# ============================================================================
# Fincept Terminal - Strategy Registry
# Auto-generated index of all available strategies
# ============================================================================

STRATEGY_REGISTRY = {
    "FCT-19E8A564": {"name": "AccumulativeInsightPortfolioRegressionAlgorithm", "category": "Portfolio Management", "path": "AccumulativeInsightPortfolioRegressionAlgorithm.py"},
    "FCT-761339E9": {"name": "AddAlphaModelAlgorithm", "category": "Alpha Model", "path": "AddAlphaModelAlgorithm.py"},
    "FCT-3CCF5CE2": {"name": "AddFutureOptionContractDataStreamingRegressionAlgorithm", "category": "Options", "path": "AddFutureOptionContractDataStreamingRegressionAlgorithm.py"},
    "FCT-2EF41B6D": {"name": "AddFutureOptionSingleOptionChainSelectedInUniverseFilterRegressionAlgorithm", "category": "Options", "path": "AddFutureOptionSingleOptionChainSelectedInUniverseFilterRegressionAlgorithm.py"},
    "FCT-5CED3309": {"name": "AddOptionContractExpiresRegressionAlgorithm", "category": "Options", "path": "AddOptionContractExpiresRegressionAlgorithm.py"},
    "FCT-202B8187": {"name": "AddOptionContractFromUniverseRegressionAlgorithm", "category": "Options", "path": "AddOptionContractFromUniverseRegressionAlgorithm.py"},
    "FCT-DA228821": {"name": "AddRemoveSecurityRegressionAlgorithm", "category": "Regression Test", "path": "AddRemoveSecurityRegressionAlgorithm.py"},
    "FCT-9874FF18": {"name": "AddRiskManagementAlgorithm", "category": "Risk Management", "path": "AddRiskManagementAlgorithm.py"},
    "FCT-8AB253F8": {"name": "AddUniverseSelectionModelAlgorithm", "category": "Universe Selection", "path": "AddUniverseSelectionModelAlgorithm.py"},
    "FCT-D137348C": {"name": "AlgorithmModeAndDeploymentTargetAlgorithm", "category": "General Strategy", "path": "AlgorithmModeAndDeploymentTargetAlgorithm.py"},
    "FCT-6C937E43": {"name": "AllShortableSymbolsCoarseSelectionRegressionAlgorithm", "category": "Regression Test", "path": "AllShortableSymbolsCoarseSelectionRegressionAlgorithm.py"},
    "FCT-F9837218": {"name": "AsynchronousUniverseRegressionAlgorithm", "category": "Universe Selection", "path": "AsynchronousUniverseRegressionAlgorithm.py"},
    "FCT-5FF79273": {"name": "AutoRegressiveIntegratedMovingAverageRegressionAlgorithm", "category": "Regression Test", "path": "AutoRegressiveIntegratedMovingAverageRegressionAlgorithm.py"},
    "FCT-C395D1D2": {"name": "AuxiliaryDataHandlersRegressionAlgorithm", "category": "Regression Test", "path": "AuxiliaryDataHandlersRegressionAlgorithm.py"},
    "FCT-0A7F740C": {"name": "BaseFrameworkRegressionAlgorithm", "category": "Regression Test", "path": "BaseFrameworkRegressionAlgorithm.py"},
    "FCT-3B2A7C04": {"name": "BasicCSharpIntegrationTemplateAlgorithm", "category": "Template", "path": "BasicCSharpIntegrationTemplateAlgorithm.py"},
    "FCT-07DF2AB7": {"name": "BasicSetAccountCurrencyAlgorithm", "category": "General Strategy", "path": "BasicSetAccountCurrencyAlgorithm.py"},
    "FCT-9A26B9BE": {"name": "BasicSetAccountCurrencyWithAmountAlgorithm", "category": "General Strategy", "path": "BasicSetAccountCurrencyWithAmountAlgorithm.py"},
    "FCT-82A09B26": {"name": "BasicTemplateAlgorithm", "category": "Template", "path": "BasicTemplateAlgorithm.py"},
    "FCT-0FAA6BDF": {"name": "BasicTemplateAxosAlgorithm", "category": "Template", "path": "BasicTemplateAxosAlgorithm.py"},
    "FCT-07CF5BDC": {"name": "BasicTemplateCfdAlgorithm", "category": "Template", "path": "BasicTemplateCfdAlgorithm.py"},
    "FCT-CED11838": {"name": "BasicTemplateContinuousFutureAlgorithm", "category": "Futures", "path": "BasicTemplateContinuousFutureAlgorithm.py"},
    "FCT-34321EAB": {"name": "BasicTemplateContinuousFutureWithExtendedMarketAlgorithm", "category": "Futures", "path": "BasicTemplateContinuousFutureWithExtendedMarketAlgorithm.py"},
    "FCT-C45FB406": {"name": "BasicTemplateCryptoAlgorithm", "category": "Crypto", "path": "BasicTemplateCryptoAlgorithm.py"},
    "FCT-F09974A0": {"name": "BasicTemplateCryptoFutureAlgorithm", "category": "Futures", "path": "BasicTemplateCryptoFutureAlgorithm.py"},
    "FCT-E96624E8": {"name": "BasicTemplateCryptoFutureHourlyAlgorithm", "category": "Futures", "path": "BasicTemplateCryptoFutureHourlyAlgorithm.py"},
    "FCT-1ADBAC8E": {"name": "BasicTemplateDailyAlgorithm", "category": "Template", "path": "BasicTemplateDailyAlgorithm.py"},
    "FCT-59CC070D": {"name": "BasicTemplateEurexFuturesAlgorithm", "category": "Futures", "path": "BasicTemplateEurexFuturesAlgorithm.py"},
    "FCT-D7F55E8F": {"name": "BasicTemplateFillForwardAlgorithm", "category": "Template", "path": "BasicTemplateFillForwardAlgorithm.py"},
    "FCT-DBF9152F": {"name": "BasicTemplateForexAlgorithm", "category": "Forex", "path": "BasicTemplateForexAlgorithm.py"},
    "FCT-EE88AED1": {"name": "BasicTemplateFrameworkAlgorithm", "category": "Template", "path": "BasicTemplateFrameworkAlgorithm.py"},
    "FCT-2426C5B7": {"name": "BasicTemplateFutureOptionAlgorithm", "category": "Options", "path": "BasicTemplateFutureOptionAlgorithm.py"},
    "FCT-1DD3D3FC": {"name": "BasicTemplateFutureRolloverAlgorithm", "category": "Futures", "path": "BasicTemplateFutureRolloverAlgorithm.py"},
    "FCT-D9822D5B": {"name": "BasicTemplateFuturesAlgorithm", "category": "Futures", "path": "BasicTemplateFuturesAlgorithm.py"},
    "FCT-C0AB4825": {"name": "BasicTemplateFuturesConsolidationAlgorithm", "category": "Futures", "path": "BasicTemplateFuturesConsolidationAlgorithm.py"},
    "FCT-B04B5965": {"name": "BasicTemplateFuturesDailyAlgorithm", "category": "Futures", "path": "BasicTemplateFuturesDailyAlgorithm.py"},
    "FCT-3F20A848": {"name": "BasicTemplateFuturesFrameworkAlgorithm", "category": "Futures", "path": "BasicTemplateFuturesFrameworkAlgorithm.py"},
    "FCT-456D112C": {"name": "BasicTemplateFuturesFrameworkWithExtendedMarketAlgorithm", "category": "Futures", "path": "BasicTemplateFuturesFrameworkWithExtendedMarketAlgorithm.py"},
    "FCT-265D788C": {"name": "BasicTemplateFuturesHistoryAlgorithm", "category": "Futures", "path": "BasicTemplateFuturesHistoryAlgorithm.py"},
    "FCT-9713D1F5": {"name": "BasicTemplateFuturesHistoryWithExtendedMarketHoursAlgorithm", "category": "Futures", "path": "BasicTemplateFuturesHistoryWithExtendedMarketHoursAlgorithm.py"},
    "FCT-D52E449D": {"name": "BasicTemplateFuturesHourlyAlgorithm", "category": "Futures", "path": "BasicTemplateFuturesHourlyAlgorithm.py"},
    "FCT-527E38F2": {"name": "BasicTemplateFuturesWithExtendedMarketAlgorithm", "category": "Futures", "path": "BasicTemplateFuturesWithExtendedMarketAlgorithm.py"},
    "FCT-074CBF2C": {"name": "BasicTemplateFuturesWithExtendedMarketDailyAlgorithm", "category": "Futures", "path": "BasicTemplateFuturesWithExtendedMarketDailyAlgorithm.py"},
    "FCT-006DF51F": {"name": "BasicTemplateFuturesWithExtendedMarketHourlyAlgorithm", "category": "Futures", "path": "BasicTemplateFuturesWithExtendedMarketHourlyAlgorithm.py"},
    "FCT-A17DA593": {"name": "BasicTemplateIndexAlgorithm", "category": "Index", "path": "BasicTemplateIndexAlgorithm.py"},
    "FCT-A8601615": {"name": "BasicTemplateIndexDailyAlgorithm", "category": "Index", "path": "BasicTemplateIndexDailyAlgorithm.py"},
    "FCT-210273A6": {"name": "BasicTemplateIndexOptionsAlgorithm", "category": "Options", "path": "BasicTemplateIndexOptionsAlgorithm.py"},
    "FCT-CB56992B": {"name": "BasicTemplateIndiaAlgorithm", "category": "Template", "path": "BasicTemplateIndiaAlgorithm.py"},
    "FCT-77306E7F": {"name": "BasicTemplateIndiaIndexAlgorithm", "category": "Index", "path": "BasicTemplateIndiaIndexAlgorithm.py"},
    "FCT-13F865B8": {"name": "BasicTemplateIntrinioEconomicData", "category": "Template", "path": "BasicTemplateIntrinioEconomicData.py"},
    "FCT-A18CA8E6": {"name": "BasicTemplateLibrary", "category": "Template", "path": "BasicTemplateLibrary.py"},
    "FCT-3EB6E68A": {"name": "BasicTemplateOptionEquityStrategyAlgorithm", "category": "Options", "path": "BasicTemplateOptionEquityStrategyAlgorithm.py"},
    "FCT-185C6BF9": {"name": "BasicTemplateOptionStrategyAlgorithm", "category": "Options", "path": "BasicTemplateOptionStrategyAlgorithm.py"},
    "FCT-29268ED2": {"name": "BasicTemplateOptionTradesAlgorithm", "category": "Options", "path": "BasicTemplateOptionTradesAlgorithm.py"},
    "FCT-9970673F": {"name": "BasicTemplateOptionsAlgorithm", "category": "Options", "path": "BasicTemplateOptionsAlgorithm.py"},
    "FCT-48AE2A59": {"name": "BasicTemplateOptionsConsolidationAlgorithm", "category": "Options", "path": "BasicTemplateOptionsConsolidationAlgorithm.py"},
    "FCT-216E29F5": {"name": "BasicTemplateOptionsDailyAlgorithm", "category": "Options", "path": "BasicTemplateOptionsDailyAlgorithm.py"},
    "FCT-702E8C68": {"name": "BasicTemplateOptionsFilterUniverseAlgorithm", "category": "Options", "path": "BasicTemplateOptionsFilterUniverseAlgorithm.py"},
    "FCT-778FF392": {"name": "BasicTemplateOptionsFrameworkAlgorithm", "category": "Options", "path": "BasicTemplateOptionsFrameworkAlgorithm.py"},
    "FCT-9F0275D6": {"name": "BasicTemplateOptionsHistoryAlgorithm", "category": "Options", "path": "BasicTemplateOptionsHistoryAlgorithm.py"},
    "FCT-77549805": {"name": "BasicTemplateOptionsHourlyAlgorithm", "category": "Options", "path": "BasicTemplateOptionsHourlyAlgorithm.py"},
    "FCT-79BA1C77": {"name": "BasicTemplateOptionsPriceModel", "category": "Options", "path": "BasicTemplateOptionsPriceModel.py"},
    "FCT-DB3B5321": {"name": "BasicTemplateSPXWeeklyIndexOptionsAlgorithm", "category": "Options", "path": "BasicTemplateSPXWeeklyIndexOptionsAlgorithm.py"},
    "FCT-88C8DA85": {"name": "BasicTemplateTradableIndexAlgorithm", "category": "Index", "path": "BasicTemplateTradableIndexAlgorithm.py"},
    "FCT-8B86F74C": {"name": "BlackLittermanPortfolioOptimizationFrameworkAlgorithm", "category": "Portfolio Management", "path": "BlackLittermanPortfolioOptimizationFrameworkAlgorithm.py"},
    "FCT-13992977": {"name": "BrokerageActivityEventHandlingAlgorithm", "category": "Brokerage", "path": "BrokerageActivityEventHandlingAlgorithm.py"},
    "FCT-21FCDA65": {"name": "BrokerageModelAlgorithm", "category": "Brokerage", "path": "BrokerageModelAlgorithm.py"},
    "FCT-181E0A50": {"name": "BubbleAlgorithm", "category": "General Strategy", "path": "BubbleAlgorithm.py"},
    "FCT-C4535414": {"name": "BybitCryptoFuturesRegressionAlgorithm", "category": "Futures", "path": "BybitCryptoFuturesRegressionAlgorithm.py"},
    "FCT-8205EE4A": {"name": "BybitCryptoRegressionAlgorithm", "category": "Crypto", "path": "BybitCryptoRegressionAlgorithm.py"},
    "FCT-E8BBF79A": {"name": "BybitCustomDataCryptoRegressionAlgorithm", "category": "Crypto", "path": "BybitCustomDataCryptoRegressionAlgorithm.py"},
    "FCT-E8875612": {"name": "CallbackCommandRegressionAlgorithm", "category": "Regression Test", "path": "CallbackCommandRegressionAlgorithm.py"},
    "FCT-D8FB9470": {"name": "CanLiquidateWithOrderPropertiesRegressionAlgorithm", "category": "Regression Test", "path": "CanLiquidateWithOrderPropertiesRegressionAlgorithm.py"},
    "FCT-65D25230": {"name": "CapmAlphaRankingFrameworkAlgorithm", "category": "Alpha Model", "path": "CapmAlphaRankingFrameworkAlgorithm.py"},
    "FCT-F172EB67": {"name": "ClassicRangeConsolidatorAlgorithm", "category": "Data Consolidation", "path": "ClassicRangeConsolidatorAlgorithm.py"},
    "FCT-5407C44C": {"name": "ClassicRangeConsolidatorWithTickAlgorithm", "category": "Data Consolidation", "path": "ClassicRangeConsolidatorWithTickAlgorithm.py"},
    "FCT-D909F7DF": {"name": "ClassicRenkoConsolidatorAlgorithm", "category": "Data Consolidation", "path": "ClassicRenkoConsolidatorAlgorithm.py"},
    "FCT-A0A879A8": {"name": "CoarseFineAsyncUniverseRegressionAlgorithm", "category": "Universe Selection", "path": "CoarseFineAsyncUniverseRegressionAlgorithm.py"},
    "FCT-CE80899F": {"name": "CoarseFineFundamentalComboAlgorithm", "category": "General Strategy", "path": "CoarseFineFundamentalComboAlgorithm.py"},
    "FCT-BF06E7EB": {"name": "CoarseFineFundamentalRegressionAlgorithm", "category": "Regression Test", "path": "CoarseFineFundamentalRegressionAlgorithm.py"},
    "FCT-5542D978": {"name": "CoarseFineOptionUniverseChainRegressionAlgorithm", "category": "Options", "path": "CoarseFineOptionUniverseChainRegressionAlgorithm.py"},
    "FCT-F95F1806": {"name": "CoarseFundamentalTop3Algorithm", "category": "General Strategy", "path": "CoarseFundamentalTop3Algorithm.py"},
    "FCT-5600B07D": {"name": "Collective2PortfolioSignalExportDemonstrationAlgorithm", "category": "Portfolio Management", "path": "Collective2PortfolioSignalExportDemonstrationAlgorithm.py"},
    "FCT-8AEECDC1": {"name": "Collective2SignalExportDemonstrationAlgorithm", "category": "General Strategy", "path": "Collective2SignalExportDemonstrationAlgorithm.py"},
    "FCT-EB692DBC": {"name": "ComboOrderTicketDemoAlgorithm", "category": "General Strategy", "path": "ComboOrderTicketDemoAlgorithm.py"},
    "FCT-203BF5C3": {"name": "ComboOrdersFillModelAlgorithm", "category": "General Strategy", "path": "ComboOrdersFillModelAlgorithm.py"},
    "FCT-5E302074": {"name": "CompleteOrderTagUpdateAlgorithm", "category": "General Strategy", "path": "CompleteOrderTagUpdateAlgorithm.py"},
    "FCT-50C4F04D": {"name": "CompositeAlphaModelFrameworkAlgorithm", "category": "Alpha Model", "path": "CompositeAlphaModelFrameworkAlgorithm.py"},
    "FCT-5A1D14B7": {"name": "CompositeRiskManagementModelFrameworkAlgorithm", "category": "Risk Management", "path": "CompositeRiskManagementModelFrameworkAlgorithm.py"},
    "FCT-9EECE18B": {"name": "ConfidenceWeightedFrameworkAlgorithm", "category": "General Strategy", "path": "ConfidenceWeightedFrameworkAlgorithm.py"},
    "FCT-C054C3D1": {"name": "ConsolidateDifferentTickTypesRegressionAlgorithm", "category": "Data Consolidation", "path": "ConsolidateDifferentTickTypesRegressionAlgorithm.py"},
    "FCT-D4F95392": {"name": "ConsolidateHourBarsIntoDailyBarsRegressionAlgorithm", "category": "Data Consolidation", "path": "ConsolidateHourBarsIntoDailyBarsRegressionAlgorithm.py"},
    "FCT-16F5EE2E": {"name": "ConsolidateRegressionAlgorithm", "category": "Data Consolidation", "path": "ConsolidateRegressionAlgorithm.py"},
    "FCT-EFBD246D": {"name": "ConstituentsQC500GeneratorAlgorithm", "category": "General Strategy", "path": "ConstituentsQC500GeneratorAlgorithm.py"},
    "FCT-DE244AD5": {"name": "ConstituentsUniverseRegressionAlgorithm", "category": "Universe Selection", "path": "ConstituentsUniverseRegressionAlgorithm.py"},
    "FCT-E27B6A38": {"name": "ContinuousFutureModelsConsistencyRegressionAlgorithm", "category": "Futures", "path": "ContinuousFutureModelsConsistencyRegressionAlgorithm.py"},
    "FCT-C573FB46": {"name": "ContinuousFutureRegressionAlgorithm", "category": "Futures", "path": "ContinuousFutureRegressionAlgorithm.py"},
    "FCT-E9C47E95": {"name": "ConvertToFrameworkAlgorithm", "category": "General Strategy", "path": "ConvertToFrameworkAlgorithm.py"},
    "FCT-C0F56022": {"name": "CorrectConsolidatedBarTypeForTickTypesAlgorithm", "category": "Data Consolidation", "path": "CorrectConsolidatedBarTypeForTickTypesAlgorithm.py"},
    "FCT-0AD9A342": {"name": "CoveredAndProtectiveCallStrategiesAlgorithm", "category": "General Strategy", "path": "CoveredAndProtectiveCallStrategiesAlgorithm.py"},
    "FCT-485EB46A": {"name": "CoveredAndProtectivePutStrategiesAlgorithm", "category": "General Strategy", "path": "CoveredAndProtectivePutStrategiesAlgorithm.py"},
    "FCT-B5A1B412": {"name": "CrunchDAOSignalExportDemonstrationAlgorithm", "category": "General Strategy", "path": "CrunchDAOSignalExportDemonstrationAlgorithm.py"},
    "FCT-390AE467": {"name": "CustomBenchmarkAlgorithm", "category": "Benchmark", "path": "CustomBenchmarkAlgorithm.py"},
    "FCT-F72D9CA4": {"name": "CustomBenchmarkRegressionAlgorithm", "category": "Regression Test", "path": "CustomBenchmarkRegressionAlgorithm.py"},
    "FCT-BDF6639E": {"name": "CustomBrokerageModelRegressionAlgorithm", "category": "Regression Test", "path": "CustomBrokerageModelRegressionAlgorithm.py"},
    "FCT-D2A1A24A": {"name": "CustomBrokerageSideOrderHandlingRegressionAlgorithm", "category": "Regression Test", "path": "CustomBrokerageSideOrderHandlingRegressionAlgorithm.py"},
    "FCT-335819E6": {"name": "CustomBrokerageSideOrderHandlingRegressionPartialAlgorithm", "category": "Regression Test", "path": "CustomBrokerageSideOrderHandlingRegressionPartialAlgorithm.py"},
    "FCT-DC4DC088": {"name": "CustomBuyingPowerModelAlgorithm", "category": "General Strategy", "path": "CustomBuyingPowerModelAlgorithm.py"},
    "FCT-DAAB71C9": {"name": "CustomChartingAlgorithm", "category": "General Strategy", "path": "CustomChartingAlgorithm.py"},
    "FCT-5FE7DA42": {"name": "CustomConsolidatorRegressionAlgorithm", "category": "Data Consolidation", "path": "CustomConsolidatorRegressionAlgorithm.py"},
    "FCT-23C6E607": {"name": "CustomDataBenchmarkRegressionAlgorithm", "category": "Regression Test", "path": "CustomDataBenchmarkRegressionAlgorithm.py"},
    "FCT-0D7003A5": {"name": "CustomDataBitcoinAlgorithm", "category": "Custom Data", "path": "CustomDataBitcoinAlgorithm.py"},
    "FCT-52D9893F": {"name": "CustomDataIconicTypesAddDataRegressionAlgorithm", "category": "Regression Test", "path": "CustomDataIconicTypesAddDataRegressionAlgorithm.py"},
    "FCT-0021591C": {"name": "CustomDataIndicatorExtensionsAlgorithm", "category": "Indicators", "path": "CustomDataIndicatorExtensionsAlgorithm.py"},
    "FCT-3EE829AC": {"name": "CustomDataLinkedIconicTypeAddDataCoarseSelectionRegressionAlgorithm", "category": "Regression Test", "path": "CustomDataLinkedIconicTypeAddDataCoarseSelectionRegressionAlgorithm.py"},
    "FCT-BAD0C3B3": {"name": "CustomDataLinkedIconicTypeAddDataOnSecuritiesChangedRegressionAlgorithm", "category": "Regression Test", "path": "CustomDataLinkedIconicTypeAddDataOnSecuritiesChangedRegressionAlgorithm.py"},
    "FCT-EA427FD2": {"name": "CustomDataMultiFileObjectStoreRegressionAlgorithm", "category": "Regression Test", "path": "CustomDataMultiFileObjectStoreRegressionAlgorithm.py"},
    "FCT-8C140F85": {"name": "CustomDataNIFTYAlgorithm", "category": "Custom Data", "path": "CustomDataNIFTYAlgorithm.py"},
    "FCT-675A0EC6": {"name": "CustomDataObjectStoreRegressionAlgorithm", "category": "Regression Test", "path": "CustomDataObjectStoreRegressionAlgorithm.py"},
    "FCT-9147ECE5": {"name": "CustomDataPropertiesRegressionAlgorithm", "category": "Regression Test", "path": "CustomDataPropertiesRegressionAlgorithm.py"},
    "FCT-67CFD0CD": {"name": "CustomDataRegressionAlgorithm", "category": "Regression Test", "path": "CustomDataRegressionAlgorithm.py"},
    "FCT-1A4DBA47": {"name": "CustomDataTypeHistoryAlgorithm", "category": "Custom Data", "path": "CustomDataTypeHistoryAlgorithm.py"},
    "FCT-A032E1EE": {"name": "CustomDataUniverseAlgorithm", "category": "Universe Selection", "path": "CustomDataUniverseAlgorithm.py"},
    "FCT-FC1DA597": {"name": "CustomDataUniverseRegressionAlgorithm", "category": "Universe Selection", "path": "CustomDataUniverseRegressionAlgorithm.py"},
    "FCT-72626C25": {"name": "CustomDataUniverseScheduledRegressionAlgorithm", "category": "Universe Selection", "path": "CustomDataUniverseScheduledRegressionAlgorithm.py"},
    "FCT-BEF6D76E": {"name": "CustomDataUsingMapFileRegressionAlgorithm", "category": "Regression Test", "path": "CustomDataUsingMapFileRegressionAlgorithm.py"},
    "FCT-95644B6E": {"name": "CustomDataZippedObjectStoreRegressionAlgorithm", "category": "Regression Test", "path": "CustomDataZippedObjectStoreRegressionAlgorithm.py"},
    "FCT-0B5CD58B": {"name": "CustomIndicatorAlgorithm", "category": "Indicators", "path": "CustomIndicatorAlgorithm.py"},
    "FCT-E42C0F2D": {"name": "CustomIndicatorWithExtensionAlgorithm", "category": "Indicators", "path": "CustomIndicatorWithExtensionAlgorithm.py"},
    "FCT-F06C15CD": {"name": "CustomMarginInterestRateModelAlgorithm", "category": "Margin", "path": "CustomMarginInterestRateModelAlgorithm.py"},
    "FCT-C77A7B18": {"name": "CustomModelsAlgorithm", "category": "General Strategy", "path": "CustomModelsAlgorithm.py"},
    "FCT-3555D255": {"name": "CustomModelsPEP8Algorithm", "category": "General Strategy", "path": "CustomModelsPEP8Algorithm.py"},
    "FCT-8C620280": {"name": "CustomOptionAssignmentRegressionAlgorithm", "category": "Options", "path": "CustomOptionAssignmentRegressionAlgorithm.py"},
    "FCT-A7E25D46": {"name": "CustomOptionExerciseModelRegressionAlgorithm", "category": "Options", "path": "CustomOptionExerciseModelRegressionAlgorithm.py"},
    "FCT-3E3DC670": {"name": "CustomPartialFillModelAlgorithm", "category": "General Strategy", "path": "CustomPartialFillModelAlgorithm.py"},
    "FCT-9C9C9891": {"name": "CustomPortfolioOptimizerRegressionAlgorithm", "category": "Portfolio Management", "path": "CustomPortfolioOptimizerRegressionAlgorithm.py"},
    "FCT-2F0E8AB5": {"name": "CustomSecurityDataFilterRegressionAlgorithm", "category": "Regression Test", "path": "CustomSecurityDataFilterRegressionAlgorithm.py"},
    "FCT-C15813B3": {"name": "CustomSecurityInitializerAlgorithm", "category": "General Strategy", "path": "CustomSecurityInitializerAlgorithm.py"},
    "FCT-3D3166AE": {"name": "CustomSettlementModelRegressionAlgorithm", "category": "Regression Test", "path": "CustomSettlementModelRegressionAlgorithm.py"},
    "FCT-324DD834": {"name": "CustomShortableProviderRegressionAlgorithm", "category": "Regression Test", "path": "CustomShortableProviderRegressionAlgorithm.py"},
    "FCT-CB434E24": {"name": "CustomUniverseSelectionModelRegressionAlgorithm", "category": "Universe Selection", "path": "CustomUniverseSelectionModelRegressionAlgorithm.py"},
    "FCT-57E3FCCE": {"name": "CustomVolatilityModelAlgorithm", "category": "General Strategy", "path": "CustomVolatilityModelAlgorithm.py"},
    "FCT-223472B2": {"name": "CustomWarmUpPeriodIndicatorAlgorithm", "category": "Indicators", "path": "CustomWarmUpPeriodIndicatorAlgorithm.py"},
    "FCT-DCA92403": {"name": "DailyAlgorithm", "category": "General Strategy", "path": "DailyAlgorithm.py"},
    "FCT-5DD0A982": {"name": "DataConsolidationAlgorithm", "category": "Data Consolidation", "path": "DataConsolidationAlgorithm.py"},
    "FCT-2D323EF8": {"name": "DelistingEventsAlgorithm", "category": "Corporate Actions", "path": "DelistingEventsAlgorithm.py"},
    "FCT-6513B96C": {"name": "DescendingCustomDataObjectStoreRegressionAlgorithm", "category": "Regression Test", "path": "DescendingCustomDataObjectStoreRegressionAlgorithm.py"},
    "FCT-E476428A": {"name": "DisplacedMovingAverageRibbon", "category": "General Strategy", "path": "DisplacedMovingAverageRibbon.py"},
    "FCT-3A64A758": {"name": "DividendAlgorithm", "category": "Corporate Actions", "path": "DividendAlgorithm.py"},
    "FCT-FFA7AD77": {"name": "DropboxBaseDataUniverseSelectionAlgorithm", "category": "Universe Selection", "path": "DropboxBaseDataUniverseSelectionAlgorithm.py"},
    "FCT-43A9D681": {"name": "DropboxCoarseFineAlgorithm", "category": "General Strategy", "path": "DropboxCoarseFineAlgorithm.py"},
    "FCT-C02B7DE9": {"name": "DropboxUniverseSelectionAlgorithm", "category": "Universe Selection", "path": "DropboxUniverseSelectionAlgorithm.py"},
    "FCT-D86D36A8": {"name": "DynamicSecurityDataRegressionAlgorithm", "category": "Regression Test", "path": "DynamicSecurityDataRegressionAlgorithm.py"},
    "FCT-2A9A1A33": {"name": "ETFConstituentUniverseCompositeDelistingRegressionAlgorithm", "category": "ETF", "path": "ETFConstituentUniverseCompositeDelistingRegressionAlgorithm.py"},
    "FCT-D7673A55": {"name": "ETFConstituentUniverseCompositeDelistingRegressionAlgorithmNoAddEquityETF", "category": "ETF", "path": "ETFConstituentUniverseCompositeDelistingRegressionAlgorithmNoAddEquityETF.py"},
    "FCT-9E29F41C": {"name": "ETFConstituentUniverseFilterFunctionRegressionAlgorithm", "category": "ETF", "path": "ETFConstituentUniverseFilterFunctionRegressionAlgorithm.py"},
    "FCT-D46C4922": {"name": "ETFConstituentUniverseFrameworkRegressionAlgorithm", "category": "ETF", "path": "ETFConstituentUniverseFrameworkRegressionAlgorithm.py"},
    "FCT-B97EAA99": {"name": "ETFConstituentUniverseMappedCompositeRegressionAlgorithm", "category": "ETF", "path": "ETFConstituentUniverseMappedCompositeRegressionAlgorithm.py"},
    "FCT-4249AE56": {"name": "ETFConstituentUniverseRSIAlphaModelAlgorithm", "category": "ETF", "path": "ETFConstituentUniverseRSIAlphaModelAlgorithm.py"},
    "FCT-A8E104E5": {"name": "ETFConstituentsFrameworkAlgorithm", "category": "ETF", "path": "ETFConstituentsFrameworkAlgorithm.py"},
    "FCT-A7B56E18": {"name": "ETFConstituentsFrameworkWithDifferentSelectionModelAlgorithm", "category": "ETF", "path": "ETFConstituentsFrameworkWithDifferentSelectionModelAlgorithm.py"},
    "FCT-D3112758": {"name": "ETFGlobalRotationAlgorithm", "category": "ETF", "path": "ETFGlobalRotationAlgorithm.py"},
    "FCT-A3A4BE5B": {"name": "EmaCrossAlphaModelFrameworkRegressionAlgorithm", "category": "Alpha Model", "path": "EmaCrossAlphaModelFrameworkRegressionAlgorithm.py"},
    "FCT-EE365736": {"name": "EmaCrossFuturesFrontMonthAlgorithm", "category": "Futures", "path": "EmaCrossFuturesFrontMonthAlgorithm.py"},
    "FCT-E66F50F9": {"name": "EmaCrossUniverseSelectionAlgorithm", "category": "Universe Selection", "path": "EmaCrossUniverseSelectionAlgorithm.py"},
    "FCT-AE32C215": {"name": "EmaCrossUniverseSelectionFrameworkAlgorithm", "category": "Universe Selection", "path": "EmaCrossUniverseSelectionFrameworkAlgorithm.py"},
    "FCT-62C5A2BF": {"name": "ExpiryHelperAlphaModelFrameworkAlgorithm", "category": "Alpha Model", "path": "ExpiryHelperAlphaModelFrameworkAlgorithm.py"},
    "FCT-47C778A4": {"name": "ExtendedMarketTradingRegressionAlgorithm", "category": "Regression Test", "path": "ExtendedMarketTradingRegressionAlgorithm.py"},
    "FCT-E75184B8": {"name": "FilterUniverseRegressionAlgorithm", "category": "Universe Selection", "path": "FilterUniverseRegressionAlgorithm.py"},
    "FCT-F0179E57": {"name": "FilteredIdentityAlgorithm", "category": "General Strategy", "path": "FilteredIdentityAlgorithm.py"},
    "FCT-29D656ED": {"name": "FinancialAdvisorDemoAlgorithm", "category": "General Strategy", "path": "FinancialAdvisorDemoAlgorithm.py"},
    "FCT-BB3C695A": {"name": "FineFundamentalFilteredUniverseRegressionAlgorithm", "category": "Universe Selection", "path": "FineFundamentalFilteredUniverseRegressionAlgorithm.py"},
    "FCT-0212DBCD": {"name": "ForwardDataOnlyFillModelAlgorithm", "category": "General Strategy", "path": "ForwardDataOnlyFillModelAlgorithm.py"},
    "FCT-BA248F90": {"name": "FractionalQuantityRegressionAlgorithm", "category": "Regression Test", "path": "FractionalQuantityRegressionAlgorithm.py"},
    "FCT-1C8EF029": {"name": "FuncRiskFreeRateInterestRateModelWithPythonLambda", "category": "Risk Management", "path": "FuncRiskFreeRateInterestRateModelWithPythonLambda.py"},
    "FCT-874367FD": {"name": "FundamentalCustomSelectionTimeRegressionAlgorithm", "category": "Regression Test", "path": "FundamentalCustomSelectionTimeRegressionAlgorithm.py"},
    "FCT-4A7607D6": {"name": "FundamentalRegressionAlgorithm", "category": "Regression Test", "path": "FundamentalRegressionAlgorithm.py"},
    "FCT-0A8C8781": {"name": "FundamentalUniverseSelectionAlgorithm", "category": "Universe Selection", "path": "FundamentalUniverseSelectionAlgorithm.py"},
    "FCT-19976618": {"name": "FundamentalUniverseSelectionRegressionAlgorithm", "category": "Universe Selection", "path": "FundamentalUniverseSelectionRegressionAlgorithm.py"},
    "FCT-E85797B9": {"name": "FutureContractsExtendedMarketHoursRegressionAlgorithm", "category": "Futures", "path": "FutureContractsExtendedMarketHoursRegressionAlgorithm.py"},
    "FCT-1855F876": {"name": "FutureOptionBuySellCallIntradayRegressionAlgorithm", "category": "Options", "path": "FutureOptionBuySellCallIntradayRegressionAlgorithm.py"},
    "FCT-DE2ACA2C": {"name": "FutureOptionCallITMExpiryRegressionAlgorithm", "category": "Options", "path": "FutureOptionCallITMExpiryRegressionAlgorithm.py"},
    "FCT-B4342086": {"name": "FutureOptionCallOTMExpiryRegressionAlgorithm", "category": "Options", "path": "FutureOptionCallOTMExpiryRegressionAlgorithm.py"},
    "FCT-16536530": {"name": "FutureOptionDailyRegressionAlgorithm", "category": "Options", "path": "FutureOptionDailyRegressionAlgorithm.py"},
    "FCT-BC31D77F": {"name": "FutureOptionHourlyRegressionAlgorithm", "category": "Options", "path": "FutureOptionHourlyRegressionAlgorithm.py"},
    "FCT-AA93FB6A": {"name": "FutureOptionMultipleContractsInDifferentContractMonthsWithSameUnderlyingFutureRegressionAlgorithm", "category": "Options", "path": "FutureOptionMultipleContractsInDifferentContractMonthsWithSameUnderlyingFutureRegressionAlgorithm.py"},
    "FCT-88F9D2E8": {"name": "FutureOptionPutITMExpiryRegressionAlgorithm", "category": "Options", "path": "FutureOptionPutITMExpiryRegressionAlgorithm.py"},
    "FCT-ADF65A2F": {"name": "FutureOptionPutOTMExpiryRegressionAlgorithm", "category": "Options", "path": "FutureOptionPutOTMExpiryRegressionAlgorithm.py"},
    "FCT-129041A8": {"name": "FutureOptionShortCallITMExpiryRegressionAlgorithm", "category": "Options", "path": "FutureOptionShortCallITMExpiryRegressionAlgorithm.py"},
    "FCT-68DA46AE": {"name": "FutureOptionShortCallOTMExpiryRegressionAlgorithm", "category": "Options", "path": "FutureOptionShortCallOTMExpiryRegressionAlgorithm.py"},
    "FCT-97BFC0D6": {"name": "FutureOptionShortPutITMExpiryRegressionAlgorithm", "category": "Options", "path": "FutureOptionShortPutITMExpiryRegressionAlgorithm.py"},
    "FCT-470C1BB3": {"name": "FutureOptionShortPutOTMExpiryRegressionAlgorithm", "category": "Options", "path": "FutureOptionShortPutOTMExpiryRegressionAlgorithm.py"},
    "FCT-119E482D": {"name": "FutureStopMarketOrderOnExtendedHoursRegressionAlgorithm", "category": "Futures", "path": "FutureStopMarketOrderOnExtendedHoursRegressionAlgorithm.py"},
    "FCT-2549D577": {"name": "FuturesAndFuturesOptionsExpiryTimeAndLiquidationRegressionAlgorithm", "category": "Options", "path": "FuturesAndFuturesOptionsExpiryTimeAndLiquidationRegressionAlgorithm.py"},
    "FCT-4EE8D5FD": {"name": "FuturesExtendedMarketHoursRegressionAlgorithm", "category": "Futures", "path": "FuturesExtendedMarketHoursRegressionAlgorithm.py"},
    "FCT-CA7ACD88": {"name": "FuturesMomentumAlgorithm", "category": "Futures", "path": "FuturesMomentumAlgorithm.py"},
    "FCT-7CAB8ED5": {"name": "G10CurrencySelectionModelFrameworkAlgorithm", "category": "General Strategy", "path": "G10CurrencySelectionModelFrameworkAlgorithm.py"},
    "FCT-4F55CFD9": {"name": "GetParameterRegressionAlgorithm", "category": "Regression Test", "path": "GetParameterRegressionAlgorithm.py"},
    "FCT-649F439A": {"name": "HistoricalReturnsAlphaModelFrameworkRegressionAlgorithm", "category": "Alpha Model", "path": "HistoricalReturnsAlphaModelFrameworkRegressionAlgorithm.py"},
    "FCT-4F051700": {"name": "HistoryAlgorithm", "category": "Historical Data", "path": "HistoryAlgorithm.py"},
    "FCT-17047AD3": {"name": "HistoryAuxiliaryDataRegressionAlgorithm", "category": "Regression Test", "path": "HistoryAuxiliaryDataRegressionAlgorithm.py"},
    "FCT-5077EFC4": {"name": "HistoryTickRegressionAlgorithm", "category": "Regression Test", "path": "HistoryTickRegressionAlgorithm.py"},
    "FCT-D55B4B0F": {"name": "HistoryWithCustomDataSourceRegressionAlgorithm", "category": "Regression Test", "path": "HistoryWithCustomDataSourceRegressionAlgorithm.py"},
    "FCT-52E3A84A": {"name": "HistoryWithDifferentContinuousContractDepthOffsetsRegressionAlgorithm", "category": "Regression Test", "path": "HistoryWithDifferentContinuousContractDepthOffsetsRegressionAlgorithm.py"},
    "FCT-8CB7F1CC": {"name": "HistoryWithDifferentDataMappingModeRegressionAlgorithm", "category": "Regression Test", "path": "HistoryWithDifferentDataMappingModeRegressionAlgorithm.py"},
    "FCT-25201E5E": {"name": "HistoryWithDifferentDataNormalizationModeRegressionAlgorithm", "category": "Regression Test", "path": "HistoryWithDifferentDataNormalizationModeRegressionAlgorithm.py"},
    "FCT-690AD750": {"name": "HourReverseSplitRegressionAlgorithm", "category": "Regression Test", "path": "HourReverseSplitRegressionAlgorithm.py"},
    "FCT-ADDA18D4": {"name": "HourSplitRegressionAlgorithm", "category": "Regression Test", "path": "HourSplitRegressionAlgorithm.py"},
    "FCT-5C005A63": {"name": "ImmediateExecutionModelWorksWithBinanceFeeModel", "category": "Execution Model", "path": "ImmediateExecutionModelWorksWithBinanceFeeModel.py"},
    "FCT-BDFB56F1": {"name": "InceptionDateSelectionRegressionAlgorithm", "category": "Regression Test", "path": "InceptionDateSelectionRegressionAlgorithm.py"},
    "FCT-5B348FD6": {"name": "IndexOptionBearCallSpreadAlgorithm", "category": "Options", "path": "IndexOptionBearCallSpreadAlgorithm.py"},
    "FCT-F75EB8E2": {"name": "IndexOptionBearPutSpreadAlgorithm", "category": "Options", "path": "IndexOptionBearPutSpreadAlgorithm.py"},
    "FCT-82E65BB4": {"name": "IndexOptionBullCallSpreadAlgorithm", "category": "Options", "path": "IndexOptionBullCallSpreadAlgorithm.py"},
    "FCT-1D8349B6": {"name": "IndexOptionBullPutSpreadAlgorithm", "category": "Options", "path": "IndexOptionBullPutSpreadAlgorithm.py"},
    "FCT-C204FEB8": {"name": "IndexOptionBuySellCallIntradayRegressionAlgorithm", "category": "Options", "path": "IndexOptionBuySellCallIntradayRegressionAlgorithm.py"},
    "FCT-DC3B31DA": {"name": "IndexOptionCallButterflyAlgorithm", "category": "Options", "path": "IndexOptionCallButterflyAlgorithm.py"},
    "FCT-C629FC42": {"name": "IndexOptionCallCalendarSpreadAlgorithm", "category": "Options", "path": "IndexOptionCallCalendarSpreadAlgorithm.py"},
    "FCT-EA1D90BB": {"name": "IndexOptionCallITMExpiryRegressionAlgorithm", "category": "Options", "path": "IndexOptionCallITMExpiryRegressionAlgorithm.py"},
    "FCT-32C0EE95": {"name": "IndexOptionCallITMGreeksExpiryRegressionAlgorithm", "category": "Options", "path": "IndexOptionCallITMGreeksExpiryRegressionAlgorithm.py"},
    "FCT-6AE00A81": {"name": "IndexOptionCallOTMExpiryRegressionAlgorithm", "category": "Options", "path": "IndexOptionCallOTMExpiryRegressionAlgorithm.py"},
    "FCT-F859111A": {"name": "IndexOptionChainApisConsistencyRegressionAlgorithm", "category": "Options", "path": "IndexOptionChainApisConsistencyRegressionAlgorithm.py"},
    "FCT-F5FE9B32": {"name": "IndexOptionIronCondorAlgorithm", "category": "Options", "path": "IndexOptionIronCondorAlgorithm.py"},
    "FCT-02F5AEAE": {"name": "IndexOptionModelsConsistencyRegressionAlgorithm", "category": "Options", "path": "IndexOptionModelsConsistencyRegressionAlgorithm.py"},
    "FCT-BFEF2627": {"name": "IndexOptionPutButterflyAlgorithm", "category": "Options", "path": "IndexOptionPutButterflyAlgorithm.py"},
    "FCT-E0220F96": {"name": "IndexOptionPutCalendarSpreadAlgorithm", "category": "Options", "path": "IndexOptionPutCalendarSpreadAlgorithm.py"},
    "FCT-48BF5359": {"name": "IndexOptionPutITMExpiryRegressionAlgorithm", "category": "Options", "path": "IndexOptionPutITMExpiryRegressionAlgorithm.py"},
    "FCT-4666C54E": {"name": "IndexOptionPutOTMExpiryRegressionAlgorithm", "category": "Options", "path": "IndexOptionPutOTMExpiryRegressionAlgorithm.py"},
    "FCT-300B9FC2": {"name": "IndexOptionShortCallITMExpiryRegressionAlgorithm", "category": "Options", "path": "IndexOptionShortCallITMExpiryRegressionAlgorithm.py"},
    "FCT-57548DAA": {"name": "IndexOptionShortCallOTMExpiryRegressionAlgorithm", "category": "Options", "path": "IndexOptionShortCallOTMExpiryRegressionAlgorithm.py"},
    "FCT-D0643727": {"name": "IndexOptionShortPutITMExpiryRegressionAlgorithm", "category": "Options", "path": "IndexOptionShortPutITMExpiryRegressionAlgorithm.py"},
    "FCT-905BC971": {"name": "IndexOptionShortPutOTMExpiryRegressionAlgorithm", "category": "Options", "path": "IndexOptionShortPutOTMExpiryRegressionAlgorithm.py"},
    "FCT-EB8CE077": {"name": "IndiaDataRegressionAlgorithm", "category": "Regression Test", "path": "IndiaDataRegressionAlgorithm.py"},
    "FCT-31D18328": {"name": "IndicatorExtensionsSMAWithCustomIndicatorsRegressionAlgorithm", "category": "Indicators", "path": "IndicatorExtensionsSMAWithCustomIndicatorsRegressionAlgorithm.py"},
    "FCT-2BC353A9": {"name": "IndicatorHistoryAlgorithm", "category": "Indicators", "path": "IndicatorHistoryAlgorithm.py"},
    "FCT-B3C67AEA": {"name": "IndicatorHistoryRegressionAlgorithm", "category": "Indicators", "path": "IndicatorHistoryRegressionAlgorithm.py"},
    "FCT-9EF0798B": {"name": "IndicatorSelectorsWorkWithDifferentOptions", "category": "Options", "path": "IndicatorSelectorsWorkWithDifferentOptions.py"},
    "FCT-71C08CCA": {"name": "IndicatorSuiteAlgorithm", "category": "Indicators", "path": "IndicatorSuiteAlgorithm.py"},
    "FCT-935D3B5D": {"name": "IndicatorWarmupAlgorithm", "category": "Indicators", "path": "IndicatorWarmupAlgorithm.py"},
    "FCT-B8EB6886": {"name": "IndicatorWithRenkoBarsRegressionAlgorithm", "category": "Indicators", "path": "IndicatorWithRenkoBarsRegressionAlgorithm.py"},
    "FCT-77C48AE3": {"name": "IndustryStandardSecurityIdentifiersRegressionAlgorithm", "category": "Regression Test", "path": "IndustryStandardSecurityIdentifiersRegressionAlgorithm.py"},
    "FCT-E8E10658": {"name": "InsightScoringRegressionAlgorithm", "category": "Regression Test", "path": "InsightScoringRegressionAlgorithm.py"},
    "FCT-15D6B08D": {"name": "InsightTagAlphaRegressionAlgorithm", "category": "Alpha Model", "path": "InsightTagAlphaRegressionAlgorithm.py"},
    "FCT-955EB562": {"name": "InsightWeightingFrameworkAlgorithm", "category": "General Strategy", "path": "InsightWeightingFrameworkAlgorithm.py"},
    "FCT-FD19D095": {"name": "IronCondorStrategyAlgorithm", "category": "General Strategy", "path": "IronCondorStrategyAlgorithm.py"},
    "FCT-8863BE2D": {"name": "KerasNeuralNetworkAlgorithm", "category": "Machine Learning", "path": "KerasNeuralNetworkAlgorithm.py"},
    "FCT-C37858CB": {"name": "LimitFillRegressionAlgorithm", "category": "Regression Test", "path": "LimitFillRegressionAlgorithm.py"},
    "FCT-78D0ECA0": {"name": "LimitIfTouchedRegressionAlgorithm", "category": "Regression Test", "path": "LimitIfTouchedRegressionAlgorithm.py"},
    "FCT-1E792B32": {"name": "LiquidETFUniverseFrameworkAlgorithm", "category": "ETF", "path": "LiquidETFUniverseFrameworkAlgorithm.py"},
    "FCT-C5F5B3E0": {"name": "LiveFeaturesAlgorithm", "category": "General Strategy", "path": "LiveFeaturesAlgorithm.py"},
    "FCT-EC39F086": {"name": "LongAndShortButterflyCallStrategiesAlgorithm", "category": "General Strategy", "path": "LongAndShortButterflyCallStrategiesAlgorithm.py"},
    "FCT-812F2B68": {"name": "LongAndShortButterflyPutStrategiesAlgorithm", "category": "General Strategy", "path": "LongAndShortButterflyPutStrategiesAlgorithm.py"},
    "FCT-8F4CCF9F": {"name": "LongAndShortCallCalendarSpreadStrategiesAlgorithm", "category": "General Strategy", "path": "LongAndShortCallCalendarSpreadStrategiesAlgorithm.py"},
    "FCT-27A6F4AF": {"name": "LongAndShortPutCalendarSpreadStrategiesAlgorithm", "category": "General Strategy", "path": "LongAndShortPutCalendarSpreadStrategiesAlgorithm.py"},
    "FCT-9BF2DDCB": {"name": "LongAndShortStraddleStrategiesAlgorithm", "category": "General Strategy", "path": "LongAndShortStraddleStrategiesAlgorithm.py"},
    "FCT-73CA6D31": {"name": "LongAndShortStrangleStrategiesAlgorithm", "category": "General Strategy", "path": "LongAndShortStrangleStrategiesAlgorithm.py"},
    "FCT-BEFEB617": {"name": "LongOnlyAlphaStreamAlgorithm", "category": "Alpha Model", "path": "LongOnlyAlphaStreamAlgorithm.py"},
    "FCT-F328066F": {"name": "MACDTrendAlgorithm", "category": "Momentum", "path": "MACDTrendAlgorithm.py"},
    "FCT-EABA6096": {"name": "MacdAlphaModelFrameworkRegressionAlgorithm", "category": "Alpha Model", "path": "MacdAlphaModelFrameworkRegressionAlgorithm.py"},
    "FCT-C0569D9C": {"name": "ManuallyRemovedConsolidatorsAlgorithm", "category": "Data Consolidation", "path": "ManuallyRemovedConsolidatorsAlgorithm.py"},
    "FCT-A4B98519": {"name": "ManuallySetMarketHoursAndSymbolPropertiesDatabaseEntriesAlgorithm", "category": "General Strategy", "path": "ManuallySetMarketHoursAndSymbolPropertiesDatabaseEntriesAlgorithm.py"},
    "FCT-FB2B7755": {"name": "MarginCallEventsAlgorithm", "category": "Margin", "path": "MarginCallEventsAlgorithm.py"},
    "FCT-26E2B07B": {"name": "MarketImpactSlippageModelRegressionAlgorithm", "category": "Regression Test", "path": "MarketImpactSlippageModelRegressionAlgorithm.py"},
    "FCT-F8893107": {"name": "MarketOnCloseOrderBufferExtendedMarketHoursRegressionAlgorithm", "category": "Regression Test", "path": "MarketOnCloseOrderBufferExtendedMarketHoursRegressionAlgorithm.py"},
    "FCT-74AD11AC": {"name": "MarketOnCloseOrderBufferRegressionAlgorithm", "category": "Regression Test", "path": "MarketOnCloseOrderBufferRegressionAlgorithm.py"},
    "FCT-A5E1134A": {"name": "MarketOnOpenOnCloseAlgorithm", "category": "General Strategy", "path": "MarketOnOpenOnCloseAlgorithm.py"},
    "FCT-791ECD54": {"name": "MaximumDrawdownPercentPerSecurityFrameworkRegressionAlgorithm", "category": "Regression Test", "path": "MaximumDrawdownPercentPerSecurityFrameworkRegressionAlgorithm.py"},
    "FCT-7A279BE5": {"name": "MaximumDrawdownPercentPortfolioFrameworkRegressionAlgorithm", "category": "Portfolio Management", "path": "MaximumDrawdownPercentPortfolioFrameworkRegressionAlgorithm.py"},
    "FCT-C143732F": {"name": "MaximumSectorExposureRiskManagementModelFrameworkRegressionAlgorithm", "category": "Risk Management", "path": "MaximumSectorExposureRiskManagementModelFrameworkRegressionAlgorithm.py"},
    "FCT-7E35ADAA": {"name": "MaximumUnrealizedProfitPercentPerSecurityFrameworkRegressionAlgorithm", "category": "Regression Test", "path": "MaximumUnrealizedProfitPercentPerSecurityFrameworkRegressionAlgorithm.py"},
    "FCT-98AE653C": {"name": "MeanReversionPortfolioAlgorithm", "category": "Portfolio Management", "path": "MeanReversionPortfolioAlgorithm.py"},
    "FCT-C42B3790": {"name": "MeanVarianceOptimizationFrameworkAlgorithm", "category": "General Strategy", "path": "MeanVarianceOptimizationFrameworkAlgorithm.py"},
    "FCT-B8F7654B": {"name": "MovingAverageCrossAlgorithm", "category": "General Strategy", "path": "MovingAverageCrossAlgorithm.py"},
    "FCT-CFDE4C40": {"name": "MultipleSymbolConsolidationAlgorithm", "category": "Data Consolidation", "path": "MultipleSymbolConsolidationAlgorithm.py"},
    "FCT-D2180B48": {"name": "NLTKSentimentTradingAlgorithm", "category": "General Strategy", "path": "NLTKSentimentTradingAlgorithm.py"},
    "FCT-AE6C825A": {"name": "NakedCallStrategyAlgorithm", "category": "General Strategy", "path": "NakedCallStrategyAlgorithm.py"},
    "FCT-82AD115E": {"name": "NakedPutStrategyAlgorithm", "category": "General Strategy", "path": "NakedPutStrategyAlgorithm.py"},
    "FCT-94DBB773": {"name": "NamedArgumentsRegression", "category": "Regression Test", "path": "NamedArgumentsRegression.py"},
    "FCT-994B4750": {"name": "NoUniverseSelectorRegressionAlgorithm", "category": "Universe Selection", "path": "NoUniverseSelectorRegressionAlgorithm.py"},
    "FCT-7F8D7895": {"name": "NullBuyingPowerOptionBullCallSpreadAlgorithm", "category": "Options", "path": "NullBuyingPowerOptionBullCallSpreadAlgorithm.py"},
    "FCT-B9E54A12": {"name": "NullMarginMultipleOrdersRegressionAlgorithm", "category": "Regression Test", "path": "NullMarginMultipleOrdersRegressionAlgorithm.py"},
    "FCT-16C48497": {"name": "NullOptionAssignmentRegressionAlgorithm", "category": "Options", "path": "NullOptionAssignmentRegressionAlgorithm.py"},
    "FCT-F5080AAC": {"name": "NumeraiSignalExportDemonstrationAlgorithm", "category": "General Strategy", "path": "NumeraiSignalExportDemonstrationAlgorithm.py"},
    "FCT-6A2A6B6A": {"name": "ObjectStoreExampleAlgorithm", "category": "General Strategy", "path": "ObjectStoreExampleAlgorithm.py"},
    "FCT-5B1C96E9": {"name": "OnEndOfDayRegressionAlgorithm", "category": "Regression Test", "path": "OnEndOfDayRegressionAlgorithm.py"},
    "FCT-7E0FD2EB": {"name": "OnWarmupFinishedNoWarmup", "category": "Warmup", "path": "OnWarmupFinishedNoWarmup.py"},
    "FCT-BA4498F3": {"name": "OnWarmupFinishedRegressionAlgorithm", "category": "Regression Test", "path": "OnWarmupFinishedRegressionAlgorithm.py"},
    "FCT-370B9F0E": {"name": "OpenInterestFuturesRegressionAlgorithm", "category": "Futures", "path": "OpenInterestFuturesRegressionAlgorithm.py"},
    "FCT-A5BE1849": {"name": "OptionChainApisConsistencyRegressionAlgorithm", "category": "Options", "path": "OptionChainApisConsistencyRegressionAlgorithm.py"},
    "FCT-98E14661": {"name": "OptionChainConsistencyRegressionAlgorithm", "category": "Options", "path": "OptionChainConsistencyRegressionAlgorithm.py"},
    "FCT-A05E4856": {"name": "OptionChainFullDataRegressionAlgorithm", "category": "Options", "path": "OptionChainFullDataRegressionAlgorithm.py"},
    "FCT-662DC1F1": {"name": "OptionChainProviderAlgorithm", "category": "Options", "path": "OptionChainProviderAlgorithm.py"},
    "FCT-1D2112EA": {"name": "OptionChainedUniverseSelectionModelRegressionAlgorithm", "category": "Options", "path": "OptionChainedUniverseSelectionModelRegressionAlgorithm.py"},
    "FCT-90DAF80B": {"name": "OptionChainsMultipleFullDataRegressionAlgorithm", "category": "Options", "path": "OptionChainsMultipleFullDataRegressionAlgorithm.py"},
    "FCT-4E7CF48A": {"name": "OptionDataNullReferenceRegressionAlgorithm", "category": "Options", "path": "OptionDataNullReferenceRegressionAlgorithm.py"},
    "FCT-A9A9EB72": {"name": "OptionExerciseAssignRegressionAlgorithm", "category": "Options", "path": "OptionExerciseAssignRegressionAlgorithm.py"},
    "FCT-CFC8C48B": {"name": "OptionIndicatorsMirrorContractsRegressionAlgorithm", "category": "Options", "path": "OptionIndicatorsMirrorContractsRegressionAlgorithm.py"},
    "FCT-707335FB": {"name": "OptionIndicatorsRegressionAlgorithm", "category": "Options", "path": "OptionIndicatorsRegressionAlgorithm.py"},
    "FCT-62B73DDD": {"name": "OptionModelsConsistencyRegressionAlgorithm", "category": "Options", "path": "OptionModelsConsistencyRegressionAlgorithm.py"},
    "FCT-0FFCB469": {"name": "OptionOpenInterestRegressionAlgorithm", "category": "Options", "path": "OptionOpenInterestRegressionAlgorithm.py"},
    "FCT-9520559C": {"name": "OptionPriceModelForOptionStylesBaseRegressionAlgorithm", "category": "Options", "path": "OptionPriceModelForOptionStylesBaseRegressionAlgorithm.py"},
    "FCT-9884C10F": {"name": "OptionPriceModelForSupportedAmericanOptionRegressionAlgorithm", "category": "Options", "path": "OptionPriceModelForSupportedAmericanOptionRegressionAlgorithm.py"},
    "FCT-B34DCB29": {"name": "OptionPriceModelForSupportedAmericanOptionTimeSpanWarmupRegressionAlgorithm", "category": "Options", "path": "OptionPriceModelForSupportedAmericanOptionTimeSpanWarmupRegressionAlgorithm.py"},
    "FCT-B6D1CB41": {"name": "OptionPriceModelForSupportedEuropeanOptionRegressionAlgorithm", "category": "Options", "path": "OptionPriceModelForSupportedEuropeanOptionRegressionAlgorithm.py"},
    "FCT-6812E1E8": {"name": "OptionPriceModelForSupportedEuropeanOptionTimeSpanWarmupRegressionAlgorithm", "category": "Options", "path": "OptionPriceModelForSupportedEuropeanOptionTimeSpanWarmupRegressionAlgorithm.py"},
    "FCT-03E734EA": {"name": "OptionPriceModelForUnsupportedAmericanOptionRegressionAlgorithm", "category": "Options", "path": "OptionPriceModelForUnsupportedAmericanOptionRegressionAlgorithm.py"},
    "FCT-850F1B89": {"name": "OptionPriceModelForUnsupportedAmericanOptionTimeSpanWarmupRegressionAlgorithm", "category": "Options", "path": "OptionPriceModelForUnsupportedAmericanOptionTimeSpanWarmupRegressionAlgorithm.py"},
    "FCT-C99DFC04": {"name": "OptionPriceModelForUnsupportedEuropeanOptionRegressionAlgorithm", "category": "Options", "path": "OptionPriceModelForUnsupportedEuropeanOptionRegressionAlgorithm.py"},
    "FCT-6FBD513A": {"name": "OptionPriceModelForUnsupportedEuropeanOptionTimeSpanWarmupRegressionAlgorithm", "category": "Options", "path": "OptionPriceModelForUnsupportedEuropeanOptionTimeSpanWarmupRegressionAlgorithm.py"},
    "FCT-8E5F0BE5": {"name": "OptionRenameRegressionAlgorithm", "category": "Options", "path": "OptionRenameRegressionAlgorithm.py"},
    "FCT-D07A1F27": {"name": "OptionSplitRegressionAlgorithm", "category": "Options", "path": "OptionSplitRegressionAlgorithm.py"},
    "FCT-CB64E8E9": {"name": "OptionStrategyFactoryMethodsBaseAlgorithm", "category": "Options", "path": "OptionStrategyFactoryMethodsBaseAlgorithm.py"},
    "FCT-876722D3": {"name": "OptionUniverseFilterGreeksRegressionAlgorithm", "category": "Options", "path": "OptionUniverseFilterGreeksRegressionAlgorithm.py"},
    "FCT-AED01B14": {"name": "OptionUniverseFilterGreeksShortcutsRegressionAlgorithm", "category": "Options", "path": "OptionUniverseFilterGreeksShortcutsRegressionAlgorithm.py"},
    "FCT-62274EA6": {"name": "OptionUniverseFilterOptionsDataRegressionAlgorithm", "category": "Options", "path": "OptionUniverseFilterOptionsDataRegressionAlgorithm.py"},
    "FCT-61D659F8": {"name": "OptionUniverseHistoryRegressionAlgorithm", "category": "Options", "path": "OptionUniverseHistoryRegressionAlgorithm.py"},
    "FCT-D1943028": {"name": "OrderTicketAssignmentDemoAlgorithm", "category": "General Strategy", "path": "OrderTicketAssignmentDemoAlgorithm.py"},
    "FCT-4AD7FFC0": {"name": "OrderTicketDemoAlgorithm", "category": "General Strategy", "path": "OrderTicketDemoAlgorithm.py"},
    "FCT-73AEBCB1": {"name": "PEP8StyleBasicAlgorithm", "category": "General Strategy", "path": "PEP8StyleBasicAlgorithm.py"},
    "FCT-69B21AF4": {"name": "PandasDataFrameFromMultipleTickTypeTickHistoryRegressionAlgorithm", "category": "Regression Test", "path": "PandasDataFrameFromMultipleTickTypeTickHistoryRegressionAlgorithm.py"},
    "FCT-C16FBA05": {"name": "PandasDataFrameHistoryAlgorithm", "category": "Historical Data", "path": "PandasDataFrameHistoryAlgorithm.py"},
    "FCT-3D4D4FC7": {"name": "ParameterizedAlgorithm", "category": "General Strategy", "path": "ParameterizedAlgorithm.py"},
    "FCT-6689DBF5": {"name": "PearsonCorrelationPairsTradingAlphaModelFrameworkAlgorithm", "category": "Alpha Model", "path": "PearsonCorrelationPairsTradingAlphaModelFrameworkAlgorithm.py"},
    "FCT-B9E58D2A": {"name": "PeriodBasedHistoryRequestNotAllowedWithTickResolutionRegressionAlgorithm", "category": "Regression Test", "path": "PeriodBasedHistoryRequestNotAllowedWithTickResolutionRegressionAlgorithm.py"},
    "FCT-B4A28E80": {"name": "PortfolioRebalanceOnCustomFuncRegressionAlgorithm", "category": "Portfolio Management", "path": "PortfolioRebalanceOnCustomFuncRegressionAlgorithm.py"},
    "FCT-53259B36": {"name": "PortfolioRebalanceOnDateRulesRegressionAlgorithm", "category": "Portfolio Management", "path": "PortfolioRebalanceOnDateRulesRegressionAlgorithm.py"},
    "FCT-1D170EBB": {"name": "PortfolioTargetTagsRegressionAlgorithm", "category": "Portfolio Management", "path": "PortfolioTargetTagsRegressionAlgorithm.py"},
    "FCT-3E91D425": {"name": "PythonDictionaryFeatureRegressionAlgorithm", "category": "Regression Test", "path": "PythonDictionaryFeatureRegressionAlgorithm.py"},
    "FCT-3BE1BA87": {"name": "PytorchNeuralNetworkAlgorithm", "category": "Machine Learning", "path": "PytorchNeuralNetworkAlgorithm.py"},
    "FCT-0CB9D7FA": {"name": "QuitAfterInitializationRegressionAlgorithm", "category": "Regression Test", "path": "QuitAfterInitializationRegressionAlgorithm.py"},
    "FCT-87512128": {"name": "QuitInInitializationRegressionAlgorithm", "category": "Regression Test", "path": "QuitInInitializationRegressionAlgorithm.py"},
    "FCT-052CED9D": {"name": "RangeConsolidatorAlgorithm", "category": "Data Consolidation", "path": "RangeConsolidatorAlgorithm.py"},
    "FCT-0761902F": {"name": "RangeConsolidatorWithTickAlgorithm", "category": "Data Consolidation", "path": "RangeConsolidatorWithTickAlgorithm.py"},
    "FCT-4C4ACA6D": {"name": "RawDataRegressionAlgorithm", "category": "Regression Test", "path": "RawDataRegressionAlgorithm.py"},
    "FCT-8426823A": {"name": "RawPricesCoarseUniverseAlgorithm", "category": "Universe Selection", "path": "RawPricesCoarseUniverseAlgorithm.py"},
    "FCT-EEE07C98": {"name": "RawPricesUniverseRegressionAlgorithm", "category": "Universe Selection", "path": "RawPricesUniverseRegressionAlgorithm.py"},
    "FCT-0D15187F": {"name": "RegisterIndicatorRegressionAlgorithm", "category": "Indicators", "path": "RegisterIndicatorRegressionAlgorithm.py"},
    "FCT-D350E387": {"name": "RegressionAlgorithm", "category": "Regression Test", "path": "RegressionAlgorithm.py"},
    "FCT-CB76FD5F": {"name": "RegressionChannelAlgorithm", "category": "Regression Test", "path": "RegressionChannelAlgorithm.py"},
    "FCT-4F8A816B": {"name": "RiskParityPortfolioAlgorithm", "category": "Risk Management", "path": "RiskParityPortfolioAlgorithm.py"},
    "FCT-5A71E57F": {"name": "RollingWindowAlgorithm", "category": "General Strategy", "path": "RollingWindowAlgorithm.py"},
    "FCT-2CBD0408": {"name": "RsiAlphaModelFrameworkRegressionAlgorithm", "category": "Alpha Model", "path": "RsiAlphaModelFrameworkRegressionAlgorithm.py"},
    "FCT-9781F28A": {"name": "ScheduledEventsAlgorithm", "category": "Scheduled Events", "path": "ScheduledEventsAlgorithm.py"},
    "FCT-BC10DFCE": {"name": "ScheduledQueuingAlgorithm", "category": "Scheduled Events", "path": "ScheduledQueuingAlgorithm.py"},
    "FCT-AE6D38CF": {"name": "ScheduledUniverseRegressionAlgorithm", "category": "Universe Selection", "path": "ScheduledUniverseRegressionAlgorithm.py"},
    "FCT-3F154B00": {"name": "ScheduledUniverseSelectionModelRegressionAlgorithm", "category": "Universe Selection", "path": "ScheduledUniverseSelectionModelRegressionAlgorithm.py"},
    "FCT-1244BB8B": {"name": "ScikitLearnLinearRegressionAlgorithm", "category": "Regression Test", "path": "ScikitLearnLinearRegressionAlgorithm.py"},
    "FCT-9159A849": {"name": "SectorExposureRiskFrameworkAlgorithm", "category": "Risk Management", "path": "SectorExposureRiskFrameworkAlgorithm.py"},
    "FCT-F578C144": {"name": "SectorWeightingFrameworkAlgorithm", "category": "General Strategy", "path": "SectorWeightingFrameworkAlgorithm.py"},
    "FCT-B0B2E65B": {"name": "SecurityCustomPropertiesAlgorithm", "category": "General Strategy", "path": "SecurityCustomPropertiesAlgorithm.py"},
    "FCT-B2BE2584": {"name": "SecurityDynamicPropertyPythonClassAlgorithm", "category": "General Strategy", "path": "SecurityDynamicPropertyPythonClassAlgorithm.py"},
    "FCT-79957FB5": {"name": "SecuritySeederRegressionAlgorithm", "category": "Regression Test", "path": "SecuritySeederRegressionAlgorithm.py"},
    "FCT-BCEB1931": {"name": "SelectUniverseSymbolsFromIDRegressionAlgorithm", "category": "Universe Selection", "path": "SelectUniverseSymbolsFromIDRegressionAlgorithm.py"},
    "FCT-86D91C89": {"name": "SetCustomSettlementModelRegressionAlgorithm", "category": "Regression Test", "path": "SetCustomSettlementModelRegressionAlgorithm.py"},
    "FCT-D64ED04F": {"name": "SetEquityDataNormalizationModeOnAddEquity", "category": "General Strategy", "path": "SetEquityDataNormalizationModeOnAddEquity.py"},
    "FCT-36FF2819": {"name": "SetHoldingsLiquidateExistingHoldingsMultipleTargetsRegressionAlgorithm", "category": "Regression Test", "path": "SetHoldingsLiquidateExistingHoldingsMultipleTargetsRegressionAlgorithm.py"},
    "FCT-5A449593": {"name": "SetHoldingsMultipleTargetsRegressionAlgorithm", "category": "Regression Test", "path": "SetHoldingsMultipleTargetsRegressionAlgorithm.py"},
    "FCT-58C330FF": {"name": "SetHoldingsRegressionAlgorithm", "category": "Regression Test", "path": "SetHoldingsRegressionAlgorithm.py"},
    "FCT-EFDED6A6": {"name": "ShortableProviderOrdersRejectedRegressionAlgorithm", "category": "Regression Test", "path": "ShortableProviderOrdersRejectedRegressionAlgorithm.py"},
    "FCT-198E83AF": {"name": "SliceGetByTypeRegressionAlgorithm", "category": "Regression Test", "path": "SliceGetByTypeRegressionAlgorithm.py"},
    "FCT-9D3D6D8F": {"name": "SmaCrossUniverseSelectionAlgorithm", "category": "Universe Selection", "path": "SmaCrossUniverseSelectionAlgorithm.py"},
    "FCT-E4FEA7D1": {"name": "SpreadExecutionModelRegressionAlgorithm", "category": "Execution Model", "path": "SpreadExecutionModelRegressionAlgorithm.py"},
    "FCT-5C2FCFA1": {"name": "StableCoinsRegressionAlgorithm", "category": "Regression Test", "path": "StableCoinsRegressionAlgorithm.py"},
    "FCT-C7F868BA": {"name": "StandardDeviationExecutionModelRegressionAlgorithm", "category": "Execution Model", "path": "StandardDeviationExecutionModelRegressionAlgorithm.py"},
    "FCT-99B5F510": {"name": "StatisticsResultsAlgorithm", "category": "General Strategy", "path": "StatisticsResultsAlgorithm.py"},
    "FCT-1A300907": {"name": "StochasticIndicatorWarmsUpProperlyRegressionAlgorithm", "category": "Indicators", "path": "StochasticIndicatorWarmsUpProperlyRegressionAlgorithm.py"},
    "FCT-58C9B30E": {"name": "StopLimitOrderRegressionAlgorithm", "category": "Regression Test", "path": "StopLimitOrderRegressionAlgorithm.py"},
    "FCT-8FAFCC5D": {"name": "StringToSymbolImplicitConversionRegressionAlgorithm", "category": "Regression Test", "path": "StringToSymbolImplicitConversionRegressionAlgorithm.py"},
    "FCT-D0F1B141": {"name": "TalibIndicatorsAlgorithm", "category": "Indicators", "path": "TalibIndicatorsAlgorithm.py"},
    "FCT-42FC8E69": {"name": "TensorFlowNeuralNetworkAlgorithm", "category": "Machine Learning", "path": "TensorFlowNeuralNetworkAlgorithm.py"},
    "FCT-84B15249": {"name": "TickDataFilteringAlgorithm", "category": "General Strategy", "path": "TickDataFilteringAlgorithm.py"},
    "FCT-824A47D1": {"name": "TickHistoryRequestWithoutTickSubscriptionRegressionAlgorithm", "category": "Regression Test", "path": "TickHistoryRequestWithoutTickSubscriptionRegressionAlgorithm.py"},
    "FCT-B0BD73CA": {"name": "TiingoPriceAlgorithm", "category": "General Strategy", "path": "TiingoPriceAlgorithm.py"},
    "FCT-F8E8016B": {"name": "TimeInForceAlgorithm", "category": "General Strategy", "path": "TimeInForceAlgorithm.py"},
    "FCT-76B63DA7": {"name": "TrailingStopOrderRegressionAlgorithm", "category": "Regression Test", "path": "TrailingStopOrderRegressionAlgorithm.py"},
    "FCT-DD7ECCB4": {"name": "TrailingStopRiskFrameworkRegressionAlgorithm", "category": "Risk Management", "path": "TrailingStopRiskFrameworkRegressionAlgorithm.py"},
    "FCT-4F56A3E5": {"name": "TrainingExampleAlgorithm", "category": "General Strategy", "path": "TrainingExampleAlgorithm.py"},
    "FCT-95DFEFEB": {"name": "TrainingInitializeRegressionAlgorithm", "category": "Regression Test", "path": "TrainingInitializeRegressionAlgorithm.py"},
    "FCT-FED4E182": {"name": "TwoLegCurrencyConversionRegressionAlgorithm", "category": "Regression Test", "path": "TwoLegCurrencyConversionRegressionAlgorithm.py"},
    "FCT-953A6967": {"name": "UniverseOnlyRegressionAlgorithm", "category": "Universe Selection", "path": "UniverseOnlyRegressionAlgorithm.py"},
    "FCT-BAF35694": {"name": "UniverseSelectedRegressionAlgorithm", "category": "Universe Selection", "path": "UniverseSelectedRegressionAlgorithm.py"},
    "FCT-DBD4926F": {"name": "UniverseSelectionDefinitionsAlgorithm", "category": "Universe Selection", "path": "UniverseSelectionDefinitionsAlgorithm.py"},
    "FCT-E51F70E4": {"name": "UniverseSelectionRegressionAlgorithm", "category": "Universe Selection", "path": "UniverseSelectionRegressionAlgorithm.py"},
    "FCT-91035E43": {"name": "UniverseUnchangedRegressionAlgorithm", "category": "Universe Selection", "path": "UniverseUnchangedRegressionAlgorithm.py"},
    "FCT-D8849489": {"name": "UnregisterIndicatorRegressionAlgorithm", "category": "Indicators", "path": "UnregisterIndicatorRegressionAlgorithm.py"},
    "FCT-BFC09E5D": {"name": "UpdateOrderRegressionAlgorithm", "category": "Regression Test", "path": "UpdateOrderRegressionAlgorithm.py"},
    "FCT-90E557F4": {"name": "UserDefinedUniverseAlgorithm", "category": "Universe Selection", "path": "UserDefinedUniverseAlgorithm.py"},
    "FCT-253853F6": {"name": "VolumeRenkoConsolidatorAlgorithm", "category": "Data Consolidation", "path": "VolumeRenkoConsolidatorAlgorithm.py"},
    "FCT-8D857005": {"name": "VolumeShareSlippageModelAlgorithm", "category": "General Strategy", "path": "VolumeShareSlippageModelAlgorithm.py"},
    "FCT-2D03F945": {"name": "VolumeWeightedAveragePriceExecutionModelRegressionAlgorithm", "category": "Execution Model", "path": "VolumeWeightedAveragePriceExecutionModelRegressionAlgorithm.py"},
    "FCT-DB342081": {"name": "WarmupAlgorithm", "category": "Warmup", "path": "WarmupAlgorithm.py"},
    "FCT-E048C42D": {"name": "WarmupHistoryAlgorithm", "category": "Warmup", "path": "WarmupHistoryAlgorithm.py"},
    "FCT-161A4DE8": {"name": "WeeklyUniverseSelectionRegressionAlgorithm", "category": "Universe Selection", "path": "WeeklyUniverseSelectionRegressionAlgorithm.py"},
    "FCT-F69688F5": {"name": "ZeroedBenchmarkRegressionAlgorithm", "category": "Regression Test", "path": "ZeroedBenchmarkRegressionAlgorithm.py"},
    "FCT-FAD58DE7": {"name": "main", "category": "General Strategy", "path": "main.py"},
    "FCT-70CBDC3D": {"name": "ContingentClaimsAnalysisDefaultPredictionAlpha", "category": "Alpha Model", "path": "alphas/ContingentClaimsAnalysisDefaultPredictionAlpha.py"},
    "FCT-9D7FFCA4": {"name": "GasAndCrudeOilEnergyCorrelationAlpha", "category": "Alpha Model", "path": "alphas/GasAndCrudeOilEnergyCorrelationAlpha.py"},
    "FCT-C3B2CF90": {"name": "GlobalEquityMeanReversionIBSAlpha", "category": "Alpha Model", "path": "alphas/GlobalEquityMeanReversionIBSAlpha.py"},
    "FCT-46661FE6": {"name": "GreenblattMagicFormulaAlpha", "category": "Alpha Model", "path": "alphas/GreenblattMagicFormulaAlpha.py"},
    "FCT-5596A325": {"name": "IntradayReversalCurrencyMarketsAlpha", "category": "Alpha Model", "path": "alphas/IntradayReversalCurrencyMarketsAlpha.py"},
    "FCT-EAEEE69C": {"name": "MeanReversionLunchBreakAlpha", "category": "Alpha Model", "path": "alphas/MeanReversionLunchBreakAlpha.py"},
    "FCT-B86663BE": {"name": "MortgageRateVolatilityAlpha", "category": "Alpha Model", "path": "alphas/MortgageRateVolatilityAlpha.py"},
    "FCT-899805AE": {"name": "PriceGapMeanReversionAlpha", "category": "Alpha Model", "path": "alphas/PriceGapMeanReversionAlpha.py"},
    "FCT-41404465": {"name": "RebalancingLeveragedETFAlpha", "category": "Alpha Model", "path": "alphas/RebalancingLeveragedETFAlpha.py"},
    "FCT-B44500AA": {"name": "ShareClassMeanReversionAlpha", "category": "Alpha Model", "path": "alphas/ShareClassMeanReversionAlpha.py"},
    "FCT-EEAA6B87": {"name": "SykesShortMicroCapAlpha", "category": "Alpha Model", "path": "alphas/SykesShortMicroCapAlpha.py"},
    "FCT-217A291D": {"name": "TriangleExchangeRateArbitrageAlpha", "category": "Alpha Model", "path": "alphas/TriangleExchangeRateArbitrageAlpha.py"},
    "FCT-A6C1E2B9": {"name": "TripleLeverageETFPairVolatilityDecayAlpha", "category": "Alpha Model", "path": "alphas/TripleLeverageETFPairVolatilityDecayAlpha.py"},
    "FCT-7DFAE1BB": {"name": "VIXDualThrustAlpha", "category": "Alpha Model", "path": "alphas/VIXDualThrustAlpha.py"},
    "FCT-B103DBA0": {"name": "BasicTemplateBenchmark", "category": "Benchmark", "path": "benchmarks/BasicTemplateBenchmark.py"},
    "FCT-5B90E12B": {"name": "CoarseFineUniverseSelectionBenchmark", "category": "Benchmark", "path": "benchmarks/CoarseFineUniverseSelectionBenchmark.py"},
    "FCT-9C878F2C": {"name": "EmptyEquityAndOptions400Benchmark", "category": "Benchmark", "path": "benchmarks/EmptyEquityAndOptions400Benchmark.py"},
    "FCT-1E0D28D7": {"name": "EmptyMinute400EquityBenchmark", "category": "Benchmark", "path": "benchmarks/EmptyMinute400EquityBenchmark.py"},
    "FCT-9BA28BE5": {"name": "EmptySingleSecuritySecondEquityBenchmark", "category": "Benchmark", "path": "benchmarks/EmptySingleSecuritySecondEquityBenchmark.py"},
    "FCT-0C67D5F6": {"name": "HistoryRequestBenchmark", "category": "Benchmark", "path": "benchmarks/HistoryRequestBenchmark.py"},
    "FCT-D5F0AB7B": {"name": "IndicatorRibbonBenchmark", "category": "Benchmark", "path": "benchmarks/IndicatorRibbonBenchmark.py"},
    "FCT-5F7C7101": {"name": "ScheduledEventsBenchmark", "category": "Benchmark", "path": "benchmarks/ScheduledEventsBenchmark.py"},
    "FCT-FA9F3E6A": {"name": "StatefulCoarseUniverseSelectionBenchmark", "category": "Benchmark", "path": "benchmarks/StatefulCoarseUniverseSelectionBenchmark.py"},
    "FCT-D12D8ED1": {"name": "StatelessCoarseUniverseSelectionBenchmark", "category": "Benchmark", "path": "benchmarks/StatelessCoarseUniverseSelectionBenchmark.py"},
}
