#!/usr/bin/env python3
"""Generate updates.json for the auto-updater.

Reads env vars:
    WORK     Directory containing downloaded release assets.
    VERSION  Project version, no "v" prefix (e.g. "4.0.2").
    TAG      Git tag (e.g. "v4.0.2").
    REPO     "owner/name" (e.g. "Fincept-Corporation/FinceptTerminal").

Writes the JSON manifest to stdout. Non-matching platforms are skipped
with a "# ..." comment to stderr — output stays valid JSON on stdout.
"""
from __future__ import annotations

import hashlib
import json
import os
import pathlib
import re
import sys


def main() -> int:
    try:
        work = pathlib.Path(os.environ["WORK"])
        version = os.environ["VERSION"]
        tag = os.environ["TAG"]
        repo = os.environ["REPO"]
    except KeyError as e:
        print(f"error: missing env var {e}", file=sys.stderr)
        return 1

    release_url = f"https://github.com/{repo}/releases/tag/{tag}"

    # Platform key → filename regex. Order matters: more specific keys first.
    platforms = [
        ("windows-x64",     re.compile(rf"FinceptTerminal-{re.escape(version)}-windows-x64-setup\.exe$")),
        ("windows-arm64",   re.compile(rf"FinceptTerminal-{re.escape(version)}-windows-arm64-setup\.exe$")),
        ("linux-x64",       re.compile(rf"FinceptTerminal-{re.escape(version)}-linux-x64-setup\.run$")),
        ("linux-arm64",     re.compile(rf"FinceptTerminal-{re.escape(version)}-linux-arm64-setup\.run$")),
        ("macos-arm64",     re.compile(rf"FinceptTerminal-{re.escape(version)}-macos-arm64-setup\.(dmg|exe)$")),
        ("macos-x64",       re.compile(rf"FinceptTerminal-{re.escape(version)}-macos-x64-setup\.(dmg|exe)$")),
        ("macos-universal", re.compile(rf"FinceptTerminal-{re.escape(version)}-macos-universal-setup\.(dmg|exe)$")),
    ]

    if not work.is_dir():
        print(f"error: WORK directory not found: {work}", file=sys.stderr)
        return 1

    files = {p.name: p for p in work.iterdir() if p.is_file()}
    print(f"# Found {len(files)} asset file(s): {sorted(files)}", file=sys.stderr, flush=True)

    updates: dict[str, dict[str, str]] = {}
    for key, pattern in platforms:
        match = next((f for f in files if pattern.match(f)), None)
        if not match:
            print(f"# No asset matches {key} — skipping", file=sys.stderr, flush=True)
            continue

        path = files[match]
        sha = hashlib.sha256(path.read_bytes()).hexdigest()
        url = f"https://github.com/{repo}/releases/download/{tag}/{match}"
        updates[key] = {
            "latest-version": version,
            "download-url": url,
            "sha256": sha,
            "open-url": release_url,
            "changelog": f"Fincept Terminal v{version} — see release notes at {release_url}",
        }
        print(f"# {key}: {match} sha256={sha[:16]}...", file=sys.stderr, flush=True)

    manifest = {
        "_comment": "Auto-generated by .github/workflows/release.yml on every tag push. Do not edit by hand.",
        "schema-version": 2,
        "updates": updates,
    }
    print(json.dumps(manifest, indent=2))
    return 0


if __name__ == "__main__":
    sys.exit(main())
