import { IndicatorDefinition } from '../types';

export const OPERATORS = [
  { value: '>', label: '>' },
  { value: '<', label: '<' },
  { value: '>=', label: '>=' },
  { value: '<=', label: '<=' },
  { value: '==', label: '==' },
  { value: 'crosses_above', label: 'Crosses Above' },
  { value: 'crosses_below', label: 'Crosses Below' },
  { value: 'between', label: 'Between' },
  { value: 'crossed_above_within', label: 'Crossed Above (N bars)' },
  { value: 'crossed_below_within', label: 'Crossed Below (N bars)' },
  { value: 'rising', label: 'Rising (N bars)' },
  { value: 'falling', label: 'Falling (N bars)' },
];

export const TIMEFRAMES = [
  { value: 'live', label: 'Live (Tick)' },
  { value: '1m', label: '1 Min' },
  { value: '3m', label: '3 Min' },
  { value: '5m', label: '5 Min' },
  { value: '10m', label: '10 Min' },
  { value: '15m', label: '15 Min' },
  { value: '30m', label: '30 Min' },
  { value: '1h', label: '1 Hour' },
  { value: '4h', label: '4 Hour' },
  { value: '1d', label: '1 Day' },
];

export const INDICATOR_DEFINITIONS: IndicatorDefinition[] = [
  // ── Stock Attributes ──────────────────────────────────────────────
  {
    name: 'CLOSE',
    label: 'Close Price',
    category: 'stock_attributes',
    fields: ['value'],
    defaultField: 'value',
    params: [],
  },
  {
    name: 'OPEN',
    label: 'Open Price',
    category: 'stock_attributes',
    fields: ['value'],
    defaultField: 'value',
    params: [],
  },
  {
    name: 'HIGH',
    label: 'High Price',
    category: 'stock_attributes',
    fields: ['value'],
    defaultField: 'value',
    params: [],
  },
  {
    name: 'LOW',
    label: 'Low Price',
    category: 'stock_attributes',
    fields: ['value'],
    defaultField: 'value',
    params: [],
  },
  {
    name: 'VOLUME',
    label: 'Volume',
    category: 'stock_attributes',
    fields: ['value'],
    defaultField: 'value',
    params: [],
  },
  {
    name: 'CHANGE_PCT',
    label: 'Change %',
    category: 'stock_attributes',
    fields: ['value'],
    defaultField: 'value',
    params: [],
  },
  {
    name: 'VWAP',
    label: 'VWAP',
    category: 'stock_attributes',
    fields: ['value'],
    defaultField: 'value',
    params: [],
  },
  {
    name: 'HL2',
    label: 'HL2 (H+L)/2',
    category: 'stock_attributes',
    fields: ['value'],
    defaultField: 'value',
    params: [],
  },
  {
    name: 'HLC3',
    label: 'HLC3 (H+L+C)/3',
    category: 'stock_attributes',
    fields: ['value'],
    defaultField: 'value',
    params: [],
  },
  {
    name: 'OHLC4',
    label: 'OHLC4 (O+H+L+C)/4',
    category: 'stock_attributes',
    fields: ['value'],
    defaultField: 'value',
    params: [],
  },
  // Heikin-Ashi candles
  {
    name: 'HA_CLOSE',
    label: 'Heikin-Ashi Close',
    category: 'stock_attributes',
    fields: ['value'],
    defaultField: 'value',
    params: [],
  },
  {
    name: 'HA_OPEN',
    label: 'Heikin-Ashi Open',
    category: 'stock_attributes',
    fields: ['value'],
    defaultField: 'value',
    params: [],
  },
  {
    name: 'HA_HIGH',
    label: 'Heikin-Ashi High',
    category: 'stock_attributes',
    fields: ['value'],
    defaultField: 'value',
    params: [],
  },
  {
    name: 'HA_LOW',
    label: 'Heikin-Ashi Low',
    category: 'stock_attributes',
    fields: ['value'],
    defaultField: 'value',
    params: [],
  },
  // Pivot Points
  {
    name: 'PIVOT',
    label: 'Pivot Points',
    category: 'stock_attributes',
    fields: ['pp', 'r1', 'r2', 'r3', 's1', 's2', 's3'],
    defaultField: 'pp',
    params: [{ key: 'type', label: 'Type (0=Std,1=Fib,2=Wood,3=Cam)', default: 0, min: 0, max: 3 }],
  },
  // Keep PRICE as backward-compatible alias
  {
    name: 'PRICE',
    label: 'Price (Close)',
    category: 'stock_attributes',
    fields: ['value'],
    defaultField: 'value',
    params: [],
  },

  // ── Moving Averages ───────────────────────────────────────────────
  {
    name: 'SMA',
    label: 'SMA',
    category: 'moving_averages',
    fields: ['value'],
    defaultField: 'value',
    params: [{ key: 'period', label: 'Period', default: 20, min: 2, max: 500 }],
  },
  {
    name: 'EMA',
    label: 'EMA',
    category: 'moving_averages',
    fields: ['value'],
    defaultField: 'value',
    params: [{ key: 'period', label: 'Period', default: 12, min: 2, max: 500 }],
  },
  {
    name: 'WMA',
    label: 'WMA',
    category: 'moving_averages',
    fields: ['value'],
    defaultField: 'value',
    params: [{ key: 'period', label: 'Period', default: 9, min: 2, max: 500 }],
  },
  {
    name: 'KAMA',
    label: 'KAMA',
    category: 'moving_averages',
    fields: ['value'],
    defaultField: 'value',
    params: [
      { key: 'period', label: 'Period', default: 10, min: 2, max: 200 },
      { key: 'pow1', label: 'Fast', default: 2, min: 1, max: 50 },
      { key: 'pow2', label: 'Slow', default: 30, min: 5, max: 100 },
    ],
  },
  {
    name: 'TEMA',
    label: 'TEMA (Triple EMA)',
    category: 'moving_averages',
    fields: ['value'],
    defaultField: 'value',
    params: [{ key: 'period', label: 'Period', default: 20, min: 2, max: 500 }],
  },
  {
    name: 'DEMA',
    label: 'DEMA (Double EMA)',
    category: 'moving_averages',
    fields: ['value'],
    defaultField: 'value',
    params: [{ key: 'period', label: 'Period', default: 20, min: 2, max: 500 }],
  },
  {
    name: 'HMA',
    label: 'HMA (Hull MA)',
    category: 'moving_averages',
    fields: ['value'],
    defaultField: 'value',
    params: [{ key: 'period', label: 'Period', default: 14, min: 2, max: 500 }],
  },
  {
    name: 'RMA',
    label: 'RMA (Running MA)',
    category: 'moving_averages',
    fields: ['value'],
    defaultField: 'value',
    params: [{ key: 'period', label: 'Period', default: 14, min: 2, max: 500 }],
  },
  {
    name: 'TMA',
    label: 'TMA (Triangular MA)',
    category: 'moving_averages',
    fields: ['value'],
    defaultField: 'value',
    params: [{ key: 'period', label: 'Period', default: 20, min: 2, max: 500 }],
  },
  {
    name: 'VWMA',
    label: 'VWMA (Vol Weighted MA)',
    category: 'moving_averages',
    fields: ['value'],
    defaultField: 'value',
    params: [{ key: 'period', label: 'Period', default: 20, min: 2, max: 500 }],
  },

  // ── Momentum ──────────────────────────────────────────────────────
  {
    name: 'RSI',
    label: 'RSI',
    category: 'momentum',
    fields: ['value'],
    defaultField: 'value',
    params: [{ key: 'period', label: 'Period', default: 14, min: 2, max: 100 }],
  },
  {
    name: 'STOCHASTIC',
    label: 'Stochastic',
    category: 'momentum',
    fields: ['k', 'd'],
    defaultField: 'k',
    params: [
      { key: 'period', label: 'Period', default: 14, min: 2, max: 100 },
      { key: 'smooth', label: 'Smooth', default: 3, min: 1, max: 20 },
    ],
  },
  {
    name: 'STOCH_RSI',
    label: 'Stochastic RSI',
    category: 'momentum',
    fields: ['stoch_rsi', 'k', 'd'],
    defaultField: 'k',
    params: [
      { key: 'period', label: 'Period', default: 14, min: 2, max: 100 },
      { key: 'smooth1', label: 'Smooth K', default: 3, min: 1, max: 20 },
      { key: 'smooth2', label: 'Smooth D', default: 3, min: 1, max: 20 },
    ],
  },
  {
    name: 'WILLIAMS_R',
    label: "Williams %R",
    category: 'momentum',
    fields: ['value'],
    defaultField: 'value',
    params: [{ key: 'period', label: 'Period', default: 14, min: 2, max: 100 }],
  },
  {
    name: 'ROC',
    label: 'ROC / Momentum',
    category: 'momentum',
    fields: ['value'],
    defaultField: 'value',
    params: [{ key: 'period', label: 'Period', default: 12, min: 1, max: 100 }],
  },
  {
    name: 'TSI',
    label: 'True Strength Index',
    category: 'momentum',
    fields: ['value'],
    defaultField: 'value',
    params: [
      { key: 'window_slow', label: 'Slow', default: 25, min: 5, max: 100 },
      { key: 'window_fast', label: 'Fast', default: 13, min: 2, max: 50 },
    ],
  },
  {
    name: 'ULTIMATE_OSCILLATOR',
    label: 'Ultimate Oscillator',
    category: 'momentum',
    fields: ['value'],
    defaultField: 'value',
    params: [
      { key: 'window1', label: 'Short', default: 7, min: 1, max: 50 },
      { key: 'window2', label: 'Medium', default: 14, min: 5, max: 100 },
      { key: 'window3', label: 'Long', default: 28, min: 10, max: 200 },
    ],
  },
  {
    name: 'AWESOME_OSCILLATOR',
    label: 'Awesome Oscillator',
    category: 'momentum',
    fields: ['value'],
    defaultField: 'value',
    params: [
      { key: 'window1', label: 'Short', default: 5, min: 2, max: 50 },
      { key: 'window2', label: 'Long', default: 34, min: 10, max: 200 },
    ],
  },
  {
    name: 'PPO',
    label: 'PPO',
    category: 'momentum',
    fields: ['ppo', 'ppo_signal', 'ppo_hist'],
    defaultField: 'ppo',
    params: [
      { key: 'fast', label: 'Fast', default: 12, min: 2, max: 50 },
      { key: 'slow', label: 'Slow', default: 26, min: 5, max: 100 },
      { key: 'signal', label: 'Signal', default: 9, min: 2, max: 50 },
    ],
  },
  {
    name: 'PVO',
    label: 'PVO',
    category: 'momentum',
    fields: ['pvo', 'pvo_signal', 'pvo_hist'],
    defaultField: 'pvo',
    params: [
      { key: 'window_slow', label: 'Slow', default: 26, min: 5, max: 100 },
      { key: 'window_fast', label: 'Fast', default: 12, min: 2, max: 50 },
      { key: 'window_sign', label: 'Signal', default: 9, min: 2, max: 50 },
    ],
  },

  // ── Trend ─────────────────────────────────────────────────────────
  {
    name: 'MACD',
    label: 'MACD',
    category: 'trend',
    fields: ['line', 'signal_line', 'histogram'],
    defaultField: 'histogram',
    params: [
      { key: 'fast', label: 'Fast', default: 12, min: 2, max: 50 },
      { key: 'slow', label: 'Slow', default: 26, min: 5, max: 100 },
      { key: 'signal', label: 'Signal', default: 9, min: 2, max: 50 },
    ],
  },
  {
    name: 'ADX',
    label: 'ADX',
    category: 'trend',
    fields: ['value', 'plus_di', 'minus_di'],
    defaultField: 'value',
    params: [{ key: 'period', label: 'Period', default: 14, min: 2, max: 100 }],
  },
  {
    name: 'CCI',
    label: 'CCI',
    category: 'trend',
    fields: ['value'],
    defaultField: 'value',
    params: [{ key: 'period', label: 'Period', default: 20, min: 2, max: 100 }],
  },
  {
    name: 'SUPERTREND',
    label: 'Supertrend',
    category: 'trend',
    fields: ['value', 'direction'],
    defaultField: 'direction',
    params: [
      { key: 'period', label: 'Period', default: 10, min: 2, max: 100 },
      { key: 'multiplier', label: 'Multiplier', default: 3, min: 1, max: 10 },
    ],
  },
  {
    name: 'ICHIMOKU',
    label: 'Ichimoku',
    category: 'trend',
    fields: ['conversion', 'base', 'span_a', 'span_b'],
    defaultField: 'conversion',
    params: [
      { key: 'window1', label: 'Tenkan', default: 9, min: 2, max: 100 },
      { key: 'window2', label: 'Kijun', default: 26, min: 5, max: 100 },
      { key: 'window3', label: 'Senkou', default: 52, min: 10, max: 200 },
    ],
  },
  {
    name: 'PSAR',
    label: 'Parabolic SAR',
    category: 'trend',
    fields: ['psar', 'psar_up', 'psar_down'],
    defaultField: 'psar',
    params: [
      { key: 'step', label: 'Step', default: 0.02, min: 0.001, max: 0.5 },
      { key: 'max_step', label: 'Max Step', default: 0.2, min: 0.01, max: 1 },
    ],
  },
  {
    name: 'AROON',
    label: 'Aroon',
    category: 'trend',
    fields: ['aroon_up', 'aroon_down', 'aroon_indicator'],
    defaultField: 'aroon_indicator',
    params: [{ key: 'period', label: 'Period', default: 25, min: 2, max: 100 }],
  },
  {
    name: 'STC',
    label: 'Schaff Trend Cycle',
    category: 'trend',
    fields: ['value'],
    defaultField: 'value',
    params: [
      { key: 'window_slow', label: 'Slow', default: 50, min: 10, max: 200 },
      { key: 'window_fast', label: 'Fast', default: 23, min: 5, max: 100 },
      { key: 'cycle', label: 'Cycle', default: 10, min: 2, max: 50 },
    ],
  },
  {
    name: 'KST',
    label: 'KST',
    category: 'trend',
    fields: ['kst', 'kst_signal'],
    defaultField: 'kst',
    params: [
      { key: 'nsig', label: 'Signal', default: 9, min: 2, max: 50 },
    ],
  },
  {
    name: 'VORTEX',
    label: 'Vortex',
    category: 'trend',
    fields: ['vortex_pos', 'vortex_neg'],
    defaultField: 'vortex_pos',
    params: [{ key: 'period', label: 'Period', default: 14, min: 2, max: 100 }],
  },
  {
    name: 'DPO',
    label: 'Detrended Price Osc.',
    category: 'trend',
    fields: ['value'],
    defaultField: 'value',
    params: [{ key: 'period', label: 'Period', default: 20, min: 2, max: 100 }],
  },
  {
    name: 'TRIX',
    label: 'TRIX',
    category: 'trend',
    fields: ['value'],
    defaultField: 'value',
    params: [{ key: 'period', label: 'Period', default: 15, min: 2, max: 100 }],
  },
  {
    name: 'MASS_INDEX',
    label: 'Mass Index',
    category: 'trend',
    fields: ['value'],
    defaultField: 'value',
    params: [
      { key: 'window_fast', label: 'Fast', default: 9, min: 2, max: 50 },
      { key: 'window_slow', label: 'Slow', default: 25, min: 5, max: 100 },
    ],
  },

  // ── Volatility ────────────────────────────────────────────────────
  {
    name: 'BOLLINGER',
    label: 'Bollinger Bands',
    category: 'volatility',
    fields: ['upper', 'middle', 'lower', 'pct_b'],
    defaultField: 'pct_b',
    params: [
      { key: 'period', label: 'Period', default: 20, min: 2, max: 100 },
      { key: 'std_dev', label: 'Std Dev', default: 2, min: 1, max: 5 },
    ],
  },
  {
    name: 'ATR',
    label: 'ATR',
    category: 'volatility',
    fields: ['value'],
    defaultField: 'value',
    params: [{ key: 'period', label: 'Period', default: 14, min: 2, max: 100 }],
  },
  {
    name: 'KELTNER',
    label: 'Keltner Channel',
    category: 'volatility',
    fields: ['upper', 'middle', 'lower'],
    defaultField: 'middle',
    params: [{ key: 'period', label: 'Period', default: 20, min: 2, max: 100 }],
  },
  {
    name: 'DONCHIAN',
    label: 'Donchian Channel',
    category: 'volatility',
    fields: ['upper', 'middle', 'lower'],
    defaultField: 'middle',
    params: [{ key: 'period', label: 'Period', default: 20, min: 2, max: 100 }],
  },

  // ── Volume ────────────────────────────────────────────────────────
  {
    name: 'OBV',
    label: 'OBV',
    category: 'volume',
    fields: ['value'],
    defaultField: 'value',
    params: [],
  },
  {
    name: 'CMF',
    label: 'Chaikin Money Flow',
    category: 'volume',
    fields: ['value'],
    defaultField: 'value',
    params: [{ key: 'period', label: 'Period', default: 20, min: 2, max: 100 }],
  },
  {
    name: 'MFI',
    label: 'Money Flow Index',
    category: 'volume',
    fields: ['value'],
    defaultField: 'value',
    params: [{ key: 'period', label: 'Period', default: 14, min: 2, max: 100 }],
  },
  {
    name: 'FORCE_INDEX',
    label: 'Force Index',
    category: 'volume',
    fields: ['value'],
    defaultField: 'value',
    params: [{ key: 'period', label: 'Period', default: 13, min: 1, max: 100 }],
  },
  {
    name: 'ADI',
    label: 'Accumulation/Distribution',
    category: 'volume',
    fields: ['value'],
    defaultField: 'value',
    params: [],
  },
  {
    name: 'EOM',
    label: 'Ease of Movement',
    category: 'volume',
    fields: ['value', 'signal'],
    defaultField: 'value',
    params: [{ key: 'period', label: 'Period', default: 14, min: 2, max: 100 }],
  },
  {
    name: 'VPT',
    label: 'Volume Price Trend',
    category: 'volume',
    fields: ['value'],
    defaultField: 'value',
    params: [],
  },
  {
    name: 'NVI',
    label: 'Negative Volume Index',
    category: 'volume',
    fields: ['value'],
    defaultField: 'value',
    params: [],
  },
];

export function getIndicatorDef(name: string): IndicatorDefinition | undefined {
  return INDICATOR_DEFINITIONS.find(d => d.name === name);
}
