[project]
name = "fincept-terminal"
version = "1.0.7"
description = "A Terminal for Financial Market Analysis and Fetching all kinds of Data."
readme = "README.md"
authors = [
  { name = "Fincept Corporation", email = "dev@fincept.in" }
]

license = { text = "MIT" }

requires-python = ">=3.8"

classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

dependencies = [
  "requests>=2.31.0,<2.33.0",
  "textual==1.0.0",
  "pandas>=2.1.0,<3.0.0",
  "numpy>=2.0.0,<3.0.0",
  "matplotlib==3.9.0",
  "plotly==5.15.0",
  "sqlalchemy==2.0.34",
  "psycopg2-binary==2.9.10",
  "feedparser==6.0.11",
  "gnews",
  "statsmodels",
  "quantstats",
  "empyrical-reloaded",
  "osmnx",
  "shapely",
  "PyPDF2",
  "pdfplumber",
  "vectorbt",
  "fyers_apiv3",
  "datagovindia",
  "fredapi",
  "openai",
  "deep-translator",
  "scholarly",
  "pytest",
  "black",
  "flake8",
  "parse"
]

[tool.setuptools.packages.find]
where = ["."]

[project.scripts]
fincept = "fincept_terminal.FinceptTerminalStart:start_terminal"

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"
