[project]
name = "fincept-terminal"
version = "1.0.3"
description = "A Terminal for Financial Market Analysis and Fetching all kinds of Data."
readme = "README.md"
authors = [
  { name = "Fincept Corporation", email = "dev@fincept.in" }
]

license = { text = "MIT" }

requires-python = ">=3.8"

classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

dependencies = [
  "requests>=2.31.0,<2.33.0",
  "textual==1.0.0",
  "pandas>=2.1.0,<3.0.0",
  "numpy==1.24.0",
  "matplotlib==3.9.0",
  "plotly==5.15.0",
  "sqlalchemy==2.0.34",
  "psycopg2==2.9.6",
  "fastapi==0.115.6",
]

[project.optional-dependencies]
news = ["gnews", "feedparser"]
ML = ["statsmodels", "quantstats", "empyrical"]
geo = ["osmnx", "shapely"]
pdf = ["PyPDF2", "pdfplumber"]
trading = ["vectorbt", "fyers_apiv3"]
data = ["datagovindia", "fredapi"]
AI = ["openai", "deep-translator"]
research = ["scholarly"]
dev = ["pytest", "black", "flake8"]

[tool.setuptools.packages.find]
where = ["."]

[project.scripts]
fincept = "fincept_terminal.FinceptTerminalStart:start_terminal"

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"
