import { DataSourceConfig } from './types';

// ========== API SOURCES (10) ==========
export const API_SOURCE_CONFIGS: DataSourceConfig[] = [
  {
    id: 'rest-api',
    name: 'REST API',
    type: 'rest-api',
    category: 'api',
    icon: '🌐',
    color: '#61DAFB',
    description: 'Connect to REST API endpoints',
    testable: true,
    requiresAuth: false,
    fields: [
      { name: 'baseUrl', label: 'Base URL', type: 'url', placeholder: 'https://api.example.com', required: true },
      { name: 'authType', label: 'Authentication Type', type: 'select', required: false, defaultValue: 'none', options: [
        { label: 'None', value: 'none' },
        { label: 'API Key', value: 'apikey' },
        { label: 'Bearer Token', value: 'bearer' },
        { label: 'Basic Auth', value: 'basic' },
      ]},
      { name: 'apiKey', label: 'API Key / Token', type: 'password', placeholder: 'your-api-key', required: false },
      { name: 'headers', label: 'Custom Headers (JSON)', type: 'textarea', placeholder: '{"X-Custom": "value"}', required: false },
    ],
  },
  {
    id: 'graphql',
    name: 'GraphQL API',
    type: 'graphql',
    category: 'api',
    icon: '◆',
    color: '#E10098',
    description: 'Connect to GraphQL endpoints',
    testable: true,
    requiresAuth: false,
    fields: [
      { name: 'endpoint', label: 'GraphQL Endpoint', type: 'url', placeholder: 'https://api.example.com/graphql', required: true },
      { name: 'authToken', label: 'Auth Token', type: 'password', placeholder: 'Bearer token', required: false },
      { name: 'headers', label: 'Custom Headers (JSON)', type: 'textarea', placeholder: '{"Authorization": "Bearer token"}', required: false },
    ],
  },
  {
    id: 'websocket',
    name: 'WebSocket',
    type: 'websocket',
    category: 'streaming',
    icon: '🔌',
    color: '#00A8E8',
    description: 'Connect to WebSocket streams',
    testable: true,
    requiresAuth: false,
    fields: [
      { name: 'url', label: 'WebSocket URL', type: 'url', placeholder: 'wss://stream.example.com', required: true },
      { name: 'protocols', label: 'Protocols (comma-separated)', type: 'text', placeholder: 'protocol1,protocol2', required: false },
      { name: 'reconnect', label: 'Auto Reconnect', type: 'checkbox', required: false, defaultValue: true },
    ],
  },
  {
    id: 'grpc',
    name: 'gRPC',
    type: 'grpc',
    category: 'api',
    icon: '',
    color: '#00ADD8',
    description: 'Connect to gRPC services',
    testable: true,
    requiresAuth: false,
    fields: [
      { name: 'host', label: 'Host', type: 'text', placeholder: 'localhost', required: true },
      { name: 'port', label: 'Port', type: 'number', placeholder: '50051', required: true, defaultValue: 50051 },
      { name: 'tls', label: 'Use TLS', type: 'checkbox', required: false, defaultValue: false },
      { name: 'protoFile', label: 'Proto File Path', type: 'text', placeholder: '/path/to/service.proto', required: false },
    ],
  },
  {
    id: 'soap',
    name: 'SOAP API',
    type: 'soap',
    category: 'api',
    icon: '🧼',
    color: '#0080FF',
    description: 'Connect to SOAP web services',
    testable: true,
    requiresAuth: false,
    fields: [
      { name: 'wsdlUrl', label: 'WSDL URL', type: 'url', placeholder: 'https://api.example.com/service?wsdl', required: true },
      { name: 'username', label: 'Username', type: 'text', placeholder: 'user', required: false },
      { name: 'password', label: 'Password', type: 'password', placeholder: '••••••••', required: false },
    ],
  },
  {
    id: 'odata',
    name: 'OData API',
    type: 'odata',
    category: 'api',
    icon: '🔗',
    color: '#0078D4',
    description: 'Connect to OData services',
    testable: true,
    requiresAuth: false,
    fields: [
      { name: 'serviceRoot', label: 'Service Root URL', type: 'url', placeholder: 'https://api.example.com/odata', required: true },
      { name: 'authType', label: 'Authentication', type: 'select', required: false, defaultValue: 'none', options: [
        { label: 'None', value: 'none' },
        { label: 'Basic', value: 'basic' },
        { label: 'OAuth2', value: 'oauth2' },
      ]},
      { name: 'username', label: 'Username', type: 'text', placeholder: 'user', required: false },
      { name: 'password', label: 'Password', type: 'password', placeholder: '••••••••', required: false },
    ],
  },
  {
    id: 'mqtt',
    name: 'MQTT',
    type: 'mqtt',
    category: 'streaming',
    icon: '📡',
    color: '#660066',
    description: 'Connect to MQTT broker for IoT data',
    testable: true,
    requiresAuth: false,
    fields: [
      { name: 'broker', label: 'Broker URL', type: 'url', placeholder: 'mqtt://broker.example.com', required: true },
      { name: 'port', label: 'Port', type: 'number', placeholder: '1883', required: true, defaultValue: 1883 },
      { name: 'clientId', label: 'Client ID', type: 'text', placeholder: 'mqtt_client_123', required: false },
      { name: 'username', label: 'Username', type: 'text', placeholder: 'user', required: false },
      { name: 'password', label: 'Password', type: 'password', placeholder: '••••••••', required: false },
      { name: 'topic', label: 'Default Topic', type: 'text', placeholder: 'sensors/#', required: false },
    ],
  },
  {
    id: 'kafka',
    name: 'Apache Kafka',
    type: 'kafka',
    category: 'streaming',
    icon: '🌊',
    color: '#231F20',
    description: 'Connect to Kafka streaming platform',
    testable: true,
    requiresAuth: false,
    fields: [
      { name: 'brokers', label: 'Bootstrap Servers (comma-separated)', type: 'text', placeholder: 'localhost:9092,broker2:9092', required: true },
      { name: 'groupId', label: 'Consumer Group ID', type: 'text', placeholder: 'my-group', required: false },
      { name: 'topic', label: 'Default Topic', type: 'text', placeholder: 'my-topic', required: false },
      { name: 'sasl', label: 'Use SASL Authentication', type: 'checkbox', required: false, defaultValue: false },
      { name: 'username', label: 'SASL Username', type: 'text', placeholder: 'user', required: false },
      { name: 'password', label: 'SASL Password', type: 'password', placeholder: '••••••••', required: false },
    ],
  },
  {
    id: 'rabbitmq',
    name: 'RabbitMQ',
    type: 'rabbitmq',
    category: 'streaming',
    icon: '🐰',
    color: '#FF6600',
    description: 'Connect to RabbitMQ message broker',
    testable: true,
    requiresAuth: true,
    fields: [
      { name: 'host', label: 'Host', type: 'text', placeholder: 'localhost', required: true },
      { name: 'port', label: 'Port', type: 'number', placeholder: '5672', required: true, defaultValue: 5672 },
      { name: 'username', label: 'Username', type: 'text', placeholder: 'guest', required: true },
      { name: 'password', label: 'Password', type: 'password', placeholder: '••••••••', required: true },
      { name: 'vhost', label: 'Virtual Host', type: 'text', placeholder: '/', required: false, defaultValue: '/' },
    ],
  },
  {
    id: 'nats',
    name: 'NATS',
    type: 'nats',
    category: 'streaming',
    icon: '📮',
    color: '#375C93',
    description: 'Connect to NATS messaging system',
    testable: true,
    requiresAuth: false,
    fields: [
      { name: 'servers', label: 'Server URLs (comma-separated)', type: 'text', placeholder: 'nats://localhost:4222', required: true },
      { name: 'username', label: 'Username', type: 'text', placeholder: 'user', required: false },
      { name: 'password', label: 'Password', type: 'password', placeholder: '••••••••', required: false },
      { name: 'token', label: 'Token', type: 'password', placeholder: 'auth-token', required: false },
    ],
  },
];

// ========== CLOUD STORAGE (10) ==========
export const CLOUD_STORAGE_CONFIGS: DataSourceConfig[] = [
  {
    id: 'aws-s3',
    name: 'AWS S3',
    type: 'aws-s3',
    category: 'cloud',
    icon: '☁️',
    color: '#FF9900',
    description: 'Amazon S3 object storage',
    testable: true,
    requiresAuth: true,
    fields: [
      { name: 'region', label: 'Region', type: 'text', placeholder: 'us-east-1', required: true },
      { name: 'bucket', label: 'Bucket Name', type: 'text', placeholder: 'my-bucket', required: true },
      { name: 'accessKeyId', label: 'Access Key ID', type: 'text', placeholder: 'AKIAIOSFODNN7EXAMPLE', required: true },
      { name: 'secretAccessKey', label: 'Secret Access Key', type: 'password', placeholder: '••••••••', required: true },
      { name: 'prefix', label: 'Prefix (optional)', type: 'text', placeholder: 'data/', required: false },
    ],
  },
  {
    id: 'google-cloud-storage',
    name: 'Google Cloud Storage',
    type: 'google-cloud-storage',
    category: 'cloud',
    icon: '☁️',
    color: '#4285F4',
    description: 'Google Cloud object storage',
    testable: true,
    requiresAuth: true,
    fields: [
      { name: 'projectId', label: 'Project ID', type: 'text', placeholder: 'my-project', required: true },
      { name: 'bucket', label: 'Bucket Name', type: 'text', placeholder: 'my-bucket', required: true },
      { name: 'credentials', label: 'Service Account JSON', type: 'textarea', placeholder: 'Paste JSON credentials', required: true },
    ],
  },
  {
    id: 'azure-blob',
    name: 'Azure Blob Storage',
    type: 'azure-blob',
    category: 'cloud',
    icon: '☁️',
    color: '#0078D4',
    description: 'Microsoft Azure blob storage',
    testable: true,
    requiresAuth: true,
    fields: [
      { name: 'accountName', label: 'Account Name', type: 'text', placeholder: 'mystorageaccount', required: true },
      { name: 'accountKey', label: 'Account Key', type: 'password', placeholder: '••••••••', required: true },
      { name: 'container', label: 'Container Name', type: 'text', placeholder: 'my-container', required: true },
    ],
  },
  {
    id: 'digitalocean-spaces',
    name: 'DigitalOcean Spaces',
    type: 'digitalocean-spaces',
    category: 'cloud',
    icon: '🌊',
    color: '#0080FF',
    description: 'DigitalOcean object storage',
    testable: true,
    requiresAuth: true,
    fields: [
      { name: 'region', label: 'Region', type: 'text', placeholder: 'nyc3', required: true },
      { name: 'space', label: 'Space Name', type: 'text', placeholder: 'my-space', required: true },
      { name: 'accessKey', label: 'Access Key', type: 'text', placeholder: 'your-access-key', required: true },
      { name: 'secretKey', label: 'Secret Key', type: 'password', placeholder: '••••••••', required: true },
    ],
  },
  {
    id: 'minio',
    name: 'MinIO',
    type: 'minio',
    category: 'cloud',
    icon: '🗄️',
    color: '#C72E49',
    description: 'Self-hosted S3-compatible object storage',
    testable: true,
    requiresAuth: true,
    fields: [
      { name: 'endpoint', label: 'Endpoint', type: 'url', placeholder: 'http://localhost:9000', required: true },
      { name: 'bucket', label: 'Bucket Name', type: 'text', placeholder: 'my-bucket', required: true },
      { name: 'accessKey', label: 'Access Key', type: 'text', placeholder: 'minioadmin', required: true },
      { name: 'secretKey', label: 'Secret Key', type: 'password', placeholder: '••••••••', required: true },
    ],
  },
  {
    id: 'backblaze-b2',
    name: 'Backblaze B2',
    type: 'backblaze-b2',
    category: 'cloud',
    icon: '💾',
    color: '#FF0000',
    description: 'Backblaze B2 cloud storage',
    testable: true,
    requiresAuth: true,
    fields: [
      { name: 'keyId', label: 'Application Key ID', type: 'text', placeholder: 'your-key-id', required: true },
      { name: 'applicationKey', label: 'Application Key', type: 'password', placeholder: '••••••••', required: true },
      { name: 'bucketId', label: 'Bucket ID', type: 'text', placeholder: 'bucket-id', required: true },
    ],
  },
  {
    id: 'wasabi',
    name: 'Wasabi',
    type: 'wasabi',
    category: 'cloud',
    icon: '🥬',
    color: '#00B388',
    description: 'Wasabi hot cloud storage',
    testable: true,
    requiresAuth: true,
    fields: [
      { name: 'region', label: 'Region', type: 'text', placeholder: 'us-east-1', required: true },
      { name: 'bucket', label: 'Bucket Name', type: 'text', placeholder: 'my-bucket', required: true },
      { name: 'accessKey', label: 'Access Key', type: 'text', placeholder: 'your-access-key', required: true },
      { name: 'secretKey', label: 'Secret Key', type: 'password', placeholder: '••••••••', required: true },
    ],
  },
  {
    id: 'cloudflare-r2',
    name: 'Cloudflare R2',
    type: 'cloudflare-r2',
    category: 'cloud',
    icon: '🔶',
    color: '#F38020',
    description: 'Cloudflare R2 storage',
    testable: true,
    requiresAuth: true,
    fields: [
      { name: 'accountId', label: 'Account ID', type: 'text', placeholder: 'your-account-id', required: true },
      { name: 'bucket', label: 'Bucket Name', type: 'text', placeholder: 'my-bucket', required: true },
      { name: 'accessKeyId', label: 'Access Key ID', type: 'text', placeholder: 'access-key', required: true },
      { name: 'secretAccessKey', label: 'Secret Access Key', type: 'password', placeholder: '••••••••', required: true },
    ],
  },
  {
    id: 'oracle-cloud-storage',
    name: 'Oracle Cloud Storage',
    type: 'oracle-cloud-storage',
    category: 'cloud',
    icon: '🔴',
    color: '#F80000',
    description: 'Oracle Cloud Infrastructure object storage',
    testable: true,
    requiresAuth: true,
    fields: [
      { name: 'region', label: 'Region', type: 'text', placeholder: 'us-phoenix-1', required: true },
      { name: 'namespace', label: 'Namespace', type: 'text', placeholder: 'my-namespace', required: true },
      { name: 'bucket', label: 'Bucket Name', type: 'text', placeholder: 'my-bucket', required: true },
      { name: 'accessKey', label: 'Access Key', type: 'text', placeholder: 'access-key', required: true },
      { name: 'secretKey', label: 'Secret Key', type: 'password', placeholder: '••••••••', required: true },
    ],
  },
  {
    id: 'ibm-cloud-storage',
    name: 'IBM Cloud Object Storage',
    type: 'ibm-cloud-storage',
    category: 'cloud',
    icon: '🔵',
    color: '#0F62FE',
    description: 'IBM Cloud object storage',
    testable: true,
    requiresAuth: true,
    fields: [
      { name: 'endpoint', label: 'Endpoint', type: 'url', placeholder: 'https://s3.us.cloud-object-storage.appdomain.cloud', required: true },
      { name: 'bucket', label: 'Bucket Name', type: 'text', placeholder: 'my-bucket', required: true },
      { name: 'apiKey', label: 'API Key', type: 'password', placeholder: '••••••••', required: true },
      { name: 'serviceInstanceId', label: 'Service Instance ID', type: 'text', placeholder: 'crn:v1:...', required: true },
    ],
  },
];

// ========== MARKET DATA SOURCES (20) ==========
export const MARKET_DATA_CONFIGS: DataSourceConfig[] = [
  {
    id: 'yahoo-finance',
    name: 'Yahoo Finance',
    type: 'yahoo-finance',
    category: 'market-data',
    icon: '📈',
    color: '#7B0099',
    description: 'Free stock market data from Yahoo Finance',
    testable: true,
    requiresAuth: false,
    fields: [
      { name: 'symbols', label: 'Default Symbols (comma-separated)', type: 'text', placeholder: 'AAPL,GOOGL,MSFT', required: false },
      { name: 'interval', label: 'Default Interval', type: 'select', required: false, defaultValue: '1d', options: [
        { label: '1 minute', value: '1m' },
        { label: '5 minutes', value: '5m' },
        { label: '15 minutes', value: '15m' },
        { label: '1 hour', value: '1h' },
        { label: '1 day', value: '1d' },
        { label: '1 week', value: '1wk' },
      ]},
    ],
  },
  {
    id: 'alpha-vantage',
    name: 'Alpha Vantage',
    type: 'alpha-vantage',
    category: 'market-data',
    icon: '📊',
    color: '#2E7D32',
    description: 'Stock, forex, and crypto market data API',
    testable: true,
    requiresAuth: true,
    fields: [
      { name: 'apiKey', label: 'API Key', type: 'password', placeholder: 'your-api-key', required: true },
    ],
  },
  {
    id: 'finnhub',
    name: 'Finnhub',
    type: 'finnhub',
    category: 'market-data',
    icon: '📉',
    color: '#00D4AA',
    description: 'Real-time stock, forex, and crypto data',
    testable: true,
    requiresAuth: true,
    fields: [
      { name: 'apiKey', label: 'API Key', type: 'password', placeholder: 'your-api-key', required: true },
    ],
  },
  {
    id: 'iex-cloud',
    name: 'IEX Cloud',
    type: 'iex-cloud',
    category: 'market-data',
    icon: '💹',
    color: '#1D7DF0',
    description: 'Financial data from IEX Exchange',
    testable: true,
    requiresAuth: true,
    fields: [
      { name: 'token', label: 'API Token', type: 'password', placeholder: 'pk_...', required: true },
      { name: 'sandbox', label: 'Use Sandbox', type: 'checkbox', required: false, defaultValue: false },
    ],
  },
  {
    id: 'twelve-data',
    name: 'Twelve Data',
    type: 'twelve-data',
    category: 'market-data',
    icon: '',
    color: '#00B4D8',
    description: 'Real-time and historical financial data',
    testable: true,
    requiresAuth: true,
    fields: [
      { name: 'apiKey', label: 'API Key', type: 'password', placeholder: 'your-api-key', required: true },
    ],
  },
  {
    id: 'quandl',
    name: 'Quandl/Nasdaq Data Link',
    type: 'quandl',
    category: 'market-data',
    icon: '📚',
    color: '#FF6B6B',
    description: 'Financial and alternative datasets',
    testable: true,
    requiresAuth: true,
    fields: [
      { name: 'apiKey', label: 'API Key', type: 'password', placeholder: 'your-api-key', required: true },
    ],
  },
  {
    id: 'binance',
    name: 'Binance',
    type: 'binance',
    category: 'market-data',
    icon: '₿',
    color: '#F3BA2F',
    description: 'Cryptocurrency exchange data',
    testable: true,
    requiresAuth: true,
    fields: [
      { name: 'apiKey', label: 'API Key', type: 'password', placeholder: 'your-api-key', required: true },
      { name: 'apiSecret', label: 'API Secret', type: 'password', placeholder: '••••••••', required: true },
      { name: 'testnet', label: 'Use Testnet', type: 'checkbox', required: false, defaultValue: false },
    ],
  },
  {
    id: 'coinbase',
    name: 'Coinbase',
    type: 'coinbase',
    category: 'market-data',
    icon: '🪙',
    color: '#0052FF',
    description: 'Cryptocurrency exchange data',
    testable: true,
    requiresAuth: true,
    fields: [
      { name: 'apiKey', label: 'API Key', type: 'password', placeholder: 'your-api-key', required: true },
      { name: 'apiSecret', label: 'API Secret', type: 'password', placeholder: '••••••••', required: true },
    ],
  },
  {
    id: 'kraken',
    name: 'Kraken',
    type: 'kraken',
    category: 'market-data',
    icon: '🐙',
    color: '#5741D9',
    description: 'Cryptocurrency exchange data',
    testable: true,
    requiresAuth: true,
    fields: [
      { name: 'apiKey', label: 'API Key', type: 'password', placeholder: 'your-api-key', required: true },
      { name: 'privateKey', label: 'Private Key', type: 'password', placeholder: '••••••••', required: true },
    ],
  },
  {
    id: 'coinmarketcap',
    name: 'CoinMarketCap',
    type: 'coinmarketcap',
    category: 'market-data',
    icon: '💰',
    color: '#17A2F5',
    description: 'Cryptocurrency market data aggregator',
    testable: true,
    requiresAuth: true,
    fields: [
      { name: 'apiKey', label: 'API Key', type: 'password', placeholder: 'your-api-key', required: true },
    ],
  },
  {
    id: 'coingecko',
    name: 'CoinGecko',
    type: 'coingecko',
    category: 'market-data',
    icon: '🦎',
    color: '#8DC63F',
    description: 'Free cryptocurrency data API',
    testable: true,
    requiresAuth: false,
    fields: [
      { name: 'apiKey', label: 'API Key (Pro only)', type: 'password', placeholder: 'your-api-key', required: false },
    ],
  },
  {
    id: 'eod-historical',
    name: 'EOD Historical Data',
    type: 'eod-historical',
    category: 'market-data',
    icon: '📜',
    color: '#4A90E2',
    description: 'Historical financial data API',
    testable: true,
    requiresAuth: true,
    fields: [
      { name: 'apiToken', label: 'API Token', type: 'password', placeholder: 'your-api-token', required: true },
    ],
  },
  {
    id: 'tiingo',
    name: 'Tiingo',
    type: 'tiingo',
    category: 'market-data',
    icon: '🔔',
    color: '#FF4E50',
    description: 'Stock, crypto, and news data',
    testable: true,
    requiresAuth: true,
    fields: [
      { name: 'apiToken', label: 'API Token', type: 'password', placeholder: 'your-api-token', required: true },
    ],
  },
  {
    id: 'intrinio',
    name: 'Intrinio',
    type: 'intrinio',
    category: 'market-data',
    icon: '🏢',
    color: '#00B4D8',
    description: 'Financial data for institutions',
    testable: true,
    requiresAuth: true,
    fields: [
      { name: 'apiKey', label: 'API Key', type: 'password', placeholder: 'your-api-key', required: true },
    ],
  },
  {
    id: 'fincept',
    name: 'Fincept Data API',
    type: 'fincept',
    category: 'market-data',
    icon: '📰',
    color: '#F58025',
    description: 'Fincept Terminal Data API',
    testable: true,
    requiresAuth: true,
    fields: [
      { name: 'host', label: 'Host', type: 'text', placeholder: 'localhost', required: true },
      { name: 'port', label: 'Port', type: 'number', placeholder: '8194', required: true, defaultValue: 8194 },
    ],
  },
  {
    id: 'reuters',
    name: 'Refinitiv/Reuters',
    type: 'reuters',
    category: 'market-data',
    icon: '📡',
    color: '#FF6200',
    description: 'Refinitiv financial data API',
    testable: true,
    requiresAuth: true,
    fields: [
      { name: 'appKey', label: 'App Key', type: 'password', placeholder: 'your-app-key', required: true },
      { name: 'username', label: 'Username', type: 'text', placeholder: 'user@company.com', required: true },
      { name: 'password', label: 'Password', type: 'password', placeholder: '••••••••', required: true },
    ],
  },
  {
    id: 'marketstack',
    name: 'Marketstack',
    type: 'marketstack',
    category: 'market-data',
    icon: '🏦',
    color: '#4CAF50',
    description: 'Real-time and historical stock data',
    testable: true,
    requiresAuth: true,
    fields: [
      { name: 'apiKey', label: 'API Key', type: 'password', placeholder: 'your-api-key', required: true },
      { name: 'https', label: 'Use HTTPS (paid plans)', type: 'checkbox', required: false, defaultValue: false },
    ],
  },
  {
    id: 'finage',
    name: 'Finage',
    type: 'finage',
    category: 'market-data',
    icon: '💵',
    color: '#00C853',
    description: 'Real-time and historical market data',
    testable: true,
    requiresAuth: true,
    fields: [
      { name: 'apiKey', label: 'API Key', type: 'password', placeholder: 'your-api-key', required: true },
    ],
  },
  {
    id: 'tradier',
    name: 'Tradier',
    type: 'tradier',
    category: 'market-data',
    icon: '🎯',
    color: '#00A8E8',
    description: 'Brokerage and market data API',
    testable: true,
    requiresAuth: true,
    fields: [
      { name: 'accessToken', label: 'Access Token', type: 'password', placeholder: 'your-access-token', required: true },
      { name: 'sandbox', label: 'Use Sandbox', type: 'checkbox', required: false, defaultValue: false },
    ],
  },
];

// ========== SEARCH & ANALYTICS (5) ==========
export const SEARCH_ANALYTICS_CONFIGS: DataSourceConfig[] = [
  {
    id: 'elasticsearch',
    name: 'Elasticsearch',
    type: 'elasticsearch',
    category: 'database',
    icon: '🔍',
    color: '#005571',
    description: 'Distributed search and analytics engine',
    testable: true,
    requiresAuth: false,
    fields: [
      { name: 'node', label: 'Node URL', type: 'url', placeholder: 'http://localhost:9200', required: true },
      { name: 'username', label: 'Username', type: 'text', placeholder: 'elastic', required: false },
      { name: 'password', label: 'Password', type: 'password', placeholder: '••••••••', required: false },
      { name: 'index', label: 'Default Index', type: 'text', placeholder: 'my-index', required: false },
    ],
  },
  {
    id: 'opensearch',
    name: 'OpenSearch',
    type: 'opensearch',
    category: 'database',
    icon: '🔎',
    color: '#003B5C',
    description: 'Open-source fork of Elasticsearch',
    testable: true,
    requiresAuth: false,
    fields: [
      { name: 'node', label: 'Node URL', type: 'url', placeholder: 'https://localhost:9200', required: true },
      { name: 'username', label: 'Username', type: 'text', placeholder: 'admin', required: false },
      { name: 'password', label: 'Password', type: 'password', placeholder: '••••••••', required: false },
    ],
  },
  {
    id: 'solr',
    name: 'Apache Solr',
    type: 'solr',
    category: 'database',
    icon: '☀️',
    color: '#D9411E',
    description: 'Enterprise search platform',
    testable: true,
    requiresAuth: false,
    fields: [
      { name: 'host', label: 'Host', type: 'url', placeholder: 'http://localhost:8983/solr', required: true },
      { name: 'collection', label: 'Collection', type: 'text', placeholder: 'my-collection', required: false },
    ],
  },
  {
    id: 'algolia',
    name: 'Algolia',
    type: 'algolia',
    category: 'database',
    icon: '🔷',
    color: '#5468FF',
    description: 'Hosted search API',
    testable: true,
    requiresAuth: true,
    fields: [
      { name: 'appId', label: 'Application ID', type: 'text', placeholder: 'your-app-id', required: true },
      { name: 'apiKey', label: 'API Key', type: 'password', placeholder: '••••••••', required: true },
      { name: 'index', label: 'Index Name', type: 'text', placeholder: 'my_index', required: false },
    ],
  },
  {
    id: 'meilisearch',
    name: 'MeiliSearch',
    type: 'meilisearch',
    category: 'database',
    icon: '',
    color: '#FF5CAA',
    description: 'Lightning-fast search API',
    testable: true,
    requiresAuth: true,
    fields: [
      { name: 'host', label: 'Host', type: 'url', placeholder: 'http://localhost:7700', required: true },
      { name: 'apiKey', label: 'API Key', type: 'password', placeholder: '••••••••', required: false },
      { name: 'index', label: 'Index Name', type: 'text', placeholder: 'movies', required: false },
    ],
  },
];

// ========== DATA WAREHOUSES (4) ==========
export const DATA_WAREHOUSE_CONFIGS: DataSourceConfig[] = [
  {
    id: 'bigquery',
    name: 'Google BigQuery',
    type: 'bigquery',
    category: 'database',
    icon: '📊',
    color: '#4285F4',
    description: 'Serverless data warehouse',
    testable: true,
    requiresAuth: true,
    fields: [
      { name: 'projectId', label: 'Project ID', type: 'text', placeholder: 'my-project', required: true },
      { name: 'dataset', label: 'Dataset', type: 'text', placeholder: 'my_dataset', required: false },
      { name: 'credentials', label: 'Service Account JSON', type: 'textarea', placeholder: 'Paste JSON credentials', required: true },
    ],
  },
  {
    id: 'redshift',
    name: 'Amazon Redshift',
    type: 'redshift',
    category: 'database',
    icon: '🔴',
    color: '#E25555',
    description: 'AWS data warehouse',
    testable: true,
    requiresAuth: true,
    fields: [
      { name: 'host', label: 'Host', type: 'text', placeholder: 'cluster.region.redshift.amazonaws.com', required: true },
      { name: 'port', label: 'Port', type: 'number', placeholder: '5439', required: true, defaultValue: 5439 },
      { name: 'database', label: 'Database', type: 'text', placeholder: 'dev', required: true },
      { name: 'username', label: 'Username', type: 'text', placeholder: 'awsuser', required: true },
      { name: 'password', label: 'Password', type: 'password', placeholder: '••••••••', required: true },
    ],
  },
  {
    id: 'databricks',
    name: 'Databricks',
    type: 'databricks',
    category: 'database',
    icon: '🧱',
    color: '#FF3621',
    description: 'Unified analytics platform',
    testable: true,
    requiresAuth: true,
    fields: [
      { name: 'serverHostname', label: 'Server Hostname', type: 'text', placeholder: 'your-workspace.cloud.databricks.com', required: true },
      { name: 'httpPath', label: 'HTTP Path', type: 'text', placeholder: '/sql/1.0/warehouses/...', required: true },
      { name: 'accessToken', label: 'Personal Access Token', type: 'password', placeholder: 'dapi...', required: true },
    ],
  },
  {
    id: 'synapse',
    name: 'Azure Synapse',
    type: 'synapse',
    category: 'database',
    icon: '🔷',
    color: '#0078D4',
    description: 'Azure analytics service',
    testable: true,
    requiresAuth: true,
    fields: [
      { name: 'server', label: 'Server', type: 'text', placeholder: 'workspace.sql.azuresynapse.net', required: true },
      { name: 'database', label: 'Database', type: 'text', placeholder: 'sqlpool', required: true },
      { name: 'username', label: 'Username', type: 'text', placeholder: 'sqladmin', required: true },
      { name: 'password', label: 'Password', type: 'password', placeholder: '••••••••', required: true },
    ],
  },
];

export const MARKET_SOURCE_CONFIGS: DataSourceConfig[] = [
  ...API_SOURCE_CONFIGS,
  ...CLOUD_STORAGE_CONFIGS,
  ...MARKET_DATA_CONFIGS,
  ...SEARCH_ANALYTICS_CONFIGS,
  ...DATA_WAREHOUSE_CONFIGS,
];
