import { DataSourceConfig } from './types';

// ========== RELATIONAL DATABASES (9) ==========
export const RELATIONAL_DB_CONFIGS: DataSourceConfig[] = [
  {
    id: 'postgresql',
    name: 'PostgreSQL',
    type: 'postgresql',
    category: 'database',
    icon: '🐘',
    color: '#336791',
    description: 'Open-source relational database with advanced features',
    testable: true,
    requiresAuth: true,
    fields: [
      { name: 'host', label: 'Host', type: 'text', placeholder: 'localhost', required: true },
      { name: 'port', label: 'Port', type: 'number', placeholder: '5432', required: true, defaultValue: 5432 },
      { name: 'database', label: 'Database', type: 'text', placeholder: 'mydb', required: true },
      { name: 'username', label: 'Username', type: 'text', placeholder: 'postgres', required: true },
      { name: 'password', label: 'Password', type: 'password', placeholder: '••••••••', required: true },
      { name: 'ssl', label: 'Use SSL', type: 'checkbox', required: false, defaultValue: false },
    ],
  },
  {
    id: 'mysql',
    name: 'MySQL',
    type: 'mysql',
    category: 'database',
    icon: '🐬',
    color: '#4479A1',
    description: 'Popular open-source relational database',
    testable: true,
    requiresAuth: true,
    fields: [
      { name: 'host', label: 'Host', type: 'text', placeholder: 'localhost', required: true },
      { name: 'port', label: 'Port', type: 'number', placeholder: '3306', required: true, defaultValue: 3306 },
      { name: 'database', label: 'Database', type: 'text', placeholder: 'mydb', required: true },
      { name: 'username', label: 'Username', type: 'text', placeholder: 'root', required: true },
      { name: 'password', label: 'Password', type: 'password', placeholder: '••••••••', required: true },
    ],
  },
  {
    id: 'mariadb',
    name: 'MariaDB',
    type: 'mariadb',
    category: 'database',
    icon: '🦭',
    color: '#003545',
    description: 'MySQL-compatible relational database fork',
    testable: true,
    requiresAuth: true,
    fields: [
      { name: 'host', label: 'Host', type: 'text', placeholder: 'localhost', required: true },
      { name: 'port', label: 'Port', type: 'number', placeholder: '3306', required: true, defaultValue: 3306 },
      { name: 'database', label: 'Database', type: 'text', placeholder: 'mydb', required: true },
      { name: 'username', label: 'Username', type: 'text', placeholder: 'root', required: true },
      { name: 'password', label: 'Password', type: 'password', placeholder: '••••••••', required: true },
    ],
  },
  {
    id: 'sqlite',
    name: 'SQLite',
    type: 'sqlite',
    category: 'database',
    icon: '💾',
    color: '#003B57',
    description: 'Lightweight embedded SQL database',
    testable: true,
    requiresAuth: false,
    fields: [
      { name: 'filepath', label: 'Database File Path', type: 'text', placeholder: '/path/to/database.db', required: true },
      { name: 'readonly', label: 'Read Only', type: 'checkbox', required: false, defaultValue: false },
    ],
  },
  {
    id: 'oracle',
    name: 'Oracle Database',
    type: 'oracle',
    category: 'database',
    icon: '🔴',
    color: '#F80000',
    description: 'Enterprise-grade relational database',
    testable: true,
    requiresAuth: true,
    fields: [
      { name: 'host', label: 'Host', type: 'text', placeholder: 'localhost', required: true },
      { name: 'port', label: 'Port', type: 'number', placeholder: '1521', required: true, defaultValue: 1521 },
      { name: 'serviceName', label: 'Service Name', type: 'text', placeholder: 'ORCL', required: true },
      { name: 'username', label: 'Username', type: 'text', placeholder: 'system', required: true },
      { name: 'password', label: 'Password', type: 'password', placeholder: '••••••••', required: true },
    ],
  },
  {
    id: 'mssql',
    name: 'Microsoft SQL Server',
    type: 'mssql',
    category: 'database',
    icon: '🪟',
    color: '#CC2927',
    description: 'Microsoft enterprise database system',
    testable: true,
    requiresAuth: true,
    fields: [
      { name: 'host', label: 'Host', type: 'text', placeholder: 'localhost', required: true },
      { name: 'port', label: 'Port', type: 'number', placeholder: '1433', required: true, defaultValue: 1433 },
      { name: 'database', label: 'Database', type: 'text', placeholder: 'master', required: true },
      { name: 'username', label: 'Username', type: 'text', placeholder: 'sa', required: true },
      { name: 'password', label: 'Password', type: 'password', placeholder: '••••••••', required: true },
    ],
  },
  {
    id: 'cockroachdb',
    name: 'CockroachDB',
    type: 'cockroachdb',
    category: 'database',
    icon: '🪳',
    color: '#6933FF',
    description: 'Distributed SQL database for cloud applications',
    testable: true,
    requiresAuth: true,
    fields: [
      { name: 'host', label: 'Host', type: 'text', placeholder: 'localhost', required: true },
      { name: 'port', label: 'Port', type: 'number', placeholder: '26257', required: true, defaultValue: 26257 },
      { name: 'database', label: 'Database', type: 'text', placeholder: 'defaultdb', required: true },
      { name: 'username', label: 'Username', type: 'text', placeholder: 'root', required: true },
      { name: 'password', label: 'Password', type: 'password', placeholder: '••••••••', required: false },
    ],
  },
  {
    id: 'snowflake',
    name: 'Snowflake',
    type: 'snowflake',
    category: 'database',
    icon: '❄️',
    color: '#29B5E8',
    description: 'Cloud data warehouse platform',
    testable: true,
    requiresAuth: true,
    fields: [
      { name: 'account', label: 'Account Identifier', type: 'text', placeholder: 'xy12345.us-east-1', required: true },
      { name: 'username', label: 'Username', type: 'text', placeholder: 'user@company.com', required: true },
      { name: 'password', label: 'Password', type: 'password', placeholder: '••••••••', required: true },
      { name: 'database', label: 'Database', type: 'text', placeholder: 'MYDB', required: true },
      { name: 'warehouse', label: 'Warehouse', type: 'text', placeholder: 'COMPUTE_WH', required: true },
      { name: 'schema', label: 'Schema', type: 'text', placeholder: 'PUBLIC', required: false },
    ],
  },
  {
    id: 'vertica',
    name: 'Vertica',
    type: 'vertica',
    category: 'database',
    icon: '🔷',
    color: '#005A9C',
    description: 'Columnar analytics database',
    testable: true,
    requiresAuth: true,
    fields: [
      { name: 'host', label: 'Host', type: 'text', placeholder: 'localhost', required: true },
      { name: 'port', label: 'Port', type: 'number', placeholder: '5433', required: true, defaultValue: 5433 },
      { name: 'database', label: 'Database', type: 'text', placeholder: 'vmart', required: true },
      { name: 'username', label: 'Username', type: 'text', placeholder: 'dbadmin', required: true },
      { name: 'password', label: 'Password', type: 'password', placeholder: '••••••••', required: true },
    ],
  },
];

// ========== NoSQL DATABASES (15) ==========
export const NOSQL_DB_CONFIGS: DataSourceConfig[] = [
  {
    id: 'mongodb',
    name: 'MongoDB',
    type: 'mongodb',
    category: 'database',
    icon: '🍃',
    color: '#47A248',
    description: 'Document-oriented NoSQL database',
    testable: true,
    requiresAuth: true,
    fields: [
      { name: 'connectionString', label: 'Connection String', type: 'text', placeholder: 'mongodb://localhost:27017', required: true },
      { name: 'database', label: 'Database', type: 'text', placeholder: 'mydb', required: true },
      { name: 'username', label: 'Username', type: 'text', placeholder: 'admin', required: false },
      { name: 'password', label: 'Password', type: 'password', placeholder: '••••••••', required: false },
    ],
  },
  {
    id: 'redis',
    name: 'Redis',
    type: 'redis',
    category: 'database',
    icon: '🔴',
    color: '#DC382D',
    description: 'In-memory data structure store',
    testable: true,
    requiresAuth: false,
    fields: [
      { name: 'host', label: 'Host', type: 'text', placeholder: 'localhost', required: true },
      { name: 'port', label: 'Port', type: 'number', placeholder: '6379', required: true, defaultValue: 6379 },
      { name: 'password', label: 'Password', type: 'password', placeholder: '••••••••', required: false },
      { name: 'database', label: 'Database Index', type: 'number', placeholder: '0', required: false, defaultValue: 0 },
    ],
  },
  {
    id: 'cassandra',
    name: 'Apache Cassandra',
    type: 'cassandra',
    category: 'database',
    icon: '🔸',
    color: '#1287B1',
    description: 'Distributed wide-column store',
    testable: true,
    requiresAuth: true,
    fields: [
      { name: 'contactPoints', label: 'Contact Points (comma-separated)', type: 'text', placeholder: 'localhost,node2', required: true },
      { name: 'port', label: 'Port', type: 'number', placeholder: '9042', required: true, defaultValue: 9042 },
      { name: 'keyspace', label: 'Keyspace', type: 'text', placeholder: 'mykeyspace', required: true },
      { name: 'username', label: 'Username', type: 'text', placeholder: 'cassandra', required: false },
      { name: 'password', label: 'Password', type: 'password', placeholder: '••••••••', required: false },
    ],
  },
  {
    id: 'couchdb',
    name: 'CouchDB',
    type: 'couchdb',
    category: 'database',
    icon: '🛋️',
    color: '#E42528',
    description: 'Document-oriented database with HTTP API',
    testable: true,
    requiresAuth: true,
    fields: [
      { name: 'url', label: 'URL', type: 'url', placeholder: 'http://localhost:5984', required: true },
      { name: 'username', label: 'Username', type: 'text', placeholder: 'admin', required: true },
      { name: 'password', label: 'Password', type: 'password', placeholder: '••••••••', required: true },
      { name: 'database', label: 'Database', type: 'text', placeholder: 'mydb', required: false },
    ],
  },
  {
    id: 'dynamodb',
    name: 'Amazon DynamoDB',
    type: 'dynamodb',
    category: 'database',
    icon: '',
    color: '#4053D6',
    description: 'AWS managed NoSQL database',
    testable: true,
    requiresAuth: true,
    fields: [
      { name: 'region', label: 'Region', type: 'text', placeholder: 'us-east-1', required: true },
      { name: 'accessKeyId', label: 'Access Key ID', type: 'text', placeholder: 'AKIAIOSFODNN7EXAMPLE', required: true },
      { name: 'secretAccessKey', label: 'Secret Access Key', type: 'password', placeholder: '••••••••', required: true },
      { name: 'endpoint', label: 'Custom Endpoint (optional)', type: 'url', placeholder: 'http://localhost:8000', required: false },
    ],
  },
  {
    id: 'neo4j',
    name: 'Neo4j',
    type: 'neo4j',
    category: 'database',
    icon: '🕸️',
    color: '#008CC1',
    description: 'Graph database management system',
    testable: true,
    requiresAuth: true,
    fields: [
      { name: 'uri', label: 'Connection URI', type: 'url', placeholder: 'bolt://localhost:7687', required: true },
      { name: 'username', label: 'Username', type: 'text', placeholder: 'neo4j', required: true },
      { name: 'password', label: 'Password', type: 'password', placeholder: '••••••••', required: true },
      { name: 'database', label: 'Database', type: 'text', placeholder: 'neo4j', required: false },
    ],
  },
  {
    id: 'arangodb',
    name: 'ArangoDB',
    type: 'arangodb',
    category: 'database',
    icon: '🥑',
    color: '#DDE016',
    description: 'Multi-model database (documents, graphs, key-value)',
    testable: true,
    requiresAuth: true,
    fields: [
      { name: 'url', label: 'URL', type: 'url', placeholder: 'http://localhost:8529', required: true },
      { name: 'database', label: 'Database', type: 'text', placeholder: '_system', required: true },
      { name: 'username', label: 'Username', type: 'text', placeholder: 'root', required: true },
      { name: 'password', label: 'Password', type: 'password', placeholder: '••••••••', required: true },
    ],
  },
  {
    id: 'memcached',
    name: 'Memcached',
    type: 'memcached',
    category: 'database',
    icon: '🧠',
    color: '#00D9FF',
    description: 'Distributed memory caching system',
    testable: true,
    requiresAuth: false,
    fields: [
      { name: 'servers', label: 'Servers (comma-separated)', type: 'text', placeholder: 'localhost:11211', required: true },
    ],
  },
  {
    id: 'rethinkdb',
    name: 'RethinkDB',
    type: 'rethinkdb',
    category: 'database',
    icon: '🔄',
    color: '#2E3A4F',
    description: 'Real-time database for modern apps',
    testable: true,
    requiresAuth: false,
    fields: [
      { name: 'host', label: 'Host', type: 'text', placeholder: 'localhost', required: true },
      { name: 'port', label: 'Port', type: 'number', placeholder: '28015', required: true, defaultValue: 28015 },
      { name: 'database', label: 'Database', type: 'text', placeholder: 'test', required: false },
      { name: 'username', label: 'Username', type: 'text', placeholder: 'admin', required: false },
      { name: 'password', label: 'Password', type: 'password', placeholder: '••••••••', required: false },
    ],
  },
  {
    id: 'firestore',
    name: 'Google Firestore',
    type: 'firestore',
    category: 'database',
    icon: '🔥',
    color: '#FFA000',
    description: 'Cloud-hosted NoSQL database from Firebase',
    testable: true,
    requiresAuth: true,
    fields: [
      { name: 'projectId', label: 'Project ID', type: 'text', placeholder: 'my-project', required: true },
      { name: 'credentials', label: 'Service Account JSON', type: 'textarea', placeholder: 'Paste JSON credentials', required: true },
    ],
  },
  {
    id: 'hbase',
    name: 'Apache HBase',
    type: 'hbase',
    category: 'database',
    icon: '🐝',
    color: '#FF6600',
    description: 'Distributed column-oriented database on Hadoop',
    testable: true,
    requiresAuth: false,
    fields: [
      { name: 'zkQuorum', label: 'ZooKeeper Quorum', type: 'text', placeholder: 'localhost:2181', required: true },
      { name: 'zkNode', label: 'ZooKeeper ZNode', type: 'text', placeholder: '/hbase', required: false, defaultValue: '/hbase' },
    ],
  },
  {
    id: 'scylladb',
    name: 'ScyllaDB',
    type: 'scylladb',
    category: 'database',
    icon: '🦂',
    color: '#53CADD',
    description: 'High-performance Cassandra-compatible database',
    testable: true,
    requiresAuth: true,
    fields: [
      { name: 'contactPoints', label: 'Contact Points', type: 'text', placeholder: 'localhost', required: true },
      { name: 'port', label: 'Port', type: 'number', placeholder: '9042', required: true, defaultValue: 9042 },
      { name: 'keyspace', label: 'Keyspace', type: 'text', placeholder: 'mykeyspace', required: true },
      { name: 'username', label: 'Username', type: 'text', placeholder: 'cassandra', required: false },
      { name: 'password', label: 'Password', type: 'password', placeholder: '••••••••', required: false },
    ],
  },
  {
    id: 'orientdb',
    name: 'OrientDB',
    type: 'orientdb',
    category: 'database',
    icon: '🌐',
    color: '#F58025',
    description: 'Multi-model database (graph, document, key-value)',
    testable: true,
    requiresAuth: true,
    fields: [
      { name: 'host', label: 'Host', type: 'text', placeholder: 'localhost', required: true },
      { name: 'port', label: 'Port', type: 'number', placeholder: '2424', required: true, defaultValue: 2424 },
      { name: 'database', label: 'Database', type: 'text', placeholder: 'demodb', required: true },
      { name: 'username', label: 'Username', type: 'text', placeholder: 'root', required: true },
      { name: 'password', label: 'Password', type: 'password', placeholder: '••••••••', required: true },
    ],
  },
  {
    id: 'cosmosdb',
    name: 'Azure Cosmos DB',
    type: 'cosmosdb',
    category: 'database',
    icon: '🌍',
    color: '#0078D4',
    description: 'Globally distributed multi-model database',
    testable: true,
    requiresAuth: true,
    fields: [
      { name: 'endpoint', label: 'Endpoint', type: 'url', placeholder: 'https://account.documents.azure.com:443/', required: true },
      { name: 'key', label: 'Primary Key', type: 'password', placeholder: '••••••••', required: true },
      { name: 'database', label: 'Database ID', type: 'text', placeholder: 'ToDoList', required: false },
    ],
  },
  {
    id: 'etcd',
    name: 'etcd',
    type: 'etcd',
    category: 'database',
    icon: '🔐',
    color: '#419EDA',
    description: 'Distributed key-value store for configuration',
    testable: true,
    requiresAuth: false,
    fields: [
      { name: 'hosts', label: 'Hosts (comma-separated)', type: 'text', placeholder: 'localhost:2379', required: true },
      { name: 'username', label: 'Username', type: 'text', placeholder: 'root', required: false },
      { name: 'password', label: 'Password', type: 'password', placeholder: '••••••••', required: false },
    ],
  },
];

// ========== TIME SERIES DATABASES (8) ==========
export const TIMESERIES_DB_CONFIGS: DataSourceConfig[] = [
  {
    id: 'influxdb',
    name: 'InfluxDB',
    type: 'influxdb',
    category: 'timeseries',
    icon: '',
    color: '#22ADF6',
    description: 'Time series database for metrics and events',
    testable: true,
    requiresAuth: true,
    fields: [
      { name: 'url', label: 'URL', type: 'url', placeholder: 'http://localhost:8086', required: true },
      { name: 'token', label: 'Token', type: 'password', placeholder: 'your-token', required: true },
      { name: 'organization', label: 'Organization', type: 'text', placeholder: 'my-org', required: true },
      { name: 'bucket', label: 'Bucket', type: 'text', placeholder: 'my-bucket', required: true },
    ],
  },
  {
    id: 'questdb',
    name: 'QuestDB',
    type: 'questdb',
    category: 'timeseries',
    icon: '',
    color: '#FF9D00',
    description: 'High-performance time series database',
    testable: true,
    requiresAuth: false,
    fields: [
      { name: 'host', label: 'Host', type: 'text', placeholder: 'localhost', required: true },
      { name: 'port', label: 'HTTP Port', type: 'number', placeholder: '9000', required: true, defaultValue: 9000 },
      { name: 'username', label: 'Username', type: 'text', placeholder: 'admin', required: false },
      { name: 'password', label: 'Password', type: 'password', placeholder: '••••••••', required: false },
    ],
  },
  {
    id: 'timescaledb',
    name: 'TimescaleDB',
    type: 'timescaledb',
    category: 'timeseries',
    icon: '',
    color: '#FDB515',
    description: 'PostgreSQL extension for time series',
    testable: true,
    requiresAuth: true,
    fields: [
      { name: 'host', label: 'Host', type: 'text', placeholder: 'localhost', required: true },
      { name: 'port', label: 'Port', type: 'number', placeholder: '5432', required: true, defaultValue: 5432 },
      { name: 'database', label: 'Database', type: 'text', placeholder: 'tsdb', required: true },
      { name: 'username', label: 'Username', type: 'text', placeholder: 'postgres', required: true },
      { name: 'password', label: 'Password', type: 'password', placeholder: '••••••••', required: true },
    ],
  },
  {
    id: 'prometheus',
    name: 'Prometheus',
    type: 'prometheus',
    category: 'timeseries',
    icon: '🔥',
    color: '#E6522C',
    description: 'Monitoring system and time series database',
    testable: true,
    requiresAuth: false,
    fields: [
      { name: 'url', label: 'URL', type: 'url', placeholder: 'http://localhost:9090', required: true },
      { name: 'username', label: 'Username', type: 'text', placeholder: '', required: false },
      { name: 'password', label: 'Password', type: 'password', placeholder: '••••••••', required: false },
    ],
  },
  {
    id: 'victoriametrics',
    name: 'VictoriaMetrics',
    type: 'victoriametrics',
    category: 'timeseries',
    icon: '📊',
    color: '#621CEA',
    description: 'Fast and cost-effective time series database',
    testable: true,
    requiresAuth: false,
    fields: [
      { name: 'url', label: 'URL', type: 'url', placeholder: 'http://localhost:8428', required: true },
    ],
  },
  {
    id: 'opentsdb',
    name: 'OpenTSDB',
    type: 'opentsdb',
    category: 'timeseries',
    icon: '📈',
    color: '#44B4E5',
    description: 'Distributed time series database on HBase',
    testable: true,
    requiresAuth: false,
    fields: [
      { name: 'url', label: 'URL', type: 'url', placeholder: 'http://localhost:4242', required: true },
    ],
  },
  {
    id: 'kdb',
    name: 'kdb+',
    type: 'kdb',
    category: 'timeseries',
    icon: '🎯',
    color: '#0069B4',
    description: 'High-performance time series database for financial data',
    testable: true,
    requiresAuth: true,
    fields: [
      { name: 'host', label: 'Host', type: 'text', placeholder: 'localhost', required: true },
      { name: 'port', label: 'Port', type: 'number', placeholder: '5000', required: true, defaultValue: 5000 },
      { name: 'username', label: 'Username', type: 'text', placeholder: 'user', required: false },
      { name: 'password', label: 'Password', type: 'password', placeholder: '••••••••', required: false },
    ],
  },
  {
    id: 'clickhouse',
    name: 'ClickHouse',
    type: 'clickhouse',
    category: 'timeseries',
    icon: '',
    color: '#FFCC00',
    description: 'Fast open-source columnar database',
    testable: true,
    requiresAuth: true,
    fields: [
      { name: 'host', label: 'Host', type: 'text', placeholder: 'localhost', required: true },
      { name: 'port', label: 'HTTP Port', type: 'number', placeholder: '8123', required: true, defaultValue: 8123 },
      { name: 'database', label: 'Database', type: 'text', placeholder: 'default', required: true },
      { name: 'username', label: 'Username', type: 'text', placeholder: 'default', required: true },
      { name: 'password', label: 'Password', type: 'password', placeholder: '••••••••', required: false },
    ],
  },
];

// ========== FILE SOURCES (8) ==========
export const FILE_SOURCE_CONFIGS: DataSourceConfig[] = [
  {
    id: 'csv',
    name: 'CSV File',
    type: 'csv',
    category: 'file',
    icon: '📄',
    color: '#217346',
    description: 'Import data from CSV files',
    testable: false,
    requiresAuth: false,
    fields: [
      { name: 'filepath', label: 'File Path', type: 'text', placeholder: 'Select CSV file', required: true },
      { name: 'delimiter', label: 'Delimiter', type: 'select', required: false, defaultValue: ',', options: [
        { label: 'Comma (,)', value: ',' },
        { label: 'Semicolon (;)', value: ';' },
        { label: 'Tab', value: '\\t' },
        { label: 'Pipe (|)', value: '|' },
      ]},
      { name: 'hasHeader', label: 'Has Header Row', type: 'checkbox', required: false, defaultValue: true },
      { name: 'encoding', label: 'Encoding', type: 'select', required: false, defaultValue: 'utf-8', options: [
        { label: 'UTF-8', value: 'utf-8' },
        { label: 'ASCII', value: 'ascii' },
        { label: 'Latin-1', value: 'latin1' },
      ]},
    ],
  },
  {
    id: 'excel',
    name: 'Excel (XLSX)',
    type: 'excel',
    category: 'file',
    icon: '📊',
    color: '#217346',
    description: 'Import data from Excel files',
    testable: false,
    requiresAuth: false,
    fields: [
      { name: 'filepath', label: 'File Path', type: 'text', placeholder: 'Select Excel file', required: true },
      { name: 'sheet', label: 'Sheet Name or Index', type: 'text', placeholder: 'Sheet1 or 0', required: false },
      { name: 'hasHeader', label: 'Has Header Row', type: 'checkbox', required: false, defaultValue: true },
    ],
  },
  {
    id: 'json',
    name: 'JSON File',
    type: 'json',
    category: 'file',
    icon: '📋',
    color: '#F7DF1E',
    description: 'Import data from JSON files',
    testable: false,
    requiresAuth: false,
    fields: [
      { name: 'filepath', label: 'File Path', type: 'text', placeholder: 'Select JSON file', required: true },
      { name: 'jsonPath', label: 'JSON Path (optional)', type: 'text', placeholder: '$.data', required: false },
    ],
  },
  {
    id: 'parquet',
    name: 'Parquet File',
    type: 'parquet',
    category: 'file',
    icon: '📦',
    color: '#FF6B00',
    description: 'Import data from Apache Parquet files',
    testable: false,
    requiresAuth: false,
    fields: [
      { name: 'filepath', label: 'File Path', type: 'text', placeholder: 'Select Parquet file', required: true },
    ],
  },
  {
    id: 'xml',
    name: 'XML File',
    type: 'xml',
    category: 'file',
    icon: '📝',
    color: '#FF6600',
    description: 'Import data from XML files',
    testable: false,
    requiresAuth: false,
    fields: [
      { name: 'filepath', label: 'File Path', type: 'text', placeholder: 'Select XML file', required: true },
      { name: 'xpath', label: 'XPath Expression', type: 'text', placeholder: '//record', required: false },
    ],
  },
  {
    id: 'avro',
    name: 'Avro File',
    type: 'avro',
    category: 'file',
    icon: '🔷',
    color: '#0066CC',
    description: 'Import data from Apache Avro files',
    testable: false,
    requiresAuth: false,
    fields: [
      { name: 'filepath', label: 'File Path', type: 'text', placeholder: 'Select Avro file', required: true },
    ],
  },
  {
    id: 'orc',
    name: 'ORC File',
    type: 'orc',
    category: 'file',
    icon: '🟦',
    color: '#5B9BD5',
    description: 'Import data from Apache ORC files',
    testable: false,
    requiresAuth: false,
    fields: [
      { name: 'filepath', label: 'File Path', type: 'text', placeholder: 'Select ORC file', required: true },
    ],
  },
  {
    id: 'feather',
    name: 'Feather File',
    type: 'feather',
    category: 'file',
    icon: '🪶',
    color: '#FF4081',
    description: 'Import data from Apache Arrow Feather files',
    testable: false,
    requiresAuth: false,
    fields: [
      { name: 'filepath', label: 'File Path', type: 'text', placeholder: 'Select Feather file', required: true },
    ],
  },
];

// ========== FTP/SFTP (2) ==========
export const FTP_SOURCE_CONFIGS: DataSourceConfig[] = [
  {
    id: 'ftp',
    name: 'FTP',
    type: 'ftp',
    category: 'file',
    icon: '📁',
    color: '#0066CC',
    description: 'File Transfer Protocol',
    testable: true,
    requiresAuth: true,
    fields: [
      { name: 'host', label: 'Host', type: 'text', placeholder: 'ftp.example.com', required: true },
      { name: 'port', label: 'Port', type: 'number', placeholder: '21', required: true, defaultValue: 21 },
      { name: 'username', label: 'Username', type: 'text', placeholder: 'user', required: true },
      { name: 'password', label: 'Password', type: 'password', placeholder: '••••••••', required: true },
    ],
  },
  {
    id: 'sftp',
    name: 'SFTP',
    type: 'sftp',
    category: 'file',
    icon: '🔒',
    color: '#00CC66',
    description: 'Secure File Transfer Protocol',
    testable: true,
    requiresAuth: true,
    fields: [
      { name: 'host', label: 'Host', type: 'text', placeholder: 'sftp.example.com', required: true },
      { name: 'port', label: 'Port', type: 'number', placeholder: '22', required: true, defaultValue: 22 },
      { name: 'username', label: 'Username', type: 'text', placeholder: 'user', required: true },
      { name: 'password', label: 'Password', type: 'password', placeholder: '••••••••', required: false },
      { name: 'privateKey', label: 'Private Key Path', type: 'text', placeholder: '/path/to/key', required: false },
    ],
  },
];

export const DATABASE_SOURCE_CONFIGS: DataSourceConfig[] = [
  ...RELATIONAL_DB_CONFIGS,
  ...NOSQL_DB_CONFIGS,
  ...TIMESERIES_DB_CONFIGS,
  ...FILE_SOURCE_CONFIGS,
  ...FTP_SOURCE_CONFIGS,
];
