# ==============================================================================
# Strategy: My Strategy
# Version: 1.0.0
# Author: User
# Description: User-created strategy
# Generated by Fincept Terminal
# ==============================================================================

# Simple Moving Average Crossover Strategy
# This is a basic example - modify as needed

from AlgorithmImports import *

class MyStrategy(QCAlgorithm):
    def Initialize(self):
        self.SetStartDate(2020, 1, 1)
        self.SetEndDate(2023, 12, 31)
        self.SetCash(100000)

        # Add equity
        self.symbol = self.AddEquity("SPY", Resolution.Daily).Symbol

        # Create indicators
        self.fast_sma = self.SMA(self.symbol, 50, Resolution.Daily)
        self.slow_sma = self.SMA(self.symbol, 200, Resolution.Daily)

    def OnData(self, data):
        if not self.fast_sma.IsReady or not self.slow_sma.IsReady:
            return

        # Buy signal: fast SMA crosses above slow SMA
        if self.fast_sma.Current.Value > self.slow_sma.Current.Value:
            if not self.Portfolio.Invested:
                self.SetHoldings(self.symbol, 1.0)

        # Sell signal: fast SMA crosses below slow SMA
        elif self.fast_sma.Current.Value < self.slow_sma.Current.Value:
            if self.Portfolio.Invested:
                self.Liquidate(self.symbol)
