ASSETS = {
    "Stock Indices": {
        "S&P 500": "^GSPC",
        "Nasdaq 100": "^NDX",
        "Dow Jones": "^DJI",
        "Russell 2000": "^RUT",
        "VIX (Volatility Index)": "^VIX",
        "FTSE 100 (UK)": "^FTSE",
        "DAX 40 (Germany)": "^GDAXI",
        "CAC 40 (France)": "^FCHI",
        "Nikkei 225 (Japan)": "^N225",
        "Hang Seng (Hong Kong)": "^HSI",
        "Shanghai Composite (China)": "000001.SS",
        "Sensex 30 (India)": "^BSESN",
        "Nifty 50 (India)": "^NSEI",
        "ASX 200 (Australia)": "^AXJO",
        "Euro Stoxx 50 (EU)": "^STOXX50E",
        "MSCI Emerging Markets": "EEM",
        "Brazil Bovespa": "^BVSP",
        "Mexico IPC": "^MXX",
        "South Korea KOSPI": "^KS11",
        "Taiwan TAIEX": "^TWII",
        "Singapore STI": "^STI",
    },
    "Forex": {
        "EUR/USD": "EURUSD=X",
        "GBP/USD": "GBPUSD=X",
        "USD/JPY": "USDJPY=X",
        "USD/CHF": "USDCHF=X",
        "USD/CAD": "USDCAD=X",
        "AUD/USD": "AUDUSD=X",
        "NZD/USD": "NZDUSD=X",
        "EUR/GBP": "EURGBP=X",
        "EUR/JPY": "EURJPY=X",
        "GBP/JPY": "GBPJPY=X",
        "CHF/JPY": "CHFJPY=X",
        "AUD/JPY": "AUDJPY=X",
        "NZD/JPY": "NZDJPY=X",
        "EUR/CHF": "EURCHF=X",
        "USD/CNY": "USDCNY=X",
        "USD/INR": "USDINR=X",
        "USD/SGD": "USDSGD=X",
        "USD/KRW": "USDKRW=X",
        "USD/HKD": "USDHKD=X",
        "USD/IDR": "USDIDR=X",
        "USD/THB": "USDTHB=X",
        "USD/MXN": "USDMXN=X",
        "USD/BRL": "USDBRL=X",
        "USD/ZAR": "USDZAR=X",
        "USD/RUB": "USDRUB=X",
        "EUR/AUD": "EURAUD=X",
        "EUR/CAD": "EURCAD=X",
        "GBP/AUD": "GBPAUD=X",
        "GBP/CAD": "GBPCAD=X",
        "AUD/CAD": "AUDCAD=X",
        "AUD/NZD": "AUDNZD=X",
        "CAD/JPY": "CADJPY=X",
        "SGD/JPY": "SGDJPY=X",
        "HKD/JPY": "HKDJPY=X",
    },
    "Commodities": {
        "Gold": "GC=F",
        "Silver": "SI=F",
        "Crude Oil (WTI)": "CL=F",
        "Brent Crude Oil": "BZ=F",
        "Natural Gas": "NG=F",
        "Copper": "HG=F",
        "Platinum": "PL=F",
        "Palladium": "PA=F",
        "Wheat": "ZW=F",
        "Corn": "ZC=F",
        "Soybeans": "ZS=F",
        "Coffee": "KC=F",
        "Cocoa": "CC=F",
        "Sugar": "SB=F",
        "Cotton": "CT=F",
        "Aluminum": "ALI=F",
        "Heating Oil": "HO=F",
        "Gasoline (RBOB)": "RB=F",
        "Live Cattle": "LE=F",
        "Lean Hogs": "HE=F",
        "Feeder Cattle": "GF=F",
        "Oats": "ZO=F",
        "Rice": "ZR=F",
        "Orange Juice": "OJ=F",
    },
    "Bonds": {
        "US 10Y Treasury": "^TNX",
        "US 30Y Treasury": "^TYX",
        "India 10Y Bond": "NIFTYGS10YR.NS",
        "Franklin Emerging Market Debt Opps": "FEMDX",
        "Motilal Oswal Nasdaq 100 Fd of Fd Reg Gr":"0P0001F0CL.BO",
        "FSITC GlobalAIRobotics and SmartAuto USD":"0P000184IC",
        "US Corporate Bonds (LQD)": "LQD",
        "US High Yield Bonds (HYG)": "HYG",
        "US Fed Funds Rate": "^IRX",
    },
    "ETFs": {
        "S&P 500 ETF (SPY)": "SPY",
        "Nasdaq 100 ETF (QQQ)": "QQQ",
        "Dow Jones ETF (DIA)": "DIA",
        "Emerging Markets ETF (EEM)": "EEM",
        "Gold ETF (GLD)": "GLD",
        "Technology ETF (XLK)": "XLK",
        "Energy ETF (XLE)": "XLE",
        "Financials ETF (XLF)": "XLF",
        "Healthcare ETF (XLV)": "XLV",
        "Real Estate ETF (VNQ)": "VNQ",
        "AI & Robotics ETF (BOTZ)": "BOTZ",
        "Clean Energy ETF (ICLN)": "ICLN",
        "EV & Battery ETF (LIT)": "LIT",
        "Cybersecurity ETF (HACK)": "HACK",
    },
    "Cryptocurrencies": {
        "Bitcoin": "BTC-USD",
        "Ethereum": "ETH-USD",
        "Binance Coin": "BNB-USD",
        "Solana": "SOL-USD",
        "XRP": "XRP-USD",
        "Dogecoin": "DOGE-USD",
        "Polygon (MATIC)": "MATIC-USD",
        "Chainlink": "LINK-USD",
        "Cardano": "ADA-USD",
        "Polkadot": "DOT-USD",
        "Avalanche": "AVAX-USD",
        "Litecoin": "LTC-USD",
        "Cosmos": "ATOM-USD",
        "Shiba Inu": "SHIB-USD",
        "Uniswap": "UNI-USD",
        "Algorand": "ALGO-USD",
        "Stellar": "XLM-USD",
        "Filecoin": "FIL-USD",
        "Aave": "AAVE-USD",
        "VeChain": "VET-USD",
        "Elrond": "EGLD-USD",
        "Decentraland": "MANA-USD",
        "Sandbox": "SAND-USD",
        "Axie Infinity": "AXS-USD",
        "ThorChain": "RUNE-USD",
        "Internet Computer": "ICP-USD",
        "Stacks": "STX-USD",
        "Arbitrum": "ARB-USD",
        "Optimism": "OP-USD",
        "Injective Protocol": "INJ-USD",
        "Rocket Pool": "RPL-USD",
    },
}


