// Alternative Data connectors (8): RavenPack, Bloomberg Second Measure, SafeGraph, Orbital Insight,
// Refinitiv Tick History, Earnest Research, Thinknum, Revelio Labs
#include "screens/data_sources/ConnectorRegistry.h"

namespace fincept::screens::datasources {

static QVector<ConnectorConfig> alt_data_configs() {
    return {
        {"ravenpack",
         "RavenPack",
         "ravenpack",
         Category::AlternativeData,
         "R",
         "#1A3A5C",
         "NLP-powered news sentiment analytics. Industry standard for quant funds — structured sentiment scores from 900k+ news sources.",
         true,
         true,
         {{"apiKey", "API Key", FieldType::Password, "your-api-key", true, "", {}},
          {"dataset",
           "Dataset",
           FieldType::Select,
           "",
           false,
           "full",
           {{"Full (all sources)", "full"}, {"Newswire", "newswire"}, {"Web", "web"}, {"Premium", "premium"}}},
          {"universe", "Entity Universe (e.g. S&P 500)", FieldType::Text, "", false, "", {}}}},

        {"bloomberg-second-measure",
         "Bloomberg Second Measure",
         "bloomberg-second-measure",
         Category::AlternativeData,
         "B",
         "#000000",
         "Credit and debit card transaction data from 4M+ anonymized consumers. Used for earnings pre-announcement alpha signals.",
         true,
         true,
         {{"apiKey", "API Key", FieldType::Password, "your-api-key", true, "", {}},
          {"company", "Company / Ticker", FieldType::Text, "AMZN", false, "", {}}}},

        {"safegraph",
         "SafeGraph / Placer.ai",
         "safegraph",
         Category::AlternativeData,
         "S",
         "#00BCD4",
         "Geolocation and foot traffic data from 30M+ devices. Used to predict retail revenue, track store visits, and measure real estate demand.",
         true,
         true,
         {{"apiKey", "API Key", FieldType::Password, "your-api-key", true, "", {}},
          {"placeId", "Place ID / PLACEKEY", FieldType::Text, "", false, "", {}},
          {"startDate", "Start Date (YYYY-MM-DD)", FieldType::Text, "", false, "", {}},
          {"endDate", "End Date (YYYY-MM-DD)", FieldType::Text, "", false, "", {}}}},

        {"orbital-insight",
         "Orbital Insight",
         "orbital-insight",
         Category::AlternativeData,
         "O",
         "#1B2A4A",
         "Satellite imagery analytics API. Tracks crude oil storage, parking lot occupancy, construction activity, and commodity stockpiles from space.",
         true,
         true,
         {{"apiKey", "API Key", FieldType::Password, "your-api-key", true, "", {}},
          {"dataset",
           "Dataset",
           FieldType::Select,
           "",
           false,
           "oil",
           {{"Crude Oil Storage", "oil"}, {"Retail Foot Traffic", "retail"}, {"Construction", "construction"}, {"Agriculture", "agriculture"}}}}},

        {"refinitiv-tick-history",
         "Refinitiv Tick History",
         "refinitiv-tick-history",
         Category::AlternativeData,
         "R",
         "#FF6200",
         "LSEG historical tick-by-tick data for equities, FX, futures, and options. Millisecond-precision trade and quote data across 450+ venues.",
         true,
         true,
         {{"appKey", "App Key", FieldType::Password, "your-app-key", true, "", {}},
          {"username", "Username", FieldType::Text, "user@firm.com", false, "", {}},
          {"password", "Password", FieldType::Password, "", false, "", {}},
          {"ric", "Default RIC", FieldType::Text, "AAPL.O", false, "", {}},
          {"fields", "Fields (comma-separated)", FieldType::Text, "Trade Price,Trade Volume,Bid Price,Ask Price", false, "", {}}}},

        {"earnest-research",
         "Earnest Research",
         "earnest-research",
         Category::AlternativeData,
         "E",
         "#2E7D32",
         "Consumer spending intelligence from anonymized credit/debit card transactions. Covers 15M+ consumers across US retail, travel, and services.",
         true,
         true,
         {{"apiKey", "API Key", FieldType::Password, "your-api-key", true, "", {}},
          {"metric",
           "Metric",
           FieldType::Select,
           "",
           false,
           "sales",
           {{"Sales Index", "sales"}, {"Transaction Count", "transactions"}, {"Basket Size", "basket"}, {"Customer Count", "customers"}}}}},

        {"thinknum",
         "Thinknum Alternative Data",
         "thinknum",
         Category::AlternativeData,
         "T",
         "#F5A623",
         "Web-scraped alternative data: job postings, product listings, app store ratings, employee reviews, and web traffic. Updated daily.",
         true,
         true,
         {{"apiKey", "API Key", FieldType::Password, "your-api-key", true, "", {}},
          {"dataset",
           "Dataset",
           FieldType::Select,
           "",
           false,
           "job_listings",
           {{"Job Listings", "job_listings"}, {"Product Prices", "product_prices"}, {"App Ratings", "app_ratings"}, {"Employee Reviews", "employee_reviews"}, {"Web Traffic", "web_traffic"}}},
          {"ticker", "Ticker / Company", FieldType::Text, "AMZN", false, "", {}}}},

        {"revelio-labs",
         "Revelio Labs",
         "revelio-labs",
         Category::AlternativeData,
         "R",
         "#6A0DAD",
         "Workforce intelligence and employment data. Tracks hiring trends, skill demand, attrition rates, and org structure changes from public job data.",
         true,
         true,
         {{"apiKey", "API Key", FieldType::Password, "your-api-key", true, "", {}},
          {"company", "Company / Ticker", FieldType::Text, "MSFT", false, "", {}},
          {"metric",
           "Metric",
           FieldType::Select,
           "",
           false,
           "headcount",
           {{"Headcount", "headcount"}, {"Hiring Rate", "hiring"}, {"Attrition Rate", "attrition"}, {"Skill Demand", "skills"}}}}},
    };
}

static bool registered = [] {
    for (auto& c : alt_data_configs())
        ConnectorRegistry::instance().add(std::move(c));
    return true;
}();

} // namespace fincept::screens::datasources
