// API & Streaming connectors (10): REST API, GraphQL, WebSocket, gRPC, SOAP, OData, MQTT, Kafka, RabbitMQ, NATS
#include "screens/data_sources/ConnectorRegistry.h"

namespace fincept::screens::datasources {

static QVector<ConnectorConfig> api_configs() {
    return {
        {"rest-api",
         "REST API",
         "rest-api",
         Category::Api,
         "R",
         "#61DAFB",
         "Connect to REST API endpoints",
         true,
         false,
         {{"baseUrl", "Base URL", FieldType::Url, "https://api.example.com", true, "", {}},
          {"authType",
           "Authentication Type",
           FieldType::Select,
           "",
           false,
           "none",
           {{"None", "none"}, {"API Key", "apikey"}, {"Bearer Token", "bearer"}, {"Basic Auth", "basic"}}},
          {"apiKey", "API Key / Token", FieldType::Password, "your-api-key", false, "", {}},
          {"headers", "Custom Headers (JSON)", FieldType::Textarea, "{\"X-Custom\": \"value\"}", false, "", {}}}},

        {"graphql",
         "GraphQL API",
         "graphql",
         Category::Api,
         "G",
         "#E10098",
         "Connect to GraphQL endpoints",
         true,
         false,
         {{"endpoint", "GraphQL Endpoint", FieldType::Url, "https://api.example.com/graphql", true, "", {}},
          {"authToken", "Auth Token", FieldType::Password, "Bearer token", false, "", {}},
          {"headers", "Custom Headers (JSON)", FieldType::Textarea, "", false, "", {}}}},

        {"websocket",
         "WebSocket",
         "websocket",
         Category::Streaming,
         "W",
         "#00A8E8",
         "Connect to WebSocket streams",
         true,
         false,
         {{"url", "WebSocket URL", FieldType::Url, "wss://stream.example.com", true, "", {}},
          {"protocols", "Protocols (comma-separated)", FieldType::Text, "", false, "", {}},
          {"reconnect", "Auto Reconnect", FieldType::Checkbox, "", false, "true", {}}}},

        {"grpc",
         "gRPC",
         "grpc",
         Category::Api,
         "G",
         "#00ADD8",
         "Connect to gRPC services",
         true,
         false,
         {{"host", "Host", FieldType::Text, "localhost", true, "", {}},
          {"port", "Port", FieldType::Number, "50051", true, "50051", {}},
          {"tls", "Use TLS", FieldType::Checkbox, "", false, "false", {}},
          {"protoFile", "Proto File Path", FieldType::Text, "/path/to/service.proto", false, "", {}}}},

        {"soap",
         "SOAP API",
         "soap",
         Category::Api,
         "S",
         "#0080FF",
         "Connect to SOAP web services",
         true,
         false,
         {{"wsdlUrl", "WSDL URL", FieldType::Url, "https://api.example.com/service?wsdl", true, "", {}},
          {"username", "Username", FieldType::Text, "user", false, "", {}},
          {"password", "Password", FieldType::Password, "", false, "", {}}}},

        {"odata",
         "OData API",
         "odata",
         Category::Api,
         "O",
         "#0078D4",
         "Connect to OData services",
         true,
         false,
         {{"serviceRoot", "Service Root URL", FieldType::Url, "https://api.example.com/odata", true, "", {}},
          {"authType",
           "Authentication",
           FieldType::Select,
           "",
           false,
           "none",
           {{"None", "none"}, {"Basic", "basic"}, {"OAuth2", "oauth2"}}},
          {"username", "Username", FieldType::Text, "user", false, "", {}},
          {"password", "Password", FieldType::Password, "", false, "", {}}}},

        {"mqtt",
         "MQTT",
         "mqtt",
         Category::Streaming,
         "M",
         "#660066",
         "Connect to MQTT broker for IoT data",
         true,
         false,
         {{"broker", "Broker URL", FieldType::Url, "mqtt://broker.example.com", true, "", {}},
          {"port", "Port", FieldType::Number, "1883", true, "1883", {}},
          {"clientId", "Client ID", FieldType::Text, "mqtt_client_123", false, "", {}},
          {"username", "Username", FieldType::Text, "user", false, "", {}},
          {"password", "Password", FieldType::Password, "", false, "", {}},
          {"topic", "Default Topic", FieldType::Text, "sensors/#", false, "", {}}}},

        {"kafka",
         "Apache Kafka",
         "kafka",
         Category::Streaming,
         "K",
         "#231F20",
         "Connect to Kafka streaming platform",
         true,
         false,
         {{"brokers", "Bootstrap Servers (comma-separated)", FieldType::Text, "localhost:9092", true, "", {}},
          {"groupId", "Consumer Group ID", FieldType::Text, "my-group", false, "", {}},
          {"topic", "Default Topic", FieldType::Text, "my-topic", false, "", {}},
          {"sasl", "Use SASL Authentication", FieldType::Checkbox, "", false, "false", {}},
          {"username", "SASL Username", FieldType::Text, "user", false, "", {}},
          {"password", "SASL Password", FieldType::Password, "", false, "", {}}}},

        {"rabbitmq",
         "RabbitMQ",
         "rabbitmq",
         Category::Streaming,
         "R",
         "#FF6600",
         "Connect to RabbitMQ message broker",
         true,
         true,
         {{"host", "Host", FieldType::Text, "localhost", true, "", {}},
          {"port", "Port", FieldType::Number, "5672", true, "5672", {}},
          {"username", "Username", FieldType::Text, "guest", true, "", {}},
          {"password", "Password", FieldType::Password, "", true, "", {}},
          {"vhost", "Virtual Host", FieldType::Text, "/", false, "/", {}}}},

        {"nats",
         "NATS",
         "nats",
         Category::Streaming,
         "N",
         "#375C93",
         "Connect to NATS messaging system",
         true,
         false,
         {{"servers", "Server URLs (comma-separated)", FieldType::Text, "nats://localhost:4222", true, "", {}},
          {"username", "Username", FieldType::Text, "user", false, "", {}},
          {"password", "Password", FieldType::Password, "", false, "", {}},
          {"token", "Token", FieldType::Password, "auth-token", false, "", {}}}},

        {"redpanda",
         "Redpanda",
         "redpanda",
         Category::Streaming,
         "R",
         "#E3342F",
         "Kafka-compatible streaming platform written in C++. 3-10x lower latency than Kafka, no JVM. Growing standard "
         "in HFT and fintech.",
         true,
         false,
         {{"brokers", "Bootstrap Servers (comma-separated)", FieldType::Text, "localhost:9092", true, "", {}},
          {"groupId", "Consumer Group ID", FieldType::Text, "my-group", false, "", {}},
          {"topic", "Default Topic", FieldType::Text, "market-ticks", false, "", {}},
          {"tls", "Use TLS", FieldType::Checkbox, "", false, "false", {}},
          {"username", "SASL Username", FieldType::Text, "user", false, "", {}},
          {"password", "SASL Password", FieldType::Password, "", false, "", {}}}},

        {"apache-flink",
         "Apache Flink",
         "apache-flink",
         Category::Streaming,
         "F",
         "#E6522C",
         "Stateful stream processing engine. 2025 standard for real-time P&L calculation, market surveillance, and "
         "fraud detection pipelines on top of Kafka.",
         true,
         false,
         {{"jobManagerUrl", "Job Manager URL", FieldType::Url, "http://localhost:8081", true, "", {}},
          {"parallelism", "Default Parallelism", FieldType::Number, "1", false, "1", {}},
          {"checkpointInterval", "Checkpoint Interval (ms)", FieldType::Number, "60000", false, "60000", {}}}},

        {"fix-protocol",
         "FIX Protocol",
         "fix-protocol",
         Category::Streaming,
         "F",
         "#1A1A2E",
         "Financial Information eXchange protocol — industry standard for order management and market data delivery "
         "(FAST/FIX FAST).",
         true,
         true,
         {{"host", "Counterparty Host", FieldType::Text, "fix.broker.com", true, "", {}},
          {"port", "Port", FieldType::Number, "9878", true, "9878", {}},
          {"senderCompId", "SenderCompID", FieldType::Text, "CLIENT", true, "", {}},
          {"targetCompId", "TargetCompID", FieldType::Text, "BROKER", true, "", {}},
          {"username", "Username", FieldType::Text, "user", false, "", {}},
          {"password", "Password", FieldType::Password, "", false, "", {}},
          {"fixVersion",
           "FIX Version",
           FieldType::Select,
           "",
           false,
           "FIX.4.4",
           {{"FIX 4.2", "FIX.4.2"}, {"FIX 4.4", "FIX.4.4"}, {"FIX 5.0", "FIX.5.0"}, {"FIXT 1.1", "FIXT.1.1"}}}}},
    };
}

static bool registered = [] {
    for (auto& c : api_configs())
        ConnectorRegistry::instance().add(std::move(c));
    return true;
}();

} // namespace fincept::screens::datasources
