// Market Data connectors (19): Yahoo Finance, Alpha Vantage, Finnhub, IEX Cloud, Twelve Data,
// Quandl, Binance, Coinbase, Kraken, CoinMarketCap, CoinGecko, EOD Historical, Tiingo,
// Intrinio, Fincept, Reuters, Marketstack, Finage, Tradier
#include "screens/data_sources/ConnectorRegistry.h"

namespace fincept::screens::datasources {

static QVector<ConnectorConfig> market_configs() {
    return {
        {"yahoo-finance",
         "Yahoo Finance",
         "yahoo-finance",
         Category::MarketData,
         "Y",
         "#7B0099",
         "Free stock market data from Yahoo Finance",
         true,
         false,
         {{"symbols", "Default Symbols (comma-separated)", FieldType::Text, "AAPL,GOOGL,MSFT", false, "", {}},
          {"interval",
           "Default Interval",
           FieldType::Select,
           "",
           false,
           "1d",
           {{"1 minute", "1m"},
            {"5 minutes", "5m"},
            {"15 minutes", "15m"},
            {"1 hour", "1h"},
            {"1 day", "1d"},
            {"1 week", "1wk"}}}}},

        {"alpha-vantage",
         "Alpha Vantage",
         "alpha-vantage",
         Category::MarketData,
         "A",
         "#2E7D32",
         "Stock, forex, and crypto market data API",
         true,
         true,
         {{"apiKey", "API Key", FieldType::Password, "your-api-key", true, "", {}}}},

        {"finnhub",
         "Finnhub",
         "finnhub",
         Category::MarketData,
         "F",
         "#00D4AA",
         "Real-time stock, forex, and crypto data",
         true,
         true,
         {{"apiKey", "API Key", FieldType::Password, "your-api-key", true, "", {}}}},

        {"iex-cloud",
         "IEX Cloud",
         "iex-cloud",
         Category::MarketData,
         "I",
         "#1D7DF0",
         "Financial data from IEX Exchange",
         true,
         true,
         {{"token", "API Token", FieldType::Password, "pk_...", true, "", {}},
          {"sandbox", "Use Sandbox", FieldType::Checkbox, "", false, "false", {}}}},

        {"twelve-data",
         "Twelve Data",
         "twelve-data",
         Category::MarketData,
         "T",
         "#00B4D8",
         "Real-time and historical financial data",
         true,
         true,
         {{"apiKey", "API Key", FieldType::Password, "your-api-key", true, "", {}}}},

        {"quandl",
         "Quandl/Nasdaq Data Link",
         "quandl",
         Category::MarketData,
         "Q",
         "#FF6B6B",
         "Financial and alternative datasets",
         true,
         true,
         {{"apiKey", "API Key", FieldType::Password, "your-api-key", true, "", {}}}},

        {"binance",
         "Binance",
         "binance",
         Category::MarketData,
         "B",
         "#F3BA2F",
         "Cryptocurrency exchange data",
         true,
         true,
         {{"apiKey", "API Key", FieldType::Password, "your-api-key", true, "", {}},
          {"apiSecret", "API Secret", FieldType::Password, "", true, "", {}},
          {"testnet", "Use Testnet", FieldType::Checkbox, "", false, "false", {}}}},

        {"coinbase",
         "Coinbase",
         "coinbase",
         Category::MarketData,
         "C",
         "#0052FF",
         "Cryptocurrency exchange data",
         true,
         true,
         {{"apiKey", "API Key", FieldType::Password, "your-api-key", true, "", {}},
          {"apiSecret", "API Secret", FieldType::Password, "", true, "", {}}}},

        {"kraken",
         "Kraken",
         "kraken",
         Category::MarketData,
         "K",
         "#5741D9",
         "Cryptocurrency exchange data",
         true,
         true,
         {{"apiKey", "API Key", FieldType::Password, "your-api-key", true, "", {}},
          {"privateKey", "Private Key", FieldType::Password, "", true, "", {}}}},

        {"coinmarketcap",
         "CoinMarketCap",
         "coinmarketcap",
         Category::MarketData,
         "C",
         "#17A2F5",
         "Cryptocurrency market data aggregator",
         true,
         true,
         {{"apiKey", "API Key", FieldType::Password, "your-api-key", true, "", {}}}},

        {"coingecko",
         "CoinGecko",
         "coingecko",
         Category::MarketData,
         "C",
         "#8DC63F",
         "Free cryptocurrency data API",
         true,
         false,
         {{"apiKey", "API Key (Pro only)", FieldType::Password, "your-api-key", false, "", {}}}},

        {"eod-historical",
         "EOD Historical Data",
         "eod-historical",
         Category::MarketData,
         "E",
         "#4A90E2",
         "Historical financial data API",
         true,
         true,
         {{"apiToken", "API Token", FieldType::Password, "your-api-token", true, "", {}}}},

        {"tiingo",
         "Tiingo",
         "tiingo",
         Category::MarketData,
         "T",
         "#FF4E50",
         "Stock, crypto, and news data",
         true,
         true,
         {{"apiToken", "API Token", FieldType::Password, "your-api-token", true, "", {}}}},

        {"intrinio",
         "Intrinio",
         "intrinio",
         Category::MarketData,
         "I",
         "#00B4D8",
         "Financial data for institutions",
         true,
         true,
         {{"apiKey", "API Key", FieldType::Password, "your-api-key", true, "", {}}}},

        {"fincept",
         "Fincept Data API",
         "fincept",
         Category::MarketData,
         "F",
         "#F58025",
         "Fincept Terminal Data API",
         true,
         true,
         {{"host", "Host", FieldType::Text, "localhost", true, "", {}},
          {"port", "Port", FieldType::Number, "8194", true, "8194", {}}}},

        {"reuters",
         "Refinitiv/Reuters",
         "reuters",
         Category::MarketData,
         "R",
         "#FF6200",
         "Refinitiv financial data API",
         true,
         true,
         {{"appKey", "App Key", FieldType::Password, "your-app-key", true, "", {}},
          {"username", "Username", FieldType::Text, "user@company.com", true, "", {}},
          {"password", "Password", FieldType::Password, "", true, "", {}}}},

        {"marketstack",
         "Marketstack",
         "marketstack",
         Category::MarketData,
         "M",
         "#4CAF50",
         "Real-time and historical stock data",
         true,
         true,
         {{"apiKey", "API Key", FieldType::Password, "your-api-key", true, "", {}},
          {"https", "Use HTTPS (paid plans)", FieldType::Checkbox, "", false, "false", {}}}},

        {"finage",
         "Finage",
         "finage",
         Category::MarketData,
         "F",
         "#00C853",
         "Real-time and historical market data",
         true,
         true,
         {{"apiKey", "API Key", FieldType::Password, "your-api-key", true, "", {}}}},

        {"tradier",
         "Tradier",
         "tradier",
         Category::MarketData,
         "T",
         "#00A8E8",
         "Brokerage and market data API",
         true,
         true,
         {{"accessToken", "Access Token", FieldType::Password, "your-access-token", true, "", {}},
          {"sandbox", "Use Sandbox", FieldType::Checkbox, "", false, "false", {}}}},

        {"polygon-io",
         "Polygon.io",
         "polygon-io",
         Category::MarketData,
         "P",
         "#6C48C5",
         "US equities, options, forex, and crypto tick data with WebSocket streaming. Free tier available.",
         true,
         true,
         {{"apiKey", "API Key", FieldType::Password, "your-api-key", true, "", {}},
          {"websocket", "Enable WebSocket Feed", FieldType::Checkbox, "", false, "false", {}}}},

        {"openfigi",
         "OpenFIGI",
         "openfigi",
         Category::MarketData,
         "O",
         "#0A3161",
         "Instrument identifier mapping: ISIN, CUSIP, SEDOL to FIGI/ticker across 70+ exchanges.",
         true,
         false,
         {{"apiKey", "API Key (optional, higher rate limits)", FieldType::Password, "", false, "", {}}}},

        {"factset",
         "FactSet",
         "factset",
         Category::MarketData,
         "F",
         "#003087",
         "Portfolio analytics, fundamentals, and machine-readable financial data (~180k professional users).",
         true,
         true,
         {{"username", "Username (username-serialnumber)", FieldType::Text, "user@firm-1234567", true, "", {}},
          {"apiKey", "API Key", FieldType::Password, "your-api-key", true, "", {}}}},

        {"refinitiv",
         "Refinitiv / LSEG Data Library",
         "refinitiv",
         Category::MarketData,
         "R",
         "#FF6200",
         "Machine-readable news, tick data, and FX from LSEG (~20% terminal market share). Supports Eikon and RDP APIs.",
         true,
         true,
         {{"appKey", "App Key", FieldType::Password, "your-app-key", true, "", {}},
          {"username", "RDP Username", FieldType::Text, "user@firm.com", false, "", {}},
          {"password", "RDP Password", FieldType::Password, "", false, "", {}}}},

        {"pitchbook",
         "PitchBook",
         "pitchbook",
         Category::MarketData,
         "P",
         "#0B3D91",
         "Private markets, VC/PE deal data, company financials, and fund performance (~100k users).",
         true,
         true,
         {{"apiKey", "API Key", FieldType::Password, "your-api-key", true, "", {}}}},

        {"nasdaq-totalview",
         "Nasdaq TotalView",
         "nasdaq-totalview",
         Category::MarketData,
         "N",
         "#0096D6",
         "Full Level 2 Nasdaq order book — all market participant quotes and orders, direct feed.",
         true,
         true,
         {{"username", "Username", FieldType::Text, "user", true, "", {}},
          {"password", "Password", FieldType::Password, "", true, "", {}},
          {"feed",
           "Feed Type",
           FieldType::Select,
           "",
           false,
           "totalview",
           {{"TotalView (full depth)", "totalview"}, {"Last Sale", "lastsale"}, {"Basic", "basic"}}}}},
    };
}

static bool registered = [] {
    for (auto& c : market_configs())
        ConnectorRegistry::instance().add(std::move(c));
    return true;
}();

} // namespace fincept::screens::datasources
