// NoSQL Database connectors (15): MongoDB, Redis, Cassandra, CouchDB, DynamoDB, Neo4j, ArangoDB,
// Memcached, RethinkDB, Firestore, HBase, ScyllaDB, OrientDB, CosmosDB, etcd
#include "screens/data_sources/ConnectorRegistry.h"

namespace fincept::screens::datasources {

static QVector<ConnectorConfig> nosql_configs() {
    return {
        {"mongodb",
         "MongoDB",
         "mongodb",
         Category::Database,
         "M",
         "#47A248",
         "Document-oriented NoSQL database",
         true,
         true,
         {{"connectionString", "Connection String", FieldType::Text, "mongodb://localhost:27017", true, "", {}},
          {"database", "Database", FieldType::Text, "mydb", true, "", {}},
          {"username", "Username", FieldType::Text, "admin", false, "", {}},
          {"password", "Password", FieldType::Password, "", false, "", {}}}},

        {"redis",
         "Redis",
         "redis",
         Category::Database,
         "R",
         "#DC382D",
         "In-memory data structure store",
         true,
         false,
         {{"host", "Host", FieldType::Text, "localhost", true, "", {}},
          {"port", "Port", FieldType::Number, "6379", true, "6379", {}},
          {"password", "Password", FieldType::Password, "", false, "", {}},
          {"database", "Database Index", FieldType::Number, "0", false, "0", {}}}},

        {"cassandra",
         "Apache Cassandra",
         "cassandra",
         Category::Database,
         "C",
         "#1287B1",
         "Distributed wide-column store",
         true,
         true,
         {{"contactPoints", "Contact Points (comma-separated)", FieldType::Text, "localhost", true, "", {}},
          {"port", "Port", FieldType::Number, "9042", true, "9042", {}},
          {"keyspace", "Keyspace", FieldType::Text, "mykeyspace", true, "", {}},
          {"username", "Username", FieldType::Text, "cassandra", false, "", {}},
          {"password", "Password", FieldType::Password, "", false, "", {}}}},

        {"couchdb",
         "CouchDB",
         "couchdb",
         Category::Database,
         "C",
         "#E42528",
         "Document-oriented database with HTTP API",
         true,
         true,
         {{"url", "URL", FieldType::Url, "http://localhost:5984", true, "", {}},
          {"username", "Username", FieldType::Text, "admin", true, "", {}},
          {"password", "Password", FieldType::Password, "", true, "", {}},
          {"database", "Database", FieldType::Text, "mydb", false, "", {}}}},

        {"dynamodb",
         "Amazon DynamoDB",
         "dynamodb",
         Category::Database,
         "D",
         "#4053D6",
         "AWS managed NoSQL database",
         true,
         true,
         {{"region", "Region", FieldType::Text, "us-east-1", true, "", {}},
          {"accessKeyId", "Access Key ID", FieldType::Text, "AKIAIOSFODNN7EXAMPLE", true, "", {}},
          {"secretAccessKey", "Secret Access Key", FieldType::Password, "", true, "", {}},
          {"endpoint", "Custom Endpoint", FieldType::Url, "http://localhost:8000", false, "", {}}}},

        {"neo4j",
         "Neo4j",
         "neo4j",
         Category::Database,
         "N",
         "#008CC1",
         "Graph database management system",
         true,
         true,
         {{"uri", "Connection URI", FieldType::Url, "bolt://localhost:7687", true, "", {}},
          {"username", "Username", FieldType::Text, "neo4j", true, "", {}},
          {"password", "Password", FieldType::Password, "", true, "", {}},
          {"database", "Database", FieldType::Text, "neo4j", false, "", {}}}},

        {"arangodb",
         "ArangoDB",
         "arangodb",
         Category::Database,
         "A",
         "#DDE016",
         "Multi-model database (documents, graphs, key-value)",
         true,
         true,
         {{"url", "URL", FieldType::Url, "http://localhost:8529", true, "", {}},
          {"database", "Database", FieldType::Text, "_system", true, "", {}},
          {"username", "Username", FieldType::Text, "root", true, "", {}},
          {"password", "Password", FieldType::Password, "", true, "", {}}}},

        {"memcached",
         "Memcached",
         "memcached",
         Category::Database,
         "M",
         "#00D9FF",
         "Distributed memory caching system",
         true,
         false,
         {{"servers", "Servers (comma-separated)", FieldType::Text, "localhost:11211", true, "", {}}}},

        {"rethinkdb",
         "RethinkDB",
         "rethinkdb",
         Category::Database,
         "R",
         "#2E3A4F",
         "Real-time database for modern apps",
         true,
         false,
         {{"host", "Host", FieldType::Text, "localhost", true, "", {}},
          {"port", "Port", FieldType::Number, "28015", true, "28015", {}},
          {"database", "Database", FieldType::Text, "test", false, "", {}},
          {"username", "Username", FieldType::Text, "admin", false, "", {}},
          {"password", "Password", FieldType::Password, "", false, "", {}}}},

        {"firestore",
         "Google Firestore",
         "firestore",
         Category::Database,
         "F",
         "#FFA000",
         "Cloud-hosted NoSQL database from Firebase",
         true,
         true,
         {{"projectId", "Project ID", FieldType::Text, "my-project", true, "", {}},
          {"credentials", "Service Account JSON", FieldType::Textarea, "Paste JSON credentials", true, "", {}}}},

        {"hbase",
         "Apache HBase",
         "hbase",
         Category::Database,
         "H",
         "#FF6600",
         "Distributed column-oriented database on Hadoop",
         true,
         false,
         {{"zkQuorum", "ZooKeeper Quorum", FieldType::Text, "localhost:2181", true, "", {}},
          {"zkNode", "ZooKeeper ZNode", FieldType::Text, "/hbase", false, "/hbase", {}}}},

        {"scylladb",
         "ScyllaDB",
         "scylladb",
         Category::Database,
         "S",
         "#53CADD",
         "High-performance Cassandra-compatible database",
         true,
         true,
         {{"contactPoints", "Contact Points", FieldType::Text, "localhost", true, "", {}},
          {"port", "Port", FieldType::Number, "9042", true, "9042", {}},
          {"keyspace", "Keyspace", FieldType::Text, "mykeyspace", true, "", {}},
          {"username", "Username", FieldType::Text, "cassandra", false, "", {}},
          {"password", "Password", FieldType::Password, "", false, "", {}}}},

        {"orientdb",
         "OrientDB",
         "orientdb",
         Category::Database,
         "O",
         "#F58025",
         "Multi-model database (graph, document, key-value)",
         true,
         true,
         {{"host", "Host", FieldType::Text, "localhost", true, "", {}},
          {"port", "Port", FieldType::Number, "2424", true, "2424", {}},
          {"database", "Database", FieldType::Text, "demodb", true, "", {}},
          {"username", "Username", FieldType::Text, "root", true, "", {}},
          {"password", "Password", FieldType::Password, "", true, "", {}}}},

        {"cosmosdb",
         "Azure Cosmos DB",
         "cosmosdb",
         Category::Database,
         "C",
         "#0078D4",
         "Globally distributed multi-model database",
         true,
         true,
         {{"endpoint", "Endpoint", FieldType::Url, "https://account.documents.azure.com:443/", true, "", {}},
          {"key", "Primary Key", FieldType::Password, "", true, "", {}},
          {"database", "Database ID", FieldType::Text, "ToDoList", false, "", {}}}},

        {"etcd",
         "etcd",
         "etcd",
         Category::Database,
         "E",
         "#419EDA",
         "Distributed key-value store for configuration",
         true,
         false,
         {{"hosts", "Hosts (comma-separated)", FieldType::Text, "localhost:2379", true, "", {}},
          {"username", "Username", FieldType::Text, "root", false, "", {}},
          {"password", "Password", FieldType::Password, "", false, "", {}}}},
    };
}

static bool registered = [] {
    for (auto& c : nosql_configs())
        ConnectorRegistry::instance().add(std::move(c));
    return true;
}();

} // namespace fincept::screens::datasources
