// Open Banking connectors (5): Plaid, MX, Finicity, TrueLayer, FDX API
#include "screens/data_sources/ConnectorRegistry.h"

namespace fincept::screens::datasources {

static QVector<ConnectorConfig> open_banking_configs() {
    return {
        {"plaid",
         "Plaid",
         "plaid",
         Category::OpenBanking,
         "P",
         "#00CF00",
         "Account aggregation for 11,000+ financial institutions. The dominant open banking aggregator in North America. Used in wealth management and PFM apps.",
         true,
         true,
         {{"clientId", "Client ID", FieldType::Text, "your-client-id", true, "", {}},
          {"secret", "Secret", FieldType::Password, "your-secret", true, "", {}},
          {"environment",
           "Environment",
           FieldType::Select,
           "",
           false,
           "sandbox",
           {{"Sandbox", "sandbox"}, {"Development", "development"}, {"Production", "production"}}},
          {"products",
           "Products",
           FieldType::Select,
           "",
           false,
           "transactions",
           {{"Transactions", "transactions"}, {"Auth", "auth"}, {"Investments", "investments"}, {"Liabilities", "liabilities"}, {"Identity", "identity"}}}}},

        {"mx",
         "MX Technologies",
         "mx",
         Category::OpenBanking,
         "M",
         "#0075BE",
         "Open banking with best-in-class data enrichment and normalization. Connects to 16,000+ institutions. Strong in financial wellness and lending analytics.",
         true,
         true,
         {{"clientId", "Client ID", FieldType::Text, "your-client-id", true, "", {}},
          {"apiKey", "API Key", FieldType::Password, "your-api-key", true, "", {}},
          {"environment",
           "Environment",
           FieldType::Select,
           "",
           false,
           "sandbox",
           {{"Sandbox", "sandbox"}, {"Production", "production"}}}}},

        {"finicity",
         "Finicity / Mastercard Open Banking",
         "finicity",
         Category::OpenBanking,
         "F",
         "#EB001B",
         "Mastercard-owned open banking platform. Strongest for lending, underwriting, and credit decisioning use cases. Covers 16,000+ US financial institutions.",
         true,
         true,
         {{"partnerId", "Partner ID", FieldType::Text, "your-partner-id", true, "", {}},
          {"partnerSecret", "Partner Secret", FieldType::Password, "your-secret", true, "", {}},
          {"appKey", "App Key", FieldType::Password, "your-app-key", true, "", {}},
          {"environment",
           "Environment",
           FieldType::Select,
           "",
           false,
           "sandbox",
           {{"Sandbox", "sandbox"}, {"Production", "production"}}}}},

        {"truelayer",
         "TrueLayer",
         "truelayer",
         Category::OpenBanking,
         "T",
         "#2CD5C4",
         "European and UK open banking connectivity. Covers PSD2-compliant access to 2,500+ banks across UK, EU, and Australia.",
         true,
         true,
         {{"clientId", "Client ID", FieldType::Text, "your-client-id", true, "", {}},
          {"clientSecret", "Client Secret", FieldType::Password, "your-client-secret", true, "", {}},
          {"environment",
           "Environment",
           FieldType::Select,
           "",
           false,
           "sandbox",
           {{"Sandbox", "sandbox"}, {"Production (UK)", "production-uk"}, {"Production (EU)", "production-eu"}}},
          {"scopes", "Scopes (space-separated)", FieldType::Text, "accounts balance transactions", false, "accounts balance transactions", {}}}},

        {"fdx-api",
         "FDX API",
         "fdx-api",
         Category::OpenBanking,
         "F",
         "#005B8E",
         "Financial Data Exchange v6.4 — the US regulatory-recognized standard (CFPB Section 1033). 114M consumer connections as of 2025. Direct FDX implementation.",
         true,
         true,
         {{"baseUrl", "FDX Provider Base URL", FieldType::Url, "https://api.yourbank.com/fdx/v6", true, "", {}},
          {"clientId", "OAuth2 Client ID", FieldType::Text, "your-client-id", true, "", {}},
          {"clientSecret", "OAuth2 Client Secret", FieldType::Password, "your-client-secret", true, "", {}},
          {"scope", "OAuth2 Scope", FieldType::Text, "fdx:accountbasic:read fdx:transactions:read", false, "fdx:accountbasic:read fdx:transactions:read", {}},
          {"version",
           "FDX Version",
           FieldType::Select,
           "",
           false,
           "v6",
           {{"FDX v6.4 (latest)", "v6"}, {"FDX v5.0", "v5"}, {"FDX v4.6", "v4"}}}}},
    };
}

static bool registered = [] {
    for (auto& c : open_banking_configs())
        ConnectorRegistry::instance().add(std::move(c));
    return true;
}();

} // namespace fincept::screens::datasources
